//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : adc_postproc_reg_block
// Unit            : adc_postproc_reg_block_pkg_uvm
// File            : adc_postproc_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 8/12/21 7:12 AM
//----------------------------------------------------------------------
// Title           : adc_postproc_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// adc_postproc_reg_block_pkg_uvm
//----------------------------------------------------------------------
package adc_postproc_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: reg_accum_bypass_reg
   // 
   // Decimator accumulator bypass
   //--------------------------------------------------------------------

   class reg_accum_bypass_reg extends uvm_reg;
      `uvm_object_utils(reg_accum_bypass_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field bypass_accum2; // bypass decimator 3rd integrator
      rand uvm_reg_field bypass_accum1; // bypass decimator 2nd integrator
      rand uvm_reg_field bypass_accum0; // bypass decimator 1st integrator


      // Function: coverage
      // 
      covergroup cg_vals;
         bypass_accum2	 : coverpoint bypass_accum2.value[0];
         bypass_accum1	 : coverpoint bypass_accum1.value[0];
         bypass_accum0	 : coverpoint bypass_accum0.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_accum_bypass_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         bypass_accum2 = uvm_reg_field::type_id::create("bypass_accum2");
         bypass_accum1 = uvm_reg_field::type_id::create("bypass_accum1");
         bypass_accum0 = uvm_reg_field::type_id::create("bypass_accum0");

         reserved.configure(this, 29, 3, "RW", 0, 29'b00000000000000000000000000000, 1, 0, 0);
         bypass_accum2.configure(this, 1, 2, "RW", 0, 1'b0, 1, 1, 0);
         bypass_accum1.configure(this, 1, 1, "RW", 0, 1'b0, 1, 1, 0);
         bypass_accum0.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_version_reg
   // 
   // ADC Post Processor version register
   //--------------------------------------------------------------------

   class reg_version_reg extends uvm_reg;
      `uvm_object_utils(reg_version_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field version; // version number


      // Function: coverage
      // 
      covergroup cg_vals;
         version	 : coverpoint version.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_version_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         version = uvm_reg_field::type_id::create("version");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         version.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_wdg_reg
   // 
   // watchdog register
   //--------------------------------------------------------------------

   class reg_wdg_reg extends uvm_reg;
      `uvm_object_utils(reg_wdg_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field wdg_cnt; // watchdog count


      // Function: coverage
      // 
      covergroup cg_vals;
         wdg_cnt	 : coverpoint wdg_cnt.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_wdg_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         wdg_cnt = uvm_reg_field::type_id::create("wdg_cnt");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         wdg_cnt.configure(this, 16, 0, "RW", 0, 16'h0040, 1, 1, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: adc_postproc_reg_block
   // 
   //--------------------------------------------------------------------

   class adc_postproc_reg_block extends uvm_reg_block;
      `uvm_object_utils(adc_postproc_reg_block)

      rand reg_version_reg reg_version; // ADC Post Processor version register
      rand reg_accum_bypass_reg reg_accum_bypass; // Decimator accumulator bypass
      rand reg_wdg_reg reg_wdg; // watchdog register

      uvm_reg_map adc_postproc_reg_block_map; 


      // Function: new
      // 
      function new(string name = "adc_postproc_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_version = reg_version_reg::type_id::create("reg_version");
         reg_version.configure(this);
         reg_version.build();

         reg_accum_bypass = reg_accum_bypass_reg::type_id::create("reg_accum_bypass");
         reg_accum_bypass.configure(this);
         reg_accum_bypass.build();

         reg_wdg = reg_wdg_reg::type_id::create("reg_wdg");
         reg_wdg.configure(this);
         reg_wdg.build();

         adc_postproc_reg_block_map = create_map("adc_postproc_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = adc_postproc_reg_block_map;

         adc_postproc_reg_block_map.add_reg(reg_version, 'h0, "RW");
         adc_postproc_reg_block_map.add_reg(reg_accum_bypass, 'h1c, "RW");
         adc_postproc_reg_block_map.add_reg(reg_wdg, 'h20, "RW");

         lock_model();
      endfunction
   endclass


endpackage
