//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : adc_clk_ctrl_reg_block
// Unit            : adc_clk_ctrl_reg_block_pkg_uvm
// File            : adc_clk_ctrl_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : puneeth.reddy
// Creation Date   : 8/9/21 1:29 AM
//----------------------------------------------------------------------
// Title           : adc_clk_ctrl_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// adc_clk_ctrl_reg_block_pkg_uvm
//----------------------------------------------------------------------
package adc_clk_ctrl_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: adc_clk_ctrl_reg_reg
   // 
   // controls the clock going into ADC block
   //--------------------------------------------------------------------

   class adc_clk_ctrl_reg_reg extends uvm_reg;
      `uvm_object_utils(adc_clk_ctrl_reg_reg)

      uvm_reg_field Reserved_24_31; // reserved
      rand uvm_reg_field clk_div_half_period; // Half of the clock divider period. eg: if the intended clock divisor is 4, the value programmed in this register should be 2.
      uvm_reg_field Reserved_9_15; // reserved
      rand uvm_reg_field conv_ncycles; // No of cycles the ADC clock will be active in a conversion. Note : reset value is 8'd256 or 8'h100


      // Function: coverage
      // 
      covergroup cg_vals;
         clk_div_half_period	 : coverpoint clk_div_half_period.value[7:0];
         conv_ncycles	 : coverpoint conv_ncycles.value[8:0];
      endgroup



      // Function: new
      // 
      function new(string name = "adc_clk_ctrl_reg_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         Reserved_24_31 = uvm_reg_field::type_id::create("Reserved_24_31");
         clk_div_half_period = uvm_reg_field::type_id::create("clk_div_half_period");
         Reserved_9_15 = uvm_reg_field::type_id::create("Reserved_9_15");
         conv_ncycles = uvm_reg_field::type_id::create("conv_ncycles");

         Reserved_24_31.configure(this, 8, 24, "RW", 1, 8'h00, 1, 0, 1);
         clk_div_half_period.configure(this, 8, 16, "RW", 0, 8'h00, 1, 1, 1);
         Reserved_9_15.configure(this, 7, 9, "RW", 1, 7'b0000000, 1, 0, 0);
         conv_ncycles.configure(this, 9, 0, "RW", 0, 9'b100000000, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: manual_ctrl_reg_reg
   // 
   // Manual control of ADC clock signals
   //--------------------------------------------------------------------

   class manual_ctrl_reg_reg extends uvm_reg;
      `uvm_object_utils(manual_ctrl_reg_reg)

      uvm_reg_field Reserved_2_31; // reserved
      rand uvm_reg_field manual_enable; // When programmable manual override is high and manual enable is high, (FORCE ENABLE)
      rand uvm_reg_field manual_override; // When programmable manual override is high and manual enable is low, (FORCE DISABLE)


      // Function: coverage
      // 
      covergroup cg_vals;
         manual_enable	 : coverpoint manual_enable.value[0];
         manual_override	 : coverpoint manual_override.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "manual_ctrl_reg_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         Reserved_2_31 = uvm_reg_field::type_id::create("Reserved_2_31");
         manual_enable = uvm_reg_field::type_id::create("manual_enable");
         manual_override = uvm_reg_field::type_id::create("manual_override");

         Reserved_2_31.configure(this, 30, 2, "RW", 1, 30'b000000000000000000000000000000, 1, 0, 0);
         manual_enable.configure(this, 1, 1, "RW", 0, 1'b0, 1, 1, 0);
         manual_override.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_block_revision_reg
   // 
   // Defines the revision ID of the adc_clk_ctrl reg block
   //--------------------------------------------------------------------

   class reg_block_revision_reg extends uvm_reg;
      `uvm_object_utils(reg_block_revision_reg)

      uvm_reg_field Reserved_16_31; // reserved
      uvm_reg_field id; // Defines the revision ID of the adc_clk_ctrl reg block


      // Function: coverage
      // 
      covergroup cg_vals;
         id	 : coverpoint id.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_block_revision_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         Reserved_16_31 = uvm_reg_field::type_id::create("Reserved_16_31");
         id = uvm_reg_field::type_id::create("id");

         Reserved_16_31.configure(this, 16, 16, "RW", 1, 16'h0000, 1, 0, 1);
         id.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: strobe_ctrl_reg_reg
   // 
   // controls strobe going into the ADC block
   //--------------------------------------------------------------------

   class strobe_ctrl_reg_reg extends uvm_reg;
      `uvm_object_utils(strobe_ctrl_reg_reg)

      uvm_reg_field Reserved_24_31; // reserved
      rand uvm_reg_field strobe_delay; // the adc_storbe signal is delayed by "N" core_clk's with respect to adc_clk edge.  N is the value programmed in this register


      // Function: coverage
      // 
      covergroup cg_vals;
         strobe_delay	 : coverpoint strobe_delay.value[7:0];
      endgroup



      // Function: new
      // 
      function new(string name = "strobe_ctrl_reg_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         Reserved_24_31 = uvm_reg_field::type_id::create("Reserved_24_31");
         strobe_delay = uvm_reg_field::type_id::create("strobe_delay");

         Reserved_24_31.configure(this, 24, 8, "RW", 1, 24'h000000, 1, 0, 1);
         strobe_delay.configure(this, 8, 0, "RW", 0, 8'h00, 1, 1, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: adc_clk_ctrl_reg_block
   // 
   //--------------------------------------------------------------------

   class adc_clk_ctrl_reg_block extends uvm_reg_block;
      `uvm_object_utils(adc_clk_ctrl_reg_block)

      rand reg_block_revision_reg reg_block_revision; // Defines the revision ID of the adc_clk_ctrl reg block
      rand strobe_ctrl_reg_reg strobe_ctrl_reg; // controls strobe going into the ADC block
      rand manual_ctrl_reg_reg manual_ctrl_reg; // Manual control of ADC clock signals
      rand adc_clk_ctrl_reg_reg adc_clk_ctrl_reg; // controls the clock going into ADC block

      uvm_reg_map adc_clk_ctrl_reg_block_map; 


      // Function: new
      // 
      function new(string name = "adc_clk_ctrl_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_block_revision = reg_block_revision_reg::type_id::create("reg_block_revision");
         reg_block_revision.configure(this);
         reg_block_revision.build();

         strobe_ctrl_reg = strobe_ctrl_reg_reg::type_id::create("strobe_ctrl_reg");
         strobe_ctrl_reg.configure(this);
         strobe_ctrl_reg.build();

         manual_ctrl_reg = manual_ctrl_reg_reg::type_id::create("manual_ctrl_reg");
         manual_ctrl_reg.configure(this);
         manual_ctrl_reg.build();

         adc_clk_ctrl_reg = adc_clk_ctrl_reg_reg::type_id::create("adc_clk_ctrl_reg");
         adc_clk_ctrl_reg.configure(this);
         adc_clk_ctrl_reg.build();

         adc_clk_ctrl_reg_block_map = create_map("adc_clk_ctrl_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = adc_clk_ctrl_reg_block_map;

         adc_clk_ctrl_reg_block_map.add_reg(reg_block_revision, 'h0, "RW");
         adc_clk_ctrl_reg_block_map.add_reg(strobe_ctrl_reg, 'h4, "RW");
         adc_clk_ctrl_reg_block_map.add_reg(manual_ctrl_reg, 'h8, "RW");
         adc_clk_ctrl_reg_block_map.add_reg(adc_clk_ctrl_reg, 'hc, "RW");

         lock_model();
      endfunction
   endclass


endpackage
