//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : adc_postproc_reg_block
// File            : /home/daniel.lee/cdssen/senUintah/adc_postproc/reg_gen/output/adc_postproc_reg_block.v
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 12 08 2021 07:12::15
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : adc_postproc_reg_block
// Address Range   : 0x24
//----------------------------------------------------------------------

module adc_postproc_reg_block
#(
  parameter ADDR_WIDTH=6,
  parameter DATA_WIDTH=32
)
(

  // FIELD OUTPUT PORTS
  output reg          bypass_accum2_reg_accum_bypass,
  output reg          bypass_accum1_reg_accum_bypass,
  output reg          bypass_accum0_reg_accum_bypass,
  output reg   [15:0] wdg_cnt_reg_wdg               ,

  // FIELD INPUT PORTS
  input wire   [15:0] version_reg_version_ip,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);

  // READ/WRITE ENABLE SIGNALS
  reg  wen_reg_accum_bypass;
  reg  wen_reg_wdg         ;

  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_version     ;
  wire [DATA_WIDTH-1:0] rmux_reg_accum_bypass;
  wire [DATA_WIDTH-1:0] rmux_reg_wdg         ;

  // FLIP-FLOP SIGNALS
  reg  [15:0] version_reg_version_local;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_VERSION_ADDR = 6'h00;
  localparam REG_ACCUM_BYPASS_ADDR = 6'h1C;
  localparam REG_WDG_ADDR = 6'h20;

  //----------------------------------------------------------------------
  //                    WRITE ADDRESS DECODE
  //----------------------------------------------------------------------
  always @ ( * )
  begin : write_enable
    wen_reg_accum_bypass = 1'b0;
    wen_reg_wdg = 1'b0;
    waddrerr = 1'b0;
    wack = 1'b0;

    if (wstrobe)
    begin
      case (waddr)
        REG_ACCUM_BYPASS_ADDR:
        begin
          wen_reg_accum_bypass = 1'b1;
        end
        REG_WDG_ADDR:
        begin
          wen_reg_wdg = 1'b1;
        end
        default:
        begin
          waddrerr = 1'b1;
        end
      endcase
      wack = 1'b1;
    end
  end


  //------------------------------------------------------------
  // Register: reg_version_reg
  //   ADC Post Processor version register
  //   SW Access     : read-write
  //   Address Offset: 0x00
  //   HW Access     : read-write
  // 
  // Instance: reg_version
  //   ADC Post Processor version register
  //   Address Offset: 0x00
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:0  version (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: version                                
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   version number
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_version_reg_version_reg_version_local
    // Reset
    if ( !reset )
      version_reg_version_local <= 16'h0000;
    // HW:write-only
    else
      version_reg_version_local <= version_reg_version_ip;
  end


  //------------------------------------------------------------
  // Register: reg_accum_bypass_reg
  //   Decimator accumulator bypass
  //   SW Access     : read-write
  //   Address Offset: 0x1C
  //   HW Access     : read-write
  // 
  // Instance: reg_accum_bypass
  //   Decimator accumulator bypass
  //   Address Offset: 0x1C
  //   Reset Value   : 
  // 
  // Fields:
  //   31:3  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //     2  bypass_accum2 (SW:read-write, HW:read-only)
  //     1  bypass_accum1 (SW:read-write, HW:read-only)
  //     0  bypass_accum0 (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 29                  , Offset: 3              
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: bypass_accum2                          
  //   Width: 1              , Offset: 2             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   bypass decimator 3rd integrator
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_accum_bypass_reg_bypass_accum2_reg_accum_bypass
    // Reset
    if ( !reset )
      bypass_accum2_reg_accum_bypass <= 1'b0;
    // SW:read-write
    else if (wen_reg_accum_bypass)
      bypass_accum2_reg_accum_bypass <= wdata[2];
  end

  //------------------------------------------------------------
  //   Field: bypass_accum1                          
  //   Width: 1              , Offset: 1             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   bypass decimator 2nd integrator
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_accum_bypass_reg_bypass_accum1_reg_accum_bypass
    // Reset
    if ( !reset )
      bypass_accum1_reg_accum_bypass <= 1'b0;
    // SW:read-write
    else if (wen_reg_accum_bypass)
      bypass_accum1_reg_accum_bypass <= wdata[1];
  end

  //------------------------------------------------------------
  //   Field: bypass_accum0                          
  //   Width: 1              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   bypass decimator 1st integrator
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_accum_bypass_reg_bypass_accum0_reg_accum_bypass
    // Reset
    if ( !reset )
      bypass_accum0_reg_accum_bypass <= 1'b0;
    // SW:read-write
    else if (wen_reg_accum_bypass)
      bypass_accum0_reg_accum_bypass <= wdata[0];
  end


  //------------------------------------------------------------
  // Register: reg_wdg_reg
  //   watchdog register
  //   SW Access     : read-write
  //   Address Offset: 0x20
  //   HW Access     : read-write
  // 
  // Instance: reg_wdg
  //   watchdog register
  //   Address Offset: 0x20
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:0  wdg_cnt (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: wdg_cnt                                
  //   Width: 16             , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   watchdog count
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_wdg_reg_wdg_cnt_reg_wdg
    // Reset
    if ( !reset )
      wdg_cnt_reg_wdg <= 16'h0040;
    // SW:read-write
    else if (wen_reg_wdg)
      wdg_cnt_reg_wdg <= wdata[15:0];
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_version[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_version[15:0] = version_reg_version_local;

  assign rmux_reg_accum_bypass[31:3] = DEF_RDATA_VAL[31:3]; // Default read value for RESERVED field - reserved
  assign rmux_reg_accum_bypass[2] = bypass_accum2_reg_accum_bypass;
  assign rmux_reg_accum_bypass[1] = bypass_accum1_reg_accum_bypass;
  assign rmux_reg_accum_bypass[0] = bypass_accum0_reg_accum_bypass;

  assign rmux_reg_wdg[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_wdg[15:0] = wdg_cnt_reg_wdg;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_VERSION_ADDR:
        begin
          rdata = rmux_reg_version;
        end
        REG_ACCUM_BYPASS_ADDR:
        begin
          rdata = rmux_reg_accum_bypass;
        end
        REG_WDG_ADDR:
        begin
          rdata = rmux_reg_wdg;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

