//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : adc_clk_ctrl_reg_block
// File            : /home/puneeth/cdssen/senUintah/adc_clk_ctrl/reg_gen/output/adc_clk_ctrl_reg_block.v
//----------------------------------------------------------------------
// Created by      : puneeth.reddy
// Creation Date   : 09 08 2021 01:29::24
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : adc_clk_ctrl_reg_block
// Address Range   : 0x10
//----------------------------------------------------------------------

module adc_clk_ctrl_reg_block
#(
  parameter ADDR_WIDTH=5,
  parameter DATA_WIDTH=32
)
(

  // FIELD OUTPUT PORTS
  output reg   [7:0] strobe_delay_strobe_ctrl_reg        ,
  output reg         manual_enable_manual_ctrl_reg       ,
  output reg         manual_override_manual_ctrl_reg     ,
  output reg   [7:0] clk_div_half_period_adc_clk_ctrl_reg,
  output reg   [8:0] conv_ncycles_adc_clk_ctrl_reg       ,

  // FIELD INPUT PORTS
  input wire   [15:0] id_reg_block_revision_ip,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);

  // READ/WRITE ENABLE SIGNALS
  reg  wen_strobe_ctrl_reg ;
  reg  wen_manual_ctrl_reg ;
  reg  wen_adc_clk_ctrl_reg;

  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_block_revision;
  wire [DATA_WIDTH-1:0] rmux_strobe_ctrl_reg   ;
  wire [DATA_WIDTH-1:0] rmux_manual_ctrl_reg   ;
  wire [DATA_WIDTH-1:0] rmux_adc_clk_ctrl_reg  ;

  // FLIP-FLOP SIGNALS
  reg  [15:0] id_reg_block_revision_local;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_BLOCK_REVISION_ADDR = 5'h00;
  localparam STROBE_CTRL_REG_ADDR = 5'h04;
  localparam MANUAL_CTRL_REG_ADDR = 5'h08;
  localparam ADC_CLK_CTRL_REG_ADDR = 5'h0C;

  //----------------------------------------------------------------------
  //                    WRITE ADDRESS DECODE
  //----------------------------------------------------------------------
  always @ ( * )
  begin : write_enable
    wen_strobe_ctrl_reg = 1'b0;
    wen_manual_ctrl_reg = 1'b0;
    wen_adc_clk_ctrl_reg = 1'b0;
    waddrerr = 1'b0;
    wack = 1'b0;

    if (wstrobe)
    begin
      case (waddr)
        STROBE_CTRL_REG_ADDR:
        begin
          wen_strobe_ctrl_reg = 1'b1;
        end
        MANUAL_CTRL_REG_ADDR:
        begin
          wen_manual_ctrl_reg = 1'b1;
        end
        ADC_CLK_CTRL_REG_ADDR:
        begin
          wen_adc_clk_ctrl_reg = 1'b1;
        end
        default:
        begin
          waddrerr = 1'b1;
        end
      endcase
      wack = 1'b1;
    end
  end


  //------------------------------------------------------------
  // Register: reg_block_revision_reg
  //   Defines the revision ID of the adc_clk_ctrl reg block
  //   SW Access     : read-write
  //   Address Offset: 0x0
  //   HW Access     : read-write
  // 
  // Instance: reg_block_revision
  //   Defines the revision ID of the adc_clk_ctrl reg block
  //   Address Offset: 0x0
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  Reserved_16_31 (SW:read-write, HW:read-only) (RESERVED) 
  //   15:0  id (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: Reserved_16_31 (reserved)                         
  //   Width: 16                        , Offset: 16            
  //   SW Access: read-write            , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: id                                     
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   Defines the revision ID of the adc_clk_ctrl reg block
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_block_revision_reg_id_reg_block_revision_local
    // Reset
    if ( !reset )
      id_reg_block_revision_local <= 16'h0000;
    // HW:write-only
    else
      id_reg_block_revision_local <= id_reg_block_revision_ip;
  end


  //------------------------------------------------------------
  // Register: strobe_ctrl_reg_reg
  //   controls strobe going into the ADC block
  //   SW Access     : read-write
  //   Address Offset: 0x4
  //   HW Access     : read-write
  // 
  // Instance: strobe_ctrl_reg
  //   controls strobe going into the ADC block
  //   Address Offset: 0x4
  //   Reset Value   : 
  // 
  // Fields:
  //   31:8  Reserved_24_31 (SW:read-write, HW:read-only) (RESERVED) 
  //   7:0  strobe_delay (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: Reserved_24_31 (reserved)                         
  //   Width: 24                        , Offset: 8             
  //   SW Access: read-write            , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: strobe_delay                           
  //   Width: 8              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   the adc_storbe signal is delayed by "N" core_clk's with respect to adc_clk edge.  N is the value programmed in this register
  //
  always @ (posedge clock or negedge reset)
  begin : reg_strobe_ctrl_reg_reg_strobe_delay_strobe_ctrl_reg
    // Reset
    if ( !reset )
      strobe_delay_strobe_ctrl_reg <= 8'h00;
    // SW:read-write
    else if (wen_strobe_ctrl_reg)
      strobe_delay_strobe_ctrl_reg <= wdata[7:0];
  end


  //------------------------------------------------------------
  // Register: manual_ctrl_reg_reg
  //   Manual control of ADC clock signals
  //   SW Access     : read-write
  //   Address Offset: 0x8
  //   HW Access     : read-write
  // 
  // Instance: manual_ctrl_reg
  //   Manual control of ADC clock signals
  //   Address Offset: 0x8
  //   Reset Value   : 
  // 
  // Fields:
  //   31:2  Reserved_2_31 (SW:read-write, HW:read-only) (RESERVED) 
  //     1  manual_enable (SW:read-write, HW:read-only)
  //     0  manual_override (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: Reserved_2_31 (reserved)                         
  //   Width: 30                       , Offset: 2             
  //   SW Access: read-write           , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: manual_enable                          
  //   Width: 1              , Offset: 1             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   When programmable manual override is high and manual enable is high, (FORCE ENABLE)
  //
  always @ (posedge clock or negedge reset)
  begin : reg_manual_ctrl_reg_reg_manual_enable_manual_ctrl_reg
    // Reset
    if ( !reset )
      manual_enable_manual_ctrl_reg <= 1'b0;
    // SW:read-write
    else if (wen_manual_ctrl_reg)
      manual_enable_manual_ctrl_reg <= wdata[1];
  end

  //------------------------------------------------------------
  //   Field: manual_override                         
  //   Width: 1               , Offset: 0             
  //   SW Access: read-write  , HW Access: read-only  
  //------------------------------------------------------------
  //   When programmable manual override is high and manual enable is low, (FORCE DISABLE)
  //
  always @ (posedge clock or negedge reset)
  begin : reg_manual_ctrl_reg_reg_manual_override_manual_ctrl_reg
    // Reset
    if ( !reset )
      manual_override_manual_ctrl_reg <= 1'b0;
    // SW:read-write
    else if (wen_manual_ctrl_reg)
      manual_override_manual_ctrl_reg <= wdata[0];
  end


  //------------------------------------------------------------
  // Register: adc_clk_ctrl_reg_reg
  //   controls the clock going into ADC block
  //   SW Access     : read-write
  //   Address Offset: 0xC
  //   HW Access     : read-write
  // 
  // Instance: adc_clk_ctrl_reg
  //   controls the clock going into ADC block
  //   Address Offset: 0xC
  //   Reset Value   : 
  // 
  // Fields:
  //   31:24  Reserved_24_31 (SW:read-write, HW:read-only) (RESERVED) 
  //   23:16  clk_div_half_period (SW:read-write, HW:read-only)
  //   15:9  Reserved_9_15 (SW:read-write, HW:read-only) (RESERVED) 
  //   8:0  conv_ncycles (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: Reserved_24_31 (reserved)                         
  //   Width: 8                         , Offset: 24            
  //   SW Access: read-write            , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: clk_div_half_period                         
  //   Width: 8                   , Offset: 16            
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   Half of the clock divider period. eg: if the intended clock divisor is 4, the value programmed in this register should be 2.
  //
  always @ (posedge clock or negedge reset)
  begin : reg_adc_clk_ctrl_reg_reg_clk_div_half_period_adc_clk_ctrl_reg
    // Reset
    if ( !reset )
      clk_div_half_period_adc_clk_ctrl_reg <= 8'h00;
    // SW:read-write
    else if (wen_adc_clk_ctrl_reg)
      clk_div_half_period_adc_clk_ctrl_reg <= wdata[23:16];
  end

  //------------------------------------------------------------
  //   Field: Reserved_9_15 (reserved)                         
  //   Width: 7                        , Offset: 9             
  //   SW Access: read-write           , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: conv_ncycles                           
  //   Width: 9              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   No of cycles the ADC clock will be active in a conversion. Note : reset value is 8'd256 or 8'h100
  //
  always @ (posedge clock or negedge reset)
  begin : reg_adc_clk_ctrl_reg_reg_conv_ncycles_adc_clk_ctrl_reg
    // Reset
    if ( !reset )
      conv_ncycles_adc_clk_ctrl_reg <= 9'h100;
    // SW:read-write
    else if (wen_adc_clk_ctrl_reg)
      conv_ncycles_adc_clk_ctrl_reg <= wdata[8:0];
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_block_revision[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - Reserved_16_31
  assign rmux_reg_block_revision[15:0] = id_reg_block_revision_local;

  assign rmux_strobe_ctrl_reg[31:8] = DEF_RDATA_VAL[31:8]; // Default read value for RESERVED field - Reserved_24_31
  assign rmux_strobe_ctrl_reg[7:0] = strobe_delay_strobe_ctrl_reg;

  assign rmux_manual_ctrl_reg[31:2] = DEF_RDATA_VAL[31:2]; // Default read value for RESERVED field - Reserved_2_31
  assign rmux_manual_ctrl_reg[1] = manual_enable_manual_ctrl_reg;
  assign rmux_manual_ctrl_reg[0] = manual_override_manual_ctrl_reg;

  assign rmux_adc_clk_ctrl_reg[31:24] = DEF_RDATA_VAL[31:24]; // Default read value for RESERVED field - Reserved_24_31
  assign rmux_adc_clk_ctrl_reg[23:16] = clk_div_half_period_adc_clk_ctrl_reg;
  assign rmux_adc_clk_ctrl_reg[15:9] = DEF_RDATA_VAL[15:9]; // Default read value for RESERVED field - Reserved_9_15
  assign rmux_adc_clk_ctrl_reg[8:0] = conv_ncycles_adc_clk_ctrl_reg;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_BLOCK_REVISION_ADDR:
        begin
          rdata = rmux_reg_block_revision;
        end
        STROBE_CTRL_REG_ADDR:
        begin
          rdata = rmux_strobe_ctrl_reg;
        end
        MANUAL_CTRL_REG_ADDR:
        begin
          rdata = rmux_manual_ctrl_reg;
        end
        ADC_CLK_CTRL_REG_ADDR:
        begin
          rdata = rmux_adc_clk_ctrl_reg;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

