//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : analog_config_reg_block
// Unit            : analog_config_reg_block_pkg_uvm
// File            : analog_config_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 8/25/21 10:41 PM
//----------------------------------------------------------------------
// Title           : analog_config_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// analog_config_reg_block_pkg_uvm
//----------------------------------------------------------------------
package analog_config_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: reg_config_afe_mux_sel_reg
   // 
   // WLM currenet select for amux
   //--------------------------------------------------------------------

   class reg_config_afe_mux_sel_reg extends uvm_reg;
      `uvm_object_utils(reg_config_afe_mux_sel_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field afe_mux_sel; // WLM current select for AMUX


      // Function: coverage
      // 
      covergroup cg_vals;
         afe_mux_sel	 : coverpoint afe_mux_sel.value[5:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_config_afe_mux_sel_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         afe_mux_sel = uvm_reg_field::type_id::create("afe_mux_sel");

         reserved.configure(this, 26, 6, "RW", 0, 26'b00000000000000000000000000, 1, 0, 0);
         afe_mux_sel.configure(this, 6, 0, "RW", 0, 6'b000000, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_config_amux_reg
   // 
   // AMUX Enable Configuration Register
   //--------------------------------------------------------------------

   class reg_config_amux_reg extends uvm_reg;
      `uvm_object_utils(reg_config_amux_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field en_amux_output; // Enable amux


      // Function: coverage
      // 
      covergroup cg_vals;
         en_amux_output	 : coverpoint en_amux_output.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_config_amux_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         en_amux_output = uvm_reg_field::type_id::create("en_amux_output");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         en_amux_output.configure(this, 16, 0, "RW", 0, 16'h0000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_config_amux_sel_reg
   // 
   // AMUX Select Configuration Register
   //--------------------------------------------------------------------

   class reg_config_amux_sel_reg extends uvm_reg;
      `uvm_object_utils(reg_config_amux_sel_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field alg_amux_sel; // Enable amux


      // Function: coverage
      // 
      covergroup cg_vals;
         alg_amux_sel	 : coverpoint alg_amux_sel.value[11:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_config_amux_sel_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         alg_amux_sel = uvm_reg_field::type_id::create("alg_amux_sel");

         reserved.configure(this, 20, 12, "RW", 0, 20'h00000, 1, 0, 0);
         alg_amux_sel.configure(this, 12, 0, "RW", 0, 12'h000, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_config_bypass_reg
   // 
   // Bypass Configuration Register
   //--------------------------------------------------------------------

   class reg_config_bypass_reg extends uvm_reg;
      `uvm_object_utils(reg_config_bypass_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field bypass_ts_afe; // Bypass Temp Sensor Analog Front End
      rand uvm_reg_field bypass_wlm_afe; // Bypass WLM Analog Front End
      rand uvm_reg_field bypass_tia; // Bypass TIA


      // Function: coverage
      // 
      covergroup cg_vals;
         bypass_ts_afe	 : coverpoint bypass_ts_afe.value[0];
         bypass_wlm_afe	 : coverpoint bypass_wlm_afe.value[0];
         bypass_tia	 : coverpoint bypass_tia.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_config_bypass_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         bypass_ts_afe = uvm_reg_field::type_id::create("bypass_ts_afe");
         bypass_wlm_afe = uvm_reg_field::type_id::create("bypass_wlm_afe");
         bypass_tia = uvm_reg_field::type_id::create("bypass_tia");

         reserved.configure(this, 29, 3, "RW", 0, 29'b00000000000000000000000000000, 1, 0, 0);
         bypass_ts_afe.configure(this, 1, 2, "RW", 0, 1'b0, 1, 1, 0);
         bypass_wlm_afe.configure(this, 1, 1, "RW", 0, 1'b0, 1, 1, 0);
         bypass_tia.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_config_dmux_sel_reg
   // 
   // DMUX Select Configuration Register
   //--------------------------------------------------------------------

   class reg_config_dmux_sel_reg extends uvm_reg;
      `uvm_object_utils(reg_config_dmux_sel_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field alg_dmux_sel; // Enable amux


      // Function: coverage
      // 
      covergroup cg_vals;
         alg_dmux_sel	 : coverpoint alg_dmux_sel.value[23:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_config_dmux_sel_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         alg_dmux_sel = uvm_reg_field::type_id::create("alg_dmux_sel");

         reserved.configure(this, 8, 24, "RW", 0, 8'h00, 1, 0, 1);
         alg_dmux_sel.configure(this, 24, 0, "RW", 0, 24'h000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_config_rx_reg
   // 
   // Rx Configuration Register
   //--------------------------------------------------------------------

   class reg_config_rx_reg extends uvm_reg;
      `uvm_object_utils(reg_config_rx_reg)

      uvm_reg_field reserved2; // reserved 2nd
      rand uvm_reg_field pd_rx_n; // Power Down Receive Block
      uvm_reg_field reserved; // reserved
      rand uvm_reg_field itrim_rx; // RX Current Trim


      // Function: coverage
      // 
      covergroup cg_vals;
         pd_rx_n	 : coverpoint pd_rx_n.value[4:0];
         itrim_rx	 : coverpoint itrim_rx.value[3:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_config_rx_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved2 = uvm_reg_field::type_id::create("reserved2");
         pd_rx_n = uvm_reg_field::type_id::create("pd_rx_n");
         reserved = uvm_reg_field::type_id::create("reserved");
         itrim_rx = uvm_reg_field::type_id::create("itrim_rx");

         reserved2.configure(this, 19, 13, "RW", 0, 19'b0000000000000000000, 1, 0, 0);
         pd_rx_n.configure(this, 5, 8, "RW", 0, 5'b00000, 1, 1, 0);
         reserved.configure(this, 4, 4, "RW", 0, 4'h0, 1, 0, 0);
         itrim_rx.configure(this, 4, 0, "RW", 0, 4'h0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_config_tx_reg
   // 
   // Tx Configuration Register
   //--------------------------------------------------------------------

   class reg_config_tx_reg extends uvm_reg;
      `uvm_object_utils(reg_config_tx_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field pd_tx_n; // Power Down Transmit Block (active low)
      rand uvm_reg_field itrim_tx; // TX Current Trim


      // Function: coverage
      // 
      covergroup cg_vals;
         pd_tx_n	 : coverpoint pd_tx_n.value[3:0];
         itrim_tx	 : coverpoint itrim_tx.value[3:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_config_tx_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         pd_tx_n = uvm_reg_field::type_id::create("pd_tx_n");
         itrim_tx = uvm_reg_field::type_id::create("itrim_tx");

         reserved.configure(this, 24, 8, "RW", 0, 24'h000000, 1, 0, 1);
         pd_tx_n.configure(this, 4, 4, "RW", 0, 4'h0, 1, 1, 0);
         itrim_tx.configure(this, 4, 0, "RW", 0, 4'h0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_status_reg
   // 
   // Status Register
   //--------------------------------------------------------------------

   class reg_status_reg extends uvm_reg;
      `uvm_object_utils(reg_status_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field watchdog_active; // Watchdog Active


      // Function: coverage
      // 
      covergroup cg_vals;
         watchdog_active	 : coverpoint watchdog_active.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_status_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         watchdog_active = uvm_reg_field::type_id::create("watchdog_active");

         reserved.configure(this, 31, 1, "RO", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         watchdog_active.configure(this, 1, 0, "RO", 1, 1'b0, 1, 0, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_version_reg
   // 
   // Arbiter version register
   //--------------------------------------------------------------------

   class reg_version_reg extends uvm_reg;
      `uvm_object_utils(reg_version_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field version; // version number


      // Function: coverage
      // 
      covergroup cg_vals;
         version	 : coverpoint version.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_version_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         version = uvm_reg_field::type_id::create("version");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         version.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: analog_config_reg_block
   // 
   //--------------------------------------------------------------------

   class analog_config_reg_block extends uvm_reg_block;
      `uvm_object_utils(analog_config_reg_block)

      rand reg_version_reg reg_version; // Arbiter version register
      rand reg_config_tx_reg reg_config_tx; // Tx Configuration Register
      rand reg_config_rx_reg reg_config_rx; // Rx Configuration Register
      rand reg_config_bypass_reg reg_config_bypass; // Bypass Configuration Register
      rand reg_config_afe_mux_sel_reg reg_config_afe_mux_sel; // WLM currenet select for amux
      rand reg_config_amux_reg reg_config_amux; // AMUX Enable Configuration Register
      rand reg_config_amux_sel_reg reg_config_amux_sel; // AMUX Select Configuration Register
      rand reg_config_dmux_sel_reg reg_config_dmux_sel; // DMUX Select Configuration Register
      rand reg_status_reg reg_status; // Status Register

      uvm_reg_map analog_config_reg_block_map; 


      // Function: new
      // 
      function new(string name = "analog_config_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_version = reg_version_reg::type_id::create("reg_version");
         reg_version.configure(this);
         reg_version.build();

         reg_config_tx = reg_config_tx_reg::type_id::create("reg_config_tx");
         reg_config_tx.configure(this);
         reg_config_tx.build();

         reg_config_rx = reg_config_rx_reg::type_id::create("reg_config_rx");
         reg_config_rx.configure(this);
         reg_config_rx.build();

         reg_config_bypass = reg_config_bypass_reg::type_id::create("reg_config_bypass");
         reg_config_bypass.configure(this);
         reg_config_bypass.build();

         reg_config_afe_mux_sel = reg_config_afe_mux_sel_reg::type_id::create("reg_config_afe_mux_sel");
         reg_config_afe_mux_sel.configure(this);
         reg_config_afe_mux_sel.build();

         reg_config_amux = reg_config_amux_reg::type_id::create("reg_config_amux");
         reg_config_amux.configure(this);
         reg_config_amux.build();

         reg_config_amux_sel = reg_config_amux_sel_reg::type_id::create("reg_config_amux_sel");
         reg_config_amux_sel.configure(this);
         reg_config_amux_sel.build();

         reg_config_dmux_sel = reg_config_dmux_sel_reg::type_id::create("reg_config_dmux_sel");
         reg_config_dmux_sel.configure(this);
         reg_config_dmux_sel.build();

         reg_status = reg_status_reg::type_id::create("reg_status");
         reg_status.configure(this);
         reg_status.build();

         analog_config_reg_block_map = create_map("analog_config_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = analog_config_reg_block_map;

         analog_config_reg_block_map.add_reg(reg_version, 'h0, "RW");
         analog_config_reg_block_map.add_reg(reg_config_tx, 'h10, "RW");
         analog_config_reg_block_map.add_reg(reg_config_rx, 'h14, "RW");
         analog_config_reg_block_map.add_reg(reg_config_bypass, 'h18, "RW");
         analog_config_reg_block_map.add_reg(reg_config_afe_mux_sel, 'h1c, "RW");
         analog_config_reg_block_map.add_reg(reg_config_amux, 'h20, "RW");
         analog_config_reg_block_map.add_reg(reg_config_amux_sel, 'h24, "RW");
         analog_config_reg_block_map.add_reg(reg_config_dmux_sel, 'h28, "RW");
         analog_config_reg_block_map.add_reg(reg_status, 'h30, "RO");

         lock_model();
      endfunction
   endclass


endpackage
