//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : analog_config_reg_block
// File            : /home/daniel.lee/cdssen/senUintah/analog_config/reg_gen/output/analog_config_reg_block.v
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 25 08 2021 22:41::47
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : analog_config_reg_block
// Address Range   : 0x34
//----------------------------------------------------------------------

module analog_config_reg_block
#(
  parameter ADDR_WIDTH=6,
  parameter DATA_WIDTH=32
)
(

  // FIELD OUTPUT PORTS
  output reg   [3:0]  pd_tx_n_reg_config_tx             ,
  output reg   [3:0]  itrim_tx_reg_config_tx            ,
  output reg   [4:0]  pd_rx_n_reg_config_rx             ,
  output reg   [3:0]  itrim_rx_reg_config_rx            ,
  output reg          bypass_ts_afe_reg_config_bypass   ,
  output reg          bypass_wlm_afe_reg_config_bypass  ,
  output reg          bypass_tia_reg_config_bypass      ,
  output reg   [5:0]  afe_mux_sel_reg_config_afe_mux_sel,
  output reg   [15:0] en_amux_output_reg_config_amux    ,
  output reg   [11:0] alg_amux_sel_reg_config_amux_sel  ,
  output reg   [23:0] alg_dmux_sel_reg_config_dmux_sel  ,

  // FIELD INPUT PORTS
  input wire   [15:0] version_reg_version_ip       ,
  input wire          watchdog_active_reg_status_ip,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);

  // READ/WRITE ENABLE SIGNALS
  reg  wen_reg_config_tx         ;
  reg  wen_reg_config_rx         ;
  reg  wen_reg_config_bypass     ;
  reg  wen_reg_config_afe_mux_sel;
  reg  wen_reg_config_amux       ;
  reg  wen_reg_config_amux_sel   ;
  reg  wen_reg_config_dmux_sel   ;

  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_version           ;
  wire [DATA_WIDTH-1:0] rmux_reg_config_tx         ;
  wire [DATA_WIDTH-1:0] rmux_reg_config_rx         ;
  wire [DATA_WIDTH-1:0] rmux_reg_config_bypass     ;
  wire [DATA_WIDTH-1:0] rmux_reg_config_afe_mux_sel;
  wire [DATA_WIDTH-1:0] rmux_reg_config_amux       ;
  wire [DATA_WIDTH-1:0] rmux_reg_config_amux_sel   ;
  wire [DATA_WIDTH-1:0] rmux_reg_config_dmux_sel   ;
  wire [DATA_WIDTH-1:0] rmux_reg_status            ;

  // FLIP-FLOP SIGNALS
  reg  [15:0] version_reg_version_local       ;
  reg         watchdog_active_reg_status_local;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_VERSION_ADDR = 6'h00;
  localparam REG_CONFIG_TX_ADDR = 6'h10;
  localparam REG_CONFIG_RX_ADDR = 6'h14;
  localparam REG_CONFIG_BYPASS_ADDR = 6'h18;
  localparam REG_CONFIG_AFE_MUX_SEL_ADDR = 6'h1C;
  localparam REG_CONFIG_AMUX_ADDR = 6'h20;
  localparam REG_CONFIG_AMUX_SEL_ADDR = 6'h24;
  localparam REG_CONFIG_DMUX_SEL_ADDR = 6'h28;
  localparam REG_STATUS_ADDR = 6'h30;

  //----------------------------------------------------------------------
  //                    WRITE ADDRESS DECODE
  //----------------------------------------------------------------------
  always @ ( * )
  begin : write_enable
    wen_reg_config_tx = 1'b0;
    wen_reg_config_rx = 1'b0;
    wen_reg_config_bypass = 1'b0;
    wen_reg_config_afe_mux_sel = 1'b0;
    wen_reg_config_amux = 1'b0;
    wen_reg_config_amux_sel = 1'b0;
    wen_reg_config_dmux_sel = 1'b0;
    waddrerr = 1'b0;
    wack = 1'b0;

    if (wstrobe)
    begin
      case (waddr)
        REG_CONFIG_TX_ADDR:
        begin
          wen_reg_config_tx = 1'b1;
        end
        REG_CONFIG_RX_ADDR:
        begin
          wen_reg_config_rx = 1'b1;
        end
        REG_CONFIG_BYPASS_ADDR:
        begin
          wen_reg_config_bypass = 1'b1;
        end
        REG_CONFIG_AFE_MUX_SEL_ADDR:
        begin
          wen_reg_config_afe_mux_sel = 1'b1;
        end
        REG_CONFIG_AMUX_ADDR:
        begin
          wen_reg_config_amux = 1'b1;
        end
        REG_CONFIG_AMUX_SEL_ADDR:
        begin
          wen_reg_config_amux_sel = 1'b1;
        end
        REG_CONFIG_DMUX_SEL_ADDR:
        begin
          wen_reg_config_dmux_sel = 1'b1;
        end
        default:
        begin
          waddrerr = 1'b1;
        end
      endcase
      wack = 1'b1;
    end
  end


  //------------------------------------------------------------
  // Register: reg_version_reg
  //   Arbiter version register
  //   SW Access     : read-write
  //   Address Offset: 0x00
  //   HW Access     : read-write
  // 
  // Instance: reg_version
  //   Arbiter version register
  //   Address Offset: 0x00
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:0  version (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: version                                
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   version number
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_version_reg_version_reg_version_local
    // Reset
    if ( !reset )
      version_reg_version_local <= 16'h0000;
    // HW:write-only
    else
      version_reg_version_local <= version_reg_version_ip;
  end


  //------------------------------------------------------------
  // Register: reg_config_tx_reg
  //   Tx Configuration Register
  //   SW Access     : read-write
  //   Address Offset: 0x10
  //   HW Access     : read-only
  // 
  // Instance: reg_config_tx
  //   Tx Configuration Register
  //   Address Offset: 0x10
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:8  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //   7:4  pd_tx_n (SW:read-write, HW:read-only)
  //   3:0  itrim_tx (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 24                  , Offset: 8             
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: pd_tx_n                                
  //   Width: 4              , Offset: 4             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Power Down Transmit Block (active low)
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_tx_reg_pd_tx_n_reg_config_tx
    // Reset
    if ( !reset )
      pd_tx_n_reg_config_tx <= 4'h0;
    // SW:read-write
    else if (wen_reg_config_tx)
      pd_tx_n_reg_config_tx <= wdata[7:4];
  end

  //------------------------------------------------------------
  //   Field: itrim_tx                               
  //   Width: 4              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   TX Current Trim
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_tx_reg_itrim_tx_reg_config_tx
    // Reset
    if ( !reset )
      itrim_tx_reg_config_tx <= 4'h0;
    // SW:read-write
    else if (wen_reg_config_tx)
      itrim_tx_reg_config_tx <= wdata[3:0];
  end


  //------------------------------------------------------------
  // Register: reg_config_rx_reg
  //   Rx Configuration Register
  //   SW Access     : read-write
  //   Address Offset: 0x14
  //   HW Access     : read-only
  // 
  // Instance: reg_config_rx
  //   Rx Configuration Register
  //   Address Offset: 0x14
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:13  reserved2 (SW:read-write, HW:read-only) (RESERVED) 
  //   12:8  pd_rx_n (SW:read-write, HW:read-only)
  //   7:4  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //   3:0  itrim_rx (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved2 (reserved)                         
  //   Width: 19                   , Offset: 13            
  //   SW Access: read-write       , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved 2nd
  //

  //------------------------------------------------------------
  //   Field: pd_rx_n                                
  //   Width: 5              , Offset: 8             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Power Down Receive Block
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_rx_reg_pd_rx_n_reg_config_rx
    // Reset
    if ( !reset )
      pd_rx_n_reg_config_rx <= 5'b00000;
    // SW:read-write
    else if (wen_reg_config_rx)
      pd_rx_n_reg_config_rx <= wdata[12:8];
  end

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 4                   , Offset: 4             
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: itrim_rx                               
  //   Width: 4              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   RX Current Trim
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_rx_reg_itrim_rx_reg_config_rx
    // Reset
    if ( !reset )
      itrim_rx_reg_config_rx <= 4'h0;
    // SW:read-write
    else if (wen_reg_config_rx)
      itrim_rx_reg_config_rx <= wdata[3:0];
  end


  //------------------------------------------------------------
  // Register: reg_config_bypass_reg
  //   Bypass Configuration Register
  //   SW Access     : read-write
  //   Address Offset: 0x18
  //   HW Access     : read-only
  // 
  // Instance: reg_config_bypass
  //   Bypass Configuration Register
  //   Address Offset: 0x18
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:3  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //     2  bypass_ts_afe (SW:read-write, HW:read-only)
  //     1  bypass_wlm_afe (SW:read-write, HW:read-only)
  //     0  bypass_tia (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 29                  , Offset: 3             
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: bypass_ts_afe                          
  //   Width: 1              , Offset: 2             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Bypass Temp Sensor Analog Front End
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_bypass_reg_bypass_ts_afe_reg_config_bypass
    // Reset
    if ( !reset )
      bypass_ts_afe_reg_config_bypass <= 1'b0;
    // SW:read-write
    else if (wen_reg_config_bypass)
      bypass_ts_afe_reg_config_bypass <= wdata[2];
  end

  //------------------------------------------------------------
  //   Field: bypass_wlm_afe                         
  //   Width: 1              , Offset: 1             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Bypass WLM Analog Front End
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_bypass_reg_bypass_wlm_afe_reg_config_bypass
    // Reset
    if ( !reset )
      bypass_wlm_afe_reg_config_bypass <= 1'b0;
    // SW:read-write
    else if (wen_reg_config_bypass)
      bypass_wlm_afe_reg_config_bypass <= wdata[1];
  end

  //------------------------------------------------------------
  //   Field: bypass_tia                             
  //   Width: 1              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Bypass TIA
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_bypass_reg_bypass_tia_reg_config_bypass
    // Reset
    if ( !reset )
      bypass_tia_reg_config_bypass <= 1'b0;
    // SW:read-write
    else if (wen_reg_config_bypass)
      bypass_tia_reg_config_bypass <= wdata[0];
  end


  //------------------------------------------------------------
  // Register: reg_config_afe_mux_sel_reg
  //   WLM currenet select for amux
  //   SW Access     : read-write
  //   Address Offset: 0x1C
  //   HW Access     : read-only
  // 
  // Instance: reg_config_afe_mux_sel
  //   WLM currenet select for amux
  //   Address Offset: 0x1C
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:6  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //   5:0  afe_mux_sel (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 26                  , Offset: 6             
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: afe_mux_sel                            
  //   Width: 6              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   WLM current select for AMUX
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_afe_mux_sel_reg_afe_mux_sel_reg_config_afe_mux_sel
    // Reset
    if ( !reset )
      afe_mux_sel_reg_config_afe_mux_sel <= 6'b000000;
    // SW:read-write
    else if (wen_reg_config_afe_mux_sel)
      afe_mux_sel_reg_config_afe_mux_sel <= wdata[5:0];
  end


  //------------------------------------------------------------
  // Register: reg_config_amux_reg
  //   AMUX Enable Configuration Register
  //   SW Access     : read-write
  //   Address Offset: 0x20
  //   HW Access     : read-only
  // 
  // Instance: reg_config_amux
  //   AMUX Enable Configuration Register
  //   Address Offset: 0x20
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //   15:0  en_amux_output (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 16                  , Offset: 16            
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: en_amux_output                         
  //   Width: 16             , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Enable amux
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_amux_reg_en_amux_output_reg_config_amux
    // Reset
    if ( !reset )
      en_amux_output_reg_config_amux <= 16'h0000;
    // SW:read-write
    else if (wen_reg_config_amux)
      en_amux_output_reg_config_amux <= wdata[15:0];
  end


  //------------------------------------------------------------
  // Register: reg_config_amux_sel_reg
  //   AMUX Select Configuration Register
  //   SW Access     : read-write
  //   Address Offset: 0x24
  //   HW Access     : read-only
  // 
  // Instance: reg_config_amux_sel
  //   AMUX Select Configuration Register
  //   Address Offset: 0x24
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:12  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //   11:0  alg_amux_sel (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 20                  , Offset: 12            
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: alg_amux_sel                           
  //   Width: 12             , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Enable amux
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_amux_sel_reg_alg_amux_sel_reg_config_amux_sel
    // Reset
    if ( !reset )
      alg_amux_sel_reg_config_amux_sel <= 12'h000;
    // SW:read-write
    else if (wen_reg_config_amux_sel)
      alg_amux_sel_reg_config_amux_sel <= wdata[11:0];
  end


  //------------------------------------------------------------
  // Register: reg_config_dmux_sel_reg
  //   DMUX Select Configuration Register
  //   SW Access     : read-write
  //   Address Offset: 0x28
  //   HW Access     : read-only
  // 
  // Instance: reg_config_dmux_sel
  //   DMUX Select Configuration Register
  //   Address Offset: 0x28
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:24  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //   23:0  alg_dmux_sel (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 8                   , Offset: 24            
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: alg_dmux_sel                           
  //   Width: 24             , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Enable amux
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_config_dmux_sel_reg_alg_dmux_sel_reg_config_dmux_sel
    // Reset
    if ( !reset )
      alg_dmux_sel_reg_config_dmux_sel <= 24'h000000;
    // SW:read-write
    else if (wen_reg_config_dmux_sel)
      alg_dmux_sel_reg_config_dmux_sel <= wdata[23:0];
  end


  //------------------------------------------------------------
  // Register: reg_status_reg
  //   Status Register
  //   SW Access     : read-only
  //   Address Offset: 0x30
  //   HW Access     : write-only
  // 
  // Instance: reg_status
  //   Status Register
  //   Address Offset: 0x30
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:1  reserved (SW:read-only, HW:write-only) (RESERVED) 
  //     0  watchdog_active (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 31                  , Offset: 1              
  //   SW Access: read-only       , HW Access: write-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: watchdog_active                          
  //   Width: 1               , Offset: 0              
  //   SW Access: read-only   , HW Access: write-only  
  //------------------------------------------------------------
  //   Watchdog Active
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_status_reg_watchdog_active_reg_status_local
    // Reset
    if ( !reset )
      watchdog_active_reg_status_local <= 1'b0;
    // HW:write-only
    else
      watchdog_active_reg_status_local <= watchdog_active_reg_status_ip;
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_version[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_version[15:0] = version_reg_version_local;

  assign rmux_reg_config_tx[31:8] = DEF_RDATA_VAL[31:8]; // Default read value for RESERVED field - reserved
  assign rmux_reg_config_tx[7:4] = pd_tx_n_reg_config_tx;
  assign rmux_reg_config_tx[3:0] = itrim_tx_reg_config_tx;

  assign rmux_reg_config_rx[31:13] = DEF_RDATA_VAL[31:13]; // Default read value for RESERVED field - reserved2
  assign rmux_reg_config_rx[12:8] = pd_rx_n_reg_config_rx;
  assign rmux_reg_config_rx[7:4] = DEF_RDATA_VAL[7:4]; // Default read value for RESERVED field - reserved
  assign rmux_reg_config_rx[3:0] = itrim_rx_reg_config_rx;

  assign rmux_reg_config_bypass[31:3] = DEF_RDATA_VAL[31:3]; // Default read value for RESERVED field - reserved
  assign rmux_reg_config_bypass[2] = bypass_ts_afe_reg_config_bypass;
  assign rmux_reg_config_bypass[1] = bypass_wlm_afe_reg_config_bypass;
  assign rmux_reg_config_bypass[0] = bypass_tia_reg_config_bypass;

  assign rmux_reg_config_afe_mux_sel[31:6] = DEF_RDATA_VAL[31:6]; // Default read value for RESERVED field - reserved
  assign rmux_reg_config_afe_mux_sel[5:0] = afe_mux_sel_reg_config_afe_mux_sel;

  assign rmux_reg_config_amux[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_config_amux[15:0] = en_amux_output_reg_config_amux;

  assign rmux_reg_config_amux_sel[31:12] = DEF_RDATA_VAL[31:12]; // Default read value for RESERVED field - reserved
  assign rmux_reg_config_amux_sel[11:0] = alg_amux_sel_reg_config_amux_sel;

  assign rmux_reg_config_dmux_sel[31:24] = DEF_RDATA_VAL[31:24]; // Default read value for RESERVED field - reserved
  assign rmux_reg_config_dmux_sel[23:0] = alg_dmux_sel_reg_config_dmux_sel;

  assign rmux_reg_status[31:1] = DEF_RDATA_VAL[31:1]; // Default read value for RESERVED field - reserved
  assign rmux_reg_status[0] = watchdog_active_reg_status_local;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_VERSION_ADDR:
        begin
          rdata = rmux_reg_version;
        end
        REG_CONFIG_TX_ADDR:
        begin
          rdata = rmux_reg_config_tx;
        end
        REG_CONFIG_RX_ADDR:
        begin
          rdata = rmux_reg_config_rx;
        end
        REG_CONFIG_BYPASS_ADDR:
        begin
          rdata = rmux_reg_config_bypass;
        end
        REG_CONFIG_AFE_MUX_SEL_ADDR:
        begin
          rdata = rmux_reg_config_afe_mux_sel;
        end
        REG_CONFIG_AMUX_ADDR:
        begin
          rdata = rmux_reg_config_amux;
        end
        REG_CONFIG_AMUX_SEL_ADDR:
        begin
          rdata = rmux_reg_config_amux_sel;
        end
        REG_CONFIG_DMUX_SEL_ADDR:
        begin
          rdata = rmux_reg_config_dmux_sel;
        end
        REG_STATUS_ADDR:
        begin
          rdata = rmux_reg_status;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

