//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : arbiter_reg_block
// File            : /home/daniel.lee/cdssen/senUintah/arbiter/reg_gen/output/arbiter_reg_block.v
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 08 08 2021 17:53::22
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : arbiter_reg_block
// Address Range   : 0x24
//----------------------------------------------------------------------

module arbiter_reg_block
#(
  parameter ADDR_WIDTH=6,
  parameter DATA_WIDTH=32
)
(

  // FIELD OUTPUT PORTS
  output reg   [15:0] wdg_cnt_reg_wdg_cnt ,
  output reg   [31:0] def_fld_reg_bus_mask,

  // FIELD INPUT PORTS
  input wire   [15:0] version_reg_version_ip,
  input wire   [7:0]  num_dev_reg_num_dev_ip,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);

  // READ/WRITE ENABLE SIGNALS
  reg  wen_reg_wdg_cnt ;
  reg  wen_reg_bus_mask;

  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_version ;
  wire [DATA_WIDTH-1:0] rmux_reg_wdg_cnt ;
  wire [DATA_WIDTH-1:0] rmux_reg_bus_mask;
  wire [DATA_WIDTH-1:0] rmux_reg_num_dev ;

  // FLIP-FLOP SIGNALS
  reg  [15:0] version_reg_version_local;
  reg  [7:0]  num_dev_reg_num_dev_local;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_VERSION_ADDR = 6'h00;
  localparam REG_WDG_CNT_ADDR = 6'h10;
  localparam REG_BUS_MASK_ADDR = 6'h14;
  localparam REG_NUM_DEV_ADDR = 6'h20;

  //----------------------------------------------------------------------
  //                    WRITE ADDRESS DECODE
  //----------------------------------------------------------------------
  always @ ( * )
  begin : write_enable
    wen_reg_wdg_cnt = 1'b0;
    wen_reg_bus_mask = 1'b0;
    waddrerr = 1'b0;
    wack = 1'b0;

    if (wstrobe)
    begin
      case (waddr)
        REG_WDG_CNT_ADDR:
        begin
          wen_reg_wdg_cnt = 1'b1;
        end
        REG_BUS_MASK_ADDR:
        begin
          wen_reg_bus_mask = 1'b1;
        end
        default:
        begin
          waddrerr = 1'b1;
        end
      endcase
      wack = 1'b1;
    end
  end


  //------------------------------------------------------------
  // Register: reg_version_reg
  //   Arbiter version register
  //   SW Access     : read-write
  //   Address Offset: 0x00
  //   HW Access     : read-write
  // 
  // Instance: reg_version
  //   Arbiter version register
  //   Address Offset: 0x00
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:0  version (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: version                                
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   version number
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_version_reg_version_reg_version_local
    // Reset
    if ( !reset )
      version_reg_version_local <= 16'h0000;
    // HW:write-only
    else
      version_reg_version_local <= version_reg_version_ip;
  end


  //------------------------------------------------------------
  // Register: reg_wdg_cnt_reg
  //   watchdog register
  //   SW Access     : read-write
  //   Address Offset: 0x10
  //   HW Access     : read-only
  // 
  // Instance: reg_wdg_cnt
  //   watchdog register
  //   Address Offset: 0x10
  //   Reset Value   : 0x40
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //   15:0  wdg_cnt (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 16                  , Offset: 16            
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: wdg_cnt                                
  //   Width: 16             , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   watchdog count
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_wdg_cnt_reg_wdg_cnt_reg_wdg_cnt
    // Reset
    if ( !reset )
      wdg_cnt_reg_wdg_cnt <= 16'h0040;
    // SW:read-write
    else if (wen_reg_wdg_cnt)
      wdg_cnt_reg_wdg_cnt <= wdata[15:0];
  end


  //------------------------------------------------------------
  // Register: reg_bus_mask_reg
  //   arbiter mask register
  //   SW Access     : read-write
  //   Address Offset: 0x14
  //   HW Access     : read-only
  // 
  // Instance: reg_bus_mask
  //   arbiter mask register
  //   Address Offset: 0x14
  //   Reset Value   : 0xFFFFFFFF
  // 
  // Fields:
  //   31:0  def_fld (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: def_fld                                
  //   Width: 32             , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Default field for entire register - reg_bus_mask_reg
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_bus_mask_reg_def_fld_reg_bus_mask
    // Reset
    if ( !reset )
      def_fld_reg_bus_mask <= 32'hFFFFFFFF;
    // SW:read-write
    else if (wen_reg_bus_mask)
      def_fld_reg_bus_mask <= wdata;
  end


  //------------------------------------------------------------
  // Register: reg_num_dev_reg
  //   Number of devices
  //   SW Access     : read-write
  //   Address Offset: 0x20
  //   HW Access     : read-write
  // 
  // Instance: reg_num_dev
  //   Number of devices
  //   Address Offset: 0x20
  //   Reset Value   : 
  // 
  // Fields:
  //   31:8  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   7:0  num_dev (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 24                  , Offset: 8              
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: num_dev                                
  //   Width: 8             , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   number of devices
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_num_dev_reg_num_dev_reg_num_dev_local
    // Reset
    if ( !reset )
      num_dev_reg_num_dev_local <= 8'h00;
    // HW:write-only
    else
      num_dev_reg_num_dev_local <= num_dev_reg_num_dev_ip;
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_version[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_version[15:0] = version_reg_version_local;

  assign rmux_reg_wdg_cnt[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_wdg_cnt[15:0] = wdg_cnt_reg_wdg_cnt;

  assign rmux_reg_bus_mask = def_fld_reg_bus_mask;

  assign rmux_reg_num_dev[31:8] = DEF_RDATA_VAL[31:8]; // Default read value for RESERVED field - reserved
  assign rmux_reg_num_dev[7:0] = num_dev_reg_num_dev_local;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_VERSION_ADDR:
        begin
          rdata = rmux_reg_version;
        end
        REG_WDG_CNT_ADDR:
        begin
          rdata = rmux_reg_wdg_cnt;
        end
        REG_BUS_MASK_ADDR:
        begin
          rdata = rmux_reg_bus_mask;
        end
        REG_NUM_DEV_ADDR:
        begin
          rdata = rmux_reg_num_dev;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

