//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : arbiter_reg_block
// Unit            : arbiter_reg_block_pkg_uvm
// File            : arbiter_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 8/8/21 5:53 PM
//----------------------------------------------------------------------
// Title           : arbiter_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// arbiter_reg_block_pkg_uvm
//----------------------------------------------------------------------
package arbiter_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: reg_bus_mask_reg
   // 
   // arbiter mask register
   //--------------------------------------------------------------------

   class reg_bus_mask_reg extends uvm_reg;
      `uvm_object_utils(reg_bus_mask_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_bus_mask_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'hffffffff, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_num_dev_reg
   // 
   // Number of devices
   //--------------------------------------------------------------------

   class reg_num_dev_reg extends uvm_reg;
      `uvm_object_utils(reg_num_dev_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field num_dev; // number of devices


      // Function: coverage
      // 
      covergroup cg_vals;
         num_dev	 : coverpoint num_dev.value[7:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_num_dev_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         num_dev = uvm_reg_field::type_id::create("num_dev");

         reserved.configure(this, 24, 8, "RW", 0, 24'h000000, 1, 0, 1);
         num_dev.configure(this, 8, 0, "RO", 0, 8'h00, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_version_reg
   // 
   // Arbiter version register
   //--------------------------------------------------------------------

   class reg_version_reg extends uvm_reg;
      `uvm_object_utils(reg_version_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field version; // version number


      // Function: coverage
      // 
      covergroup cg_vals;
         version	 : coverpoint version.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_version_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         version = uvm_reg_field::type_id::create("version");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         version.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_wdg_cnt_reg
   // 
   // watchdog register
   //--------------------------------------------------------------------

   class reg_wdg_cnt_reg extends uvm_reg;
      `uvm_object_utils(reg_wdg_cnt_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field wdg_cnt; // watchdog count


      // Function: coverage
      // 
      covergroup cg_vals;
         wdg_cnt	 : coverpoint wdg_cnt.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_wdg_cnt_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         wdg_cnt = uvm_reg_field::type_id::create("wdg_cnt");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         wdg_cnt.configure(this, 16, 0, "RW", 0, 16'h0040, 1, 1, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: arbiter_reg_block
   // 
   //--------------------------------------------------------------------

   class arbiter_reg_block extends uvm_reg_block;
      `uvm_object_utils(arbiter_reg_block)

      rand reg_version_reg reg_version; // Arbiter version register
      rand reg_wdg_cnt_reg reg_wdg_cnt; // watchdog register
      rand reg_bus_mask_reg reg_bus_mask; // arbiter mask register
      rand reg_num_dev_reg reg_num_dev; // Number of devices

      uvm_reg_map arbiter_reg_block_map; 


      // Function: new
      // 
      function new(string name = "arbiter_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_version = reg_version_reg::type_id::create("reg_version");
         reg_version.configure(this);
         reg_version.build();

         reg_wdg_cnt = reg_wdg_cnt_reg::type_id::create("reg_wdg_cnt");
         reg_wdg_cnt.configure(this);
         reg_wdg_cnt.build();

         reg_bus_mask = reg_bus_mask_reg::type_id::create("reg_bus_mask");
         reg_bus_mask.configure(this);
         reg_bus_mask.build();

         reg_num_dev = reg_num_dev_reg::type_id::create("reg_num_dev");
         reg_num_dev.configure(this);
         reg_num_dev.build();

         arbiter_reg_block_map = create_map("arbiter_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = arbiter_reg_block_map;

         arbiter_reg_block_map.add_reg(reg_version, 'h0, "RW");
         arbiter_reg_block_map.add_reg(reg_wdg_cnt, 'h10, "RW");
         arbiter_reg_block_map.add_reg(reg_bus_mask, 'h14, "RW");
         arbiter_reg_block_map.add_reg(reg_num_dev, 'h20, "RW");

         lock_model();
      endfunction
   endclass


endpackage
