//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : fifo_reg_block
// File            : /home/chaitra.rangaswamaia/cdssen/senUintah/fifo/reg_gen/output/fifo_reg_block.v
//----------------------------------------------------------------------
// Created by      : chaitra.rangaswamaia
// Creation Date   : 30 08 2021 10:47::46
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : fifo_reg_block
// Address Range   : 0x30
//----------------------------------------------------------------------

module fifo_reg_block
#(
  parameter ADDR_WIDTH=6,
  parameter DATA_WIDTH=32
)
(

  // FIELD OUTPUT PORTS
  output reg          clear_err_addr_reg_fifo_clear   ,
  output reg          clear_reg_fifo_clear            ,
  output reg          capture_reg_fifo_capture        ,
  output reg          resync_reg_fifo_resync          ,
  output reg   [13:0] fifo_thresh_reg_fifo_thresh     ,
  output reg          read_en_reg_fifo_read_init      ,
  output reg          parity_odd_not_even_reg_fifo_cfg,

  // FIELD INPUT PORTS
  input wire   [15:0] version_reg_fifo_version_ip        ,
  input wire   [14:0] fifo_level_reg_fifo_level_ip       ,
  input wire   [14:0] err_addr_reg_fifo_status_ip        ,
  input wire          fifo_full_reg_fifo_status_ip       ,
  input wire          fifo_empty_reg_fifo_status_ip      ,
  input wire   [31:0] ingress_cnt_reg_fifo_ingress_cnt_ip,
  input wire   [31:0] egress_cnt_reg_fifo_egress_cnt_ip  ,
  input wire   [31:0] def_fld_reg_fifo_read_data_ip      ,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);

  // READ/WRITE ENABLE SIGNALS
  reg  wen_reg_fifo_clear    ;
  reg  wen_reg_fifo_capture  ;
  reg  wen_reg_fifo_resync   ;
  reg  wen_reg_fifo_thresh   ;
  reg  wen_reg_fifo_read_init;
  reg  wen_reg_fifo_cfg      ;

  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_version    ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_clear      ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_capture    ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_resync     ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_thresh     ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_level      ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_status     ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_ingress_cnt;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_egress_cnt ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_read_init  ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_read_data  ;
  wire [DATA_WIDTH-1:0] rmux_reg_fifo_cfg        ;

  // FLIP-FLOP SIGNALS
  reg  [15:0] version_reg_fifo_version_local        ;
  reg  [14:0] fifo_level_reg_fifo_level_local       ;
  reg  [14:0] err_addr_reg_fifo_status_local        ;
  reg         fifo_full_reg_fifo_status_local       ;
  reg         fifo_empty_reg_fifo_status_local      ;
  reg  [31:0] ingress_cnt_reg_fifo_ingress_cnt_local;
  reg  [31:0] egress_cnt_reg_fifo_egress_cnt_local  ;
  reg  [31:0] def_fld_reg_fifo_read_data_local      ;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_FIFO_VERSION_ADDR = 6'h00;
  localparam REG_FIFO_CLEAR_ADDR = 6'h04;
  localparam REG_FIFO_CAPTURE_ADDR = 6'h08;
  localparam REG_FIFO_RESYNC_ADDR = 6'h0C;
  localparam REG_FIFO_THRESH_ADDR = 6'h10;
  localparam REG_FIFO_LEVEL_ADDR = 6'h14;
  localparam REG_FIFO_STATUS_ADDR = 6'h18;
  localparam REG_FIFO_INGRESS_CNT_ADDR = 6'h1C;
  localparam REG_FIFO_EGRESS_CNT_ADDR = 6'h20;
  localparam REG_FIFO_READ_INIT_ADDR = 6'h24;
  localparam REG_FIFO_READ_DATA_ADDR = 6'h28;
  localparam REG_FIFO_CFG_ADDR = 6'h2C;

  //----------------------------------------------------------------------
  //                    WRITE ADDRESS DECODE
  //----------------------------------------------------------------------
  always @ ( * )
  begin : write_enable
    wen_reg_fifo_clear = 1'b0;
    wen_reg_fifo_capture = 1'b0;
    wen_reg_fifo_resync = 1'b0;
    wen_reg_fifo_thresh = 1'b0;
    wen_reg_fifo_read_init = 1'b0;
    wen_reg_fifo_cfg = 1'b0;
    waddrerr = 1'b0;
    wack = 1'b0;

    if (wstrobe)
    begin
      case (waddr)
        REG_FIFO_CLEAR_ADDR:
        begin
          wen_reg_fifo_clear = 1'b1;
        end
        REG_FIFO_CAPTURE_ADDR:
        begin
          wen_reg_fifo_capture = 1'b1;
        end
        REG_FIFO_RESYNC_ADDR:
        begin
          wen_reg_fifo_resync = 1'b1;
        end
        REG_FIFO_THRESH_ADDR:
        begin
          wen_reg_fifo_thresh = 1'b1;
        end
        REG_FIFO_READ_INIT_ADDR:
        begin
          wen_reg_fifo_read_init = 1'b1;
        end
        REG_FIFO_CFG_ADDR:
        begin
          wen_reg_fifo_cfg = 1'b1;
        end
        default:
        begin
          waddrerr = 1'b1;
        end
      endcase
      wack = 1'b1;
    end
  end


  //------------------------------------------------------------
  // Register: reg_fifo_version_reg
  //   fifo version register
  //   SW Access     : read-write
  //   Address Offset: 0x00
  //   HW Access     : read-write
  // 
  // Instance: reg_fifo_version
  //   fifo version register
  //   Address Offset: 0x00
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:0  version (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: version                                
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   version number
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_version_reg_version_reg_fifo_version_local
    // Reset
    if ( !reset )
      version_reg_fifo_version_local <= 16'h0000;
    // HW:write-only
    else
      version_reg_fifo_version_local <= version_reg_fifo_version_ip;
  end


  //------------------------------------------------------------
  // Register: reg_fifo_clear_reg
  //   fifo clear register
  //   SW Access     : read-write
  //   Address Offset: 0x04
  //   HW Access     : read-write
  // 
  // Instance: reg_fifo_clear
  //   fifo clear register
  //   Address Offset: 0x04
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:2  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //     1  clear_err_addr (SW:write-only, HW:read-only)
  //     0  clear (SW:write-only, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 30                  , Offset: 2              
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: clear_err_addr                         
  //   Width: 1              , Offset: 1             
  //   SW Access: write-only , HW Access: read-only  
  //------------------------------------------------------------
  //   write 1 to clear error address (reset error address to 0, self-clear)
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_clear_reg_clear_err_addr_reg_fifo_clear
    // Reset
    if ( !reset )
      clear_err_addr_reg_fifo_clear <= 1'b0;
    // Soft Reset
    else if (!wstrobe)
      clear_err_addr_reg_fifo_clear <= 0; // self clear
    // SW:write-only
    else if (wen_reg_fifo_clear)
      clear_err_addr_reg_fifo_clear <= wdata[1];
  end

  //------------------------------------------------------------
  //   Field: clear                                  
  //   Width: 1              , Offset: 0             
  //   SW Access: write-only , HW Access: read-only  
  //------------------------------------------------------------
  //   clear
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_clear_reg_clear_reg_fifo_clear
    // Reset
    if ( !reset )
      clear_reg_fifo_clear <= 1'b0;
    // Soft Reset
    else if (!wstrobe)
      clear_reg_fifo_clear <= 0; // self clear
    // SW:write-only
    else if (wen_reg_fifo_clear)
      clear_reg_fifo_clear <= wdata[0];
  end


  //------------------------------------------------------------
  // Register: reg_fifo_capture_reg
  //   fifo capture register
  //   SW Access     : read-write
  //   Address Offset: 0x08
  //   HW Access     : read-write
  // 
  // Instance: reg_fifo_capture
  //   fifo capture register
  //   Address Offset: 0x08
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:1  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //     0  capture (SW:write-only, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 31                  , Offset: 1              
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: capture                                
  //   Width: 1              , Offset: 0             
  //   SW Access: write-only , HW Access: read-only  
  //------------------------------------------------------------
  //   capture
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_capture_reg_capture_reg_fifo_capture
    // Reset
    if ( !reset )
      capture_reg_fifo_capture <= 1'b0;
    // Soft Reset
    else if (!wstrobe)
      capture_reg_fifo_capture <= 0; // self clear
    // SW:write-only
    else if (wen_reg_fifo_capture)
      capture_reg_fifo_capture <= wdata[0];
  end


  //------------------------------------------------------------
  // Register: reg_fifo_resync_reg
  //   fifo resync register
  //   SW Access     : read-write
  //   Address Offset: 0x0C
  //   HW Access     : read-write
  // 
  // Instance: reg_fifo_resync
  //   fifo resync register
  //   Address Offset: 0x0C
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:1  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //     0  resync (SW:write-only, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 31                  , Offset: 1              
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: resync                                 
  //   Width: 1              , Offset: 0             
  //   SW Access: write-only , HW Access: read-only  
  //------------------------------------------------------------
  //   resync
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_resync_reg_resync_reg_fifo_resync
    // Reset
    if ( !reset )
      resync_reg_fifo_resync <= 1'b0;
    // Soft Reset
    else if (!wstrobe)
      resync_reg_fifo_resync <= 0; // self clear
    // SW:write-only
    else if (wen_reg_fifo_resync)
      resync_reg_fifo_resync <= wdata[0];
  end


  //------------------------------------------------------------
  // Register: reg_fifo_thresh_reg
  //   fifo programmable threshold register
  //   SW Access     : read-write
  //   Address Offset: 0x10
  //   HW Access     : read-only
  // 
  // Instance: reg_fifo_thresh
  //   fifo programmable threshold register
  //   Address Offset: 0x10
  //   Reset Value   : 
  // 
  // Fields:
  //   31:14  reserved (SW:read-write, HW:read-only) (RESERVED) 
  //   13:0  fifo_thresh (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                         
  //   Width: 18                  , Offset: 14            
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: fifo_thresh                            
  //   Width: 14             , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   fifo threshold
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_thresh_reg_fifo_thresh_reg_fifo_thresh
    // Reset
    if ( !reset )
      fifo_thresh_reg_fifo_thresh <= 14'h2000;
    // SW:read-write
    else if (wen_reg_fifo_thresh)
      fifo_thresh_reg_fifo_thresh <= wdata[13:0];
  end


  //------------------------------------------------------------
  // Register: reg_fifo_level_reg
  //   fifo level register
  //   SW Access     : read-only
  //   Address Offset: 0x14
  //   HW Access     : write-only
  // 
  // Instance: reg_fifo_level
  //   fifo level register
  //   Address Offset: 0x14
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:15  reserved (SW:read-only, HW:write-only) (RESERVED) 
  //   14:0  fifo_level (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 17                  , Offset: 15             
  //   SW Access: read-only       , HW Access: write-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: fifo_level                             
  //   Width: 15            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   fifo level
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_level_reg_fifo_level_reg_fifo_level_local
    // Reset
    if ( !reset )
      fifo_level_reg_fifo_level_local <= 15'b000000000000000;
    // HW:write-only
    else
      fifo_level_reg_fifo_level_local <= fifo_level_reg_fifo_level_ip;
  end


  //------------------------------------------------------------
  // Register: reg_fifo_status_reg
  //   fifo status register
  //   SW Access     : read-write
  //   Address Offset: 0x18
  //   HW Access     : read-write
  // 
  // Instance: reg_fifo_status
  //   fifo status register
  //   Address Offset: 0x18
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:17  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   16:2  err_addr (SW:read-only, HW:write-only)
  //     1  fifo_full (SW:read-only, HW:write-only)
  //     0  fifo_empty (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 15                  , Offset: 17             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: err_addr                               
  //   Width: 15            , Offset: 2              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   err_addr (can be cleared with clear_err_addr)
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_status_reg_err_addr_reg_fifo_status_local
    // Reset
    if ( !reset )
      err_addr_reg_fifo_status_local <= 15'b000000000000000;
    // HW:write-only
    else
      err_addr_reg_fifo_status_local <= err_addr_reg_fifo_status_ip;
  end

  //------------------------------------------------------------
  //   Field: fifo_full                              
  //   Width: 1             , Offset: 1              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   fifo full
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_status_reg_fifo_full_reg_fifo_status_local
    // Reset
    if ( !reset )
      fifo_full_reg_fifo_status_local <= 1'b0;
    // HW:write-only
    else
      fifo_full_reg_fifo_status_local <= fifo_full_reg_fifo_status_ip;
  end

  //------------------------------------------------------------
  //   Field: fifo_empty                             
  //   Width: 1             , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   fifo empty
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_status_reg_fifo_empty_reg_fifo_status_local
    // Reset
    if ( !reset )
      fifo_empty_reg_fifo_status_local <= 1'b0;
    // HW:write-only
    else
      fifo_empty_reg_fifo_status_local <= fifo_empty_reg_fifo_status_ip;
  end


  //------------------------------------------------------------
  // Register: reg_fifo_ingress_cnt_reg
  //   fifo ingress counter register
  //   SW Access     : read-only
  //   Address Offset: 0x1C
  //   HW Access     : write-only
  // 
  // Instance: reg_fifo_ingress_cnt
  //   fifo ingress counter register
  //   Address Offset: 0x1C
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:0  ingress_cnt (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: ingress_cnt                            
  //   Width: 32            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   ingress counter
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_ingress_cnt_reg_ingress_cnt_reg_fifo_ingress_cnt_local
    // Reset
    if ( !reset )
      ingress_cnt_reg_fifo_ingress_cnt_local <= 32'h00000000;
    // HW:write-only
    else
      ingress_cnt_reg_fifo_ingress_cnt_local <= ingress_cnt_reg_fifo_ingress_cnt_ip;
  end


  //------------------------------------------------------------
  // Register: reg_fifo_egress_cnt_reg
  //   fifo egress counter register
  //   SW Access     : read-only
  //   Address Offset: 0x20
  //   HW Access     : write-only
  // 
  // Instance: reg_fifo_egress_cnt
  //   fifo egress counter register
  //   Address Offset: 0x20
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:0  egress_cnt (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: egress_cnt                             
  //   Width: 32            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   egress counter
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_egress_cnt_reg_egress_cnt_reg_fifo_egress_cnt_local
    // Reset
    if ( !reset )
      egress_cnt_reg_fifo_egress_cnt_local <= 32'h00000000;
    // HW:write-only
    else
      egress_cnt_reg_fifo_egress_cnt_local <= egress_cnt_reg_fifo_egress_cnt_ip;
  end


  //------------------------------------------------------------
  // Register: reg_fifo_read_init_reg
  //   fifo read enable register
  //   SW Access     : read-write
  //   Address Offset: 0x24
  //   HW Access     : read-write
  // 
  // Instance: reg_fifo_read_init
  //   fifo read enable register
  //   Address Offset: 0x24
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:1  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //     0  read_en (SW:write-only, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 31                  , Offset: 1              
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: read_en                                
  //   Width: 1              , Offset: 0             
  //   SW Access: write-only , HW Access: read-only  
  //------------------------------------------------------------
  //   read enable
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_read_init_reg_read_en_reg_fifo_read_init
    // Reset
    if ( !reset )
      read_en_reg_fifo_read_init <= 1'b0;
    // Soft Reset
    else if (!wstrobe)
      read_en_reg_fifo_read_init <= 0; // self clear
    // SW:write-only
    else if (wen_reg_fifo_read_init)
      read_en_reg_fifo_read_init <= wdata[0];
  end


  //------------------------------------------------------------
  // Register: reg_fifo_read_data_reg
  //   fifo read data
  //   SW Access     : read-only
  //   Address Offset: 0x28
  //   HW Access     : write-only
  // 
  // Instance: reg_fifo_read_data
  //   fifo read data
  //   Address Offset: 0x28
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:0  def_fld (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: def_fld                                
  //   Width: 32            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   Default field for entire register - reg_fifo_read_data_reg
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_read_data_reg_def_fld_reg_fifo_read_data_local
    // Reset
    if ( !reset )
      def_fld_reg_fifo_read_data_local <= 32'h00000000;
    // HW:write-only
    else
      def_fld_reg_fifo_read_data_local <= def_fld_reg_fifo_read_data_ip;
  end


  //------------------------------------------------------------
  // Register: reg_fifo_cfg_reg
  //   fifo configuration register
  //   SW Access     : read-write
  //   Address Offset: 0x2C
  //   HW Access     : read-write
  // 
  // Instance: reg_fifo_cfg
  //   fifo configuration register
  //   Address Offset: 0x2C
  //   Reset Value   : 
  // 
  // Fields:
  //   31:1  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //     0  parity_odd_not_even (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 31                  , Offset: 1              
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: parity_odd_not_even                         
  //   Width: 1                   , Offset: 0             
  //   SW Access: read-write      , HW Access: read-only  
  //------------------------------------------------------------
  //   parity bit odd 1, even 0
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_fifo_cfg_reg_parity_odd_not_even_reg_fifo_cfg
    // Reset
    if ( !reset )
      parity_odd_not_even_reg_fifo_cfg <= 1'b0;
    // SW:read-write
    else if (wen_reg_fifo_cfg)
      parity_odd_not_even_reg_fifo_cfg <= wdata[0];
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_fifo_version[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_version[15:0] = version_reg_fifo_version_local;

  assign rmux_reg_fifo_clear[31:2] = DEF_RDATA_VAL[31:2]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_clear[1] = DEF_RDATA_VAL[1]; // Default read value for write-only field - clear_err_addr
  assign rmux_reg_fifo_clear[0] = DEF_RDATA_VAL[0]; // Default read value for write-only field - clear

  assign rmux_reg_fifo_capture[31:1] = DEF_RDATA_VAL[31:1]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_capture[0] = DEF_RDATA_VAL[0]; // Default read value for write-only field - capture

  assign rmux_reg_fifo_resync[31:1] = DEF_RDATA_VAL[31:1]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_resync[0] = DEF_RDATA_VAL[0]; // Default read value for write-only field - resync

  assign rmux_reg_fifo_thresh[31:14] = DEF_RDATA_VAL[31:14]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_thresh[13:0] = fifo_thresh_reg_fifo_thresh;

  assign rmux_reg_fifo_level[31:15] = DEF_RDATA_VAL[31:15]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_level[14:0] = fifo_level_reg_fifo_level_local;

  assign rmux_reg_fifo_status[31:17] = DEF_RDATA_VAL[31:17]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_status[16:2] = err_addr_reg_fifo_status_local;
  assign rmux_reg_fifo_status[1] = fifo_full_reg_fifo_status_local;
  assign rmux_reg_fifo_status[0] = fifo_empty_reg_fifo_status_local;

  assign rmux_reg_fifo_ingress_cnt = ingress_cnt_reg_fifo_ingress_cnt_local;

  assign rmux_reg_fifo_egress_cnt = egress_cnt_reg_fifo_egress_cnt_local;

  assign rmux_reg_fifo_read_init[31:1] = DEF_RDATA_VAL[31:1]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_read_init[0] = DEF_RDATA_VAL[0]; // Default read value for write-only field - read_en

  assign rmux_reg_fifo_read_data = def_fld_reg_fifo_read_data_local;

  assign rmux_reg_fifo_cfg[31:1] = DEF_RDATA_VAL[31:1]; // Default read value for RESERVED field - reserved
  assign rmux_reg_fifo_cfg[0] = parity_odd_not_even_reg_fifo_cfg;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_FIFO_VERSION_ADDR:
        begin
          rdata = rmux_reg_fifo_version;
        end
        REG_FIFO_CLEAR_ADDR:
        begin
          rdata = rmux_reg_fifo_clear;
        end
        REG_FIFO_CAPTURE_ADDR:
        begin
          rdata = rmux_reg_fifo_capture;
        end
        REG_FIFO_RESYNC_ADDR:
        begin
          rdata = rmux_reg_fifo_resync;
        end
        REG_FIFO_THRESH_ADDR:
        begin
          rdata = rmux_reg_fifo_thresh;
        end
        REG_FIFO_LEVEL_ADDR:
        begin
          rdata = rmux_reg_fifo_level;
        end
        REG_FIFO_STATUS_ADDR:
        begin
          rdata = rmux_reg_fifo_status;
        end
        REG_FIFO_INGRESS_CNT_ADDR:
        begin
          rdata = rmux_reg_fifo_ingress_cnt;
        end
        REG_FIFO_EGRESS_CNT_ADDR:
        begin
          rdata = rmux_reg_fifo_egress_cnt;
        end
        REG_FIFO_READ_INIT_ADDR:
        begin
          rdata = rmux_reg_fifo_read_init;
        end
        REG_FIFO_READ_DATA_ADDR:
        begin
          rdata = rmux_reg_fifo_read_data;
        end
        REG_FIFO_CFG_ADDR:
        begin
          rdata = rmux_reg_fifo_cfg;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

