//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : fifo_reg_block
// Unit            : fifo_reg_block_pkg_uvm
// File            : fifo_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : chaitra.rangaswamaia
// Creation Date   : 8/30/21 10:47 AM
//----------------------------------------------------------------------
// Title           : fifo_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// fifo_reg_block_pkg_uvm
//----------------------------------------------------------------------
package fifo_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: reg_fifo_capture_reg
   // 
   // fifo capture register
   //--------------------------------------------------------------------

   class reg_fifo_capture_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_capture_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field capture; // capture


      // Function: coverage
      // 
      covergroup cg_vals;
         capture	 : coverpoint capture.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_fifo_capture_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         capture = uvm_reg_field::type_id::create("capture");

         reserved.configure(this, 31, 1, "RW", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         capture.configure(this, 1, 0, "WO", 1, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_cfg_reg
   // 
   // fifo configuration register
   //--------------------------------------------------------------------

   class reg_fifo_cfg_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_cfg_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field parity_odd_not_even; // parity bit odd 1, even 0


      // Function: new
      // 
      function new(string name = "reg_fifo_cfg_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         parity_odd_not_even = uvm_reg_field::type_id::create("parity_odd_not_even");

         reserved.configure(this, 31, 1, "RW", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         parity_odd_not_even.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_clear_reg
   // 
   // fifo clear register
   //--------------------------------------------------------------------

   class reg_fifo_clear_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_clear_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field clear_err_addr; // write 1 to clear error address (reset error address to 0, self-clear)
      rand uvm_reg_field clear; // clear


      // Function: coverage
      // 
      covergroup cg_vals;
         clear_err_addr	 : coverpoint clear_err_addr.value[0];
         clear	 : coverpoint clear.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_fifo_clear_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         clear_err_addr = uvm_reg_field::type_id::create("clear_err_addr");
         clear = uvm_reg_field::type_id::create("clear");

         reserved.configure(this, 30, 2, "RW", 0, 30'b000000000000000000000000000000, 1, 0, 0);
         clear_err_addr.configure(this, 1, 1, "WO", 1, 1'b0, 1, 1, 0);
         clear.configure(this, 1, 0, "WO", 1, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_egress_cnt_reg
   // 
   // fifo egress counter register
   //--------------------------------------------------------------------

   class reg_fifo_egress_cnt_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_egress_cnt_reg)

      uvm_reg_field egress_cnt; // egress counter


      // Function: new
      // 
      function new(string name = "reg_fifo_egress_cnt_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         egress_cnt = uvm_reg_field::type_id::create("egress_cnt");

         egress_cnt.configure(this, 32, 0, "RO", 1, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_ingress_cnt_reg
   // 
   // fifo ingress counter register
   //--------------------------------------------------------------------

   class reg_fifo_ingress_cnt_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_ingress_cnt_reg)

      uvm_reg_field ingress_cnt; // ingress counter


      // Function: new
      // 
      function new(string name = "reg_fifo_ingress_cnt_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         ingress_cnt = uvm_reg_field::type_id::create("ingress_cnt");

         ingress_cnt.configure(this, 32, 0, "RO", 1, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_level_reg
   // 
   // fifo level register
   //--------------------------------------------------------------------

   class reg_fifo_level_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_level_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field fifo_level; // fifo level


      // Function: new
      // 
      function new(string name = "reg_fifo_level_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         fifo_level = uvm_reg_field::type_id::create("fifo_level");

         reserved.configure(this, 17, 15, "RO", 0, 17'b00000000000000000, 1, 0, 0);
         fifo_level.configure(this, 15, 0, "RO", 1, 15'b000000000000000, 1, 0, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_read_data_reg
   // 
   // fifo read data
   //--------------------------------------------------------------------

   class reg_fifo_read_data_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_read_data_reg)

      uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_fifo_read_data_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RO", 1, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_read_init_reg
   // 
   // fifo read enable register
   //--------------------------------------------------------------------

   class reg_fifo_read_init_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_read_init_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field read_en; // read enable


      // Function: coverage
      // 
      covergroup cg_vals;
         read_en	 : coverpoint read_en.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_fifo_read_init_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         read_en = uvm_reg_field::type_id::create("read_en");

         reserved.configure(this, 31, 1, "RW", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         read_en.configure(this, 1, 0, "WO", 1, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_resync_reg
   // 
   // fifo resync register
   //--------------------------------------------------------------------

   class reg_fifo_resync_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_resync_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field resync; // resync


      // Function: coverage
      // 
      covergroup cg_vals;
         resync	 : coverpoint resync.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_fifo_resync_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         resync = uvm_reg_field::type_id::create("resync");

         reserved.configure(this, 31, 1, "RW", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         resync.configure(this, 1, 0, "WO", 1, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_status_reg
   // 
   // fifo status register
   //--------------------------------------------------------------------

   class reg_fifo_status_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_status_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field err_addr; // err_addr (can be cleared with clear_err_addr)
      uvm_reg_field fifo_full; // fifo full
      uvm_reg_field fifo_empty; // fifo empty


      // Function: coverage
      // 
      covergroup cg_vals;
         err_addr	 : coverpoint err_addr.value[14:0];
         fifo_full	 : coverpoint fifo_full.value[0];
         fifo_empty	 : coverpoint fifo_empty.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_fifo_status_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         err_addr = uvm_reg_field::type_id::create("err_addr");
         fifo_full = uvm_reg_field::type_id::create("fifo_full");
         fifo_empty = uvm_reg_field::type_id::create("fifo_empty");

         reserved.configure(this, 15, 17, "RW", 0, 15'b000000000000000, 1, 0, 0);
         err_addr.configure(this, 15, 2, "RO", 1, 15'b000000000000000, 1, 0, 0);
         fifo_full.configure(this, 1, 1, "RO", 0, 1'b0, 1, 0, 0);
         fifo_empty.configure(this, 1, 0, "RO", 0, 1'b0, 1, 0, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_thresh_reg
   // 
   // fifo programmable threshold register
   //--------------------------------------------------------------------

   class reg_fifo_thresh_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_thresh_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field fifo_thresh; // fifo threshold


      // Function: coverage
      // 
      covergroup cg_vals;
         fifo_thresh	 : coverpoint fifo_thresh.value[13:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_fifo_thresh_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         fifo_thresh = uvm_reg_field::type_id::create("fifo_thresh");

         reserved.configure(this, 18, 14, "RW", 0, 18'b000000000000000000, 1, 0, 0);
         fifo_thresh.configure(this, 14, 0, "RW", 1, 14'b10000000000000, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_fifo_version_reg
   // 
   // fifo version register
   //--------------------------------------------------------------------

   class reg_fifo_version_reg extends uvm_reg;
      `uvm_object_utils(reg_fifo_version_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field version; // version number


      // Function: coverage
      // 
      covergroup cg_vals;
         version	 : coverpoint version.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_fifo_version_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         version = uvm_reg_field::type_id::create("version");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         version.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: fifo_reg_block
   // 
   //--------------------------------------------------------------------

   class fifo_reg_block extends uvm_reg_block;
      `uvm_object_utils(fifo_reg_block)

      rand reg_fifo_version_reg reg_fifo_version; // fifo version register
      rand reg_fifo_clear_reg reg_fifo_clear; // fifo clear register
      rand reg_fifo_capture_reg reg_fifo_capture; // fifo capture register
      rand reg_fifo_resync_reg reg_fifo_resync; // fifo resync register
      rand reg_fifo_thresh_reg reg_fifo_thresh; // fifo programmable threshold register
      rand reg_fifo_level_reg reg_fifo_level; // fifo level register
      rand reg_fifo_status_reg reg_fifo_status; // fifo status register
      rand reg_fifo_ingress_cnt_reg reg_fifo_ingress_cnt; // fifo ingress counter register
      rand reg_fifo_egress_cnt_reg reg_fifo_egress_cnt; // fifo egress counter register
      rand reg_fifo_read_init_reg reg_fifo_read_init; // fifo read enable register
      rand reg_fifo_read_data_reg reg_fifo_read_data; // fifo read data
      rand reg_fifo_cfg_reg reg_fifo_cfg; // fifo configuration register

      uvm_reg_map fifo_reg_block_map; 


      // Function: new
      // 
      function new(string name = "fifo_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_fifo_version = reg_fifo_version_reg::type_id::create("reg_fifo_version");
         reg_fifo_version.configure(this);
         reg_fifo_version.build();

         reg_fifo_clear = reg_fifo_clear_reg::type_id::create("reg_fifo_clear");
         reg_fifo_clear.configure(this);
         reg_fifo_clear.build();

         reg_fifo_capture = reg_fifo_capture_reg::type_id::create("reg_fifo_capture");
         reg_fifo_capture.configure(this);
         reg_fifo_capture.build();

         reg_fifo_resync = reg_fifo_resync_reg::type_id::create("reg_fifo_resync");
         reg_fifo_resync.configure(this);
         reg_fifo_resync.build();

         reg_fifo_thresh = reg_fifo_thresh_reg::type_id::create("reg_fifo_thresh");
         reg_fifo_thresh.configure(this);
         reg_fifo_thresh.build();

         reg_fifo_level = reg_fifo_level_reg::type_id::create("reg_fifo_level");
         reg_fifo_level.configure(this);
         reg_fifo_level.build();

         reg_fifo_status = reg_fifo_status_reg::type_id::create("reg_fifo_status");
         reg_fifo_status.configure(this);
         reg_fifo_status.build();

         reg_fifo_ingress_cnt = reg_fifo_ingress_cnt_reg::type_id::create("reg_fifo_ingress_cnt");
         reg_fifo_ingress_cnt.configure(this);
         reg_fifo_ingress_cnt.build();

         reg_fifo_egress_cnt = reg_fifo_egress_cnt_reg::type_id::create("reg_fifo_egress_cnt");
         reg_fifo_egress_cnt.configure(this);
         reg_fifo_egress_cnt.build();

         reg_fifo_read_init = reg_fifo_read_init_reg::type_id::create("reg_fifo_read_init");
         reg_fifo_read_init.configure(this);
         reg_fifo_read_init.build();

         reg_fifo_read_data = reg_fifo_read_data_reg::type_id::create("reg_fifo_read_data");
         reg_fifo_read_data.configure(this);
         reg_fifo_read_data.build();

         reg_fifo_cfg = reg_fifo_cfg_reg::type_id::create("reg_fifo_cfg");
         reg_fifo_cfg.configure(this);
         reg_fifo_cfg.build();

         fifo_reg_block_map = create_map("fifo_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = fifo_reg_block_map;

         fifo_reg_block_map.add_reg(reg_fifo_version, 'h0, "RW");
         fifo_reg_block_map.add_reg(reg_fifo_clear, 'h4, "RW");
         fifo_reg_block_map.add_reg(reg_fifo_capture, 'h8, "RW");
         fifo_reg_block_map.add_reg(reg_fifo_resync, 'hc, "RW");
         fifo_reg_block_map.add_reg(reg_fifo_thresh, 'h10, "RW");
         fifo_reg_block_map.add_reg(reg_fifo_level, 'h14, "RO");
         fifo_reg_block_map.add_reg(reg_fifo_status, 'h18, "RW");
         fifo_reg_block_map.add_reg(reg_fifo_ingress_cnt, 'h1c, "RO");
         fifo_reg_block_map.add_reg(reg_fifo_egress_cnt, 'h20, "RO");
         fifo_reg_block_map.add_reg(reg_fifo_read_init, 'h24, "RW");
         fifo_reg_block_map.add_reg(reg_fifo_read_data, 'h28, "RO");
         fifo_reg_block_map.add_reg(reg_fifo_cfg, 'h2c, "RW");

         lock_model();
      endfunction
   endclass


endpackage
