//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : interrupt_gen_reg_block
// File            : /home/daniel.lee/cdssen/senUintah/interrupt_gen/reg_gen/output/interrupt_gen_reg_block.v
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 09 08 2021 19:08::09
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : interrupt_gen_reg_block
// Address Range   : 0x14
//----------------------------------------------------------------------

module interrupt_gen_reg_block
#(
  parameter ADDR_WIDTH=5,
  parameter DATA_WIDTH=32
)
(

  // FIELD OUTPUT PORTS
  output reg   [31:0] def_fld_reg_int_mask   ,
  output reg   [31:0] int_clear_reg_int_clear,
  output reg   [31:0] int_set_reg_int_set    ,

  // FIELD INPUT PORTS
  input wire   [15:0] version_reg_version_ip   ,
  input wire   [31:0] def_fld_reg_int_status_ip,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);

  // READ/WRITE ENABLE SIGNALS
  reg  wen_reg_int_mask ;
  reg  wen_reg_int_clear;
  reg  wen_reg_int_set  ;

  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_version   ;
  wire [DATA_WIDTH-1:0] rmux_reg_int_mask  ;
  wire [DATA_WIDTH-1:0] rmux_reg_int_status;

  // FLIP-FLOP SIGNALS
  reg  [15:0] version_reg_version_local   ;
  reg  [31:0] def_fld_reg_int_status_local;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_VERSION_ADDR = 5'h00;
  localparam REG_INT_MASK_ADDR = 5'h04;
  localparam REG_INT_STATUS_ADDR = 5'h08;
  localparam REG_INT_CLEAR_ADDR = 5'h0C;
  localparam REG_INT_SET_ADDR = 5'h10;

  //----------------------------------------------------------------------
  //                    WRITE ADDRESS DECODE
  //----------------------------------------------------------------------
  always @ ( * )
  begin : write_enable
    wen_reg_int_mask = 1'b0;
    wen_reg_int_clear = 1'b0;
    wen_reg_int_set = 1'b0;
    waddrerr = 1'b0;
    wack = 1'b0;

    if (wstrobe)
    begin
      case (waddr)
        REG_INT_MASK_ADDR:
        begin
          wen_reg_int_mask = 1'b1;
        end
        REG_INT_CLEAR_ADDR:
        begin
          wen_reg_int_clear = 1'b1;
        end
        REG_INT_SET_ADDR:
        begin
          wen_reg_int_set = 1'b1;
        end
        default:
        begin
          waddrerr = 1'b1;
        end
      endcase
      wack = 1'b1;
    end
  end


  //------------------------------------------------------------
  // Register: reg_version_reg
  //   Interrupt Generator version register
  //   SW Access     : read-write
  //   Address Offset: 0x00
  //   HW Access     : read-write
  // 
  // Instance: reg_version
  //   Interrupt Generator version register
  //   Address Offset: 0x00
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:0  version (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: version                                
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   version number
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_version_reg_version_reg_version_local
    // Reset
    if ( !reset )
      version_reg_version_local <= 16'h0000;
    // HW:write-only
    else
      version_reg_version_local <= version_reg_version_ip;
  end


  //------------------------------------------------------------
  // Register: reg_int_mask_reg
  //   mask register
  //   SW Access     : read-write
  //   Address Offset: 0x04
  //   HW Access     : read-only
  // 
  // Instance: reg_int_mask
  //   mask register
  //   Address Offset: 0x04
  //   Reset Value   : 0xFFFFFFFF
  // 
  // Fields:
  //   31:0  def_fld (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: def_fld                                
  //   Width: 32             , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   Default field for entire register - reg_int_mask_reg
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_int_mask_reg_def_fld_reg_int_mask
    // Reset
    if ( !reset )
      def_fld_reg_int_mask <= 32'hFFFFFFFF;
    // SW:read-write
    else if (wen_reg_int_mask)
      def_fld_reg_int_mask <= wdata;
  end


  //------------------------------------------------------------
  // Register: reg_int_status_reg
  //   interrupt status register
  //   SW Access     : read-only
  //   Address Offset: 0x08
  //   HW Access     : write-only
  // 
  // Instance: reg_int_status
  //   interrupt status register
  //   Address Offset: 0x08
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:0  def_fld (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: def_fld                                
  //   Width: 32            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   Default field for entire register - reg_int_status_reg
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_int_status_reg_def_fld_reg_int_status_local
    // Reset
    if ( !reset )
      def_fld_reg_int_status_local <= 32'h00000000;
    // HW:write-only
    else
      def_fld_reg_int_status_local <= def_fld_reg_int_status_ip;
  end


  //------------------------------------------------------------
  // Register: reg_int_clear_reg
  //   Interrupt clear register.  (Self-clear)
  //   When set, it clears  corresponding interrupt status bit field.
  //   SW Access     : write-only
  //   Address Offset: 0x0C
  //   HW Access     : read-only
  // 
  // Instance: reg_int_clear
  //   Interrupt clear register.  (Self-clear)
  //   When set, it clears  corresponding interrupt status bit field.
  //   Address Offset: 0x0C
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:0  int_clear (SW:write-only, HW:read-only)

  //------------------------------------------------------------
  //   Field: int_clear                              
  //   Width: 32             , Offset: 0             
  //   SW Access: write-only , HW Access: read-only  
  //------------------------------------------------------------
  //   interrupt clear (self-clear)
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_int_clear_reg_int_clear_reg_int_clear
    // Reset
    if ( !reset )
      int_clear_reg_int_clear <= 32'h00000000;
    // Soft Reset
    else if (!wstrobe)
      int_clear_reg_int_clear <= 0; // self clear
    // SW:write-only
    else if (wen_reg_int_clear)
      int_clear_reg_int_clear <= wdata;
  end


  //------------------------------------------------------------
  // Register: reg_int_set_reg
  //   interrupt event generator register - for debugging
  //   When set, it sets corresponding interrupt status bit field.
  //   SW Access     : write-only
  //   Address Offset: 0x10
  //   HW Access     : read-only
  // 
  // Instance: reg_int_set
  //   interrupt event generator register - for debugging
  //   When set, it sets corresponding interrupt status bit field.
  //   Address Offset: 0x10
  //   Reset Value   : 0
  // 
  // Fields:
  //   31:0  int_set (SW:write-only, HW:read-only)

  //------------------------------------------------------------
  //   Field: int_set                                
  //   Width: 32             , Offset: 0             
  //   SW Access: write-only , HW Access: read-only  
  //------------------------------------------------------------
  //   interrupt set (self-clear)
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_int_set_reg_int_set_reg_int_set
    // Reset
    if ( !reset )
      int_set_reg_int_set <= 32'h00000000;
    // Soft Reset
    else if (!wstrobe)
      int_set_reg_int_set <= 0; // self clear
    // SW:write-only
    else if (wen_reg_int_set)
      int_set_reg_int_set <= wdata;
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_version[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_version[15:0] = version_reg_version_local;

  assign rmux_reg_int_mask = def_fld_reg_int_mask;

  assign rmux_reg_int_status = def_fld_reg_int_status_local;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_VERSION_ADDR:
        begin
          rdata = rmux_reg_version;
        end
        REG_INT_MASK_ADDR:
        begin
          rdata = rmux_reg_int_mask;
        end
        REG_INT_STATUS_ADDR:
        begin
          rdata = rmux_reg_int_status;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

