//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : interrupt_gen_reg_block
// Unit            : interrupt_gen_reg_block_pkg_uvm
// File            : interrupt_gen_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 8/9/21 7:08 PM
//----------------------------------------------------------------------
// Title           : interrupt_gen_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// interrupt_gen_reg_block_pkg_uvm
//----------------------------------------------------------------------
package interrupt_gen_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: reg_int_clear_reg
   // 
   // Interrupt clear register.  (Self-clear)
   // When set, it clears  corresponding interrupt status bit field.
   //--------------------------------------------------------------------

   class reg_int_clear_reg extends uvm_reg;
      `uvm_object_utils(reg_int_clear_reg)

      rand uvm_reg_field int_clear; // interrupt clear (self-clear)


      // Function: coverage
      // 
      covergroup cg_vals;
         int_clear	 : coverpoint int_clear.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_int_clear_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         int_clear = uvm_reg_field::type_id::create("int_clear");

         int_clear.configure(this, 32, 0, "WO", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_int_mask_reg
   // 
   // mask register
   //--------------------------------------------------------------------

   class reg_int_mask_reg extends uvm_reg;
      `uvm_object_utils(reg_int_mask_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_int_mask_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'hffffffff, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_int_set_reg
   // 
   // interrupt event generator register - for debugging
   // When set, it sets corresponding interrupt status bit field.
   //--------------------------------------------------------------------

   class reg_int_set_reg extends uvm_reg;
      `uvm_object_utils(reg_int_set_reg)

      rand uvm_reg_field int_set; // interrupt set (self-clear)


      // Function: coverage
      // 
      covergroup cg_vals;
         int_set	 : coverpoint int_set.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_int_set_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         int_set = uvm_reg_field::type_id::create("int_set");

         int_set.configure(this, 32, 0, "WO", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_int_status_reg
   // 
   // interrupt status register
   //--------------------------------------------------------------------

   class reg_int_status_reg extends uvm_reg;
      `uvm_object_utils(reg_int_status_reg)

      uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_int_status_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RO", 1, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_version_reg
   // 
   // Interrupt Generator version register
   //--------------------------------------------------------------------

   class reg_version_reg extends uvm_reg;
      `uvm_object_utils(reg_version_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field version; // version number


      // Function: coverage
      // 
      covergroup cg_vals;
         version	 : coverpoint version.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_version_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         version = uvm_reg_field::type_id::create("version");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         version.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: interrupt_gen_reg_block
   // 
   //--------------------------------------------------------------------

   class interrupt_gen_reg_block extends uvm_reg_block;
      `uvm_object_utils(interrupt_gen_reg_block)

      rand reg_version_reg reg_version; // Interrupt Generator version register
      rand reg_int_mask_reg reg_int_mask; // mask register
      rand reg_int_status_reg reg_int_status; // interrupt status register
      rand reg_int_clear_reg reg_int_clear; // Interrupt clear register.  (Self-clear)
                                          // When set, it clears  corresponding interrupt status bit field.
      rand reg_int_set_reg reg_int_set; // interrupt event generator register - for debugging
                                       // When set, it sets corresponding interrupt status bit field.

      uvm_reg_map interrupt_gen_reg_block_map; 


      // Function: new
      // 
      function new(string name = "interrupt_gen_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_version = reg_version_reg::type_id::create("reg_version");
         reg_version.configure(this);
         reg_version.build();

         reg_int_mask = reg_int_mask_reg::type_id::create("reg_int_mask");
         reg_int_mask.configure(this);
         reg_int_mask.build();

         reg_int_status = reg_int_status_reg::type_id::create("reg_int_status");
         reg_int_status.configure(this);
         reg_int_status.build();

         reg_int_clear = reg_int_clear_reg::type_id::create("reg_int_clear");
         reg_int_clear.configure(this);
         reg_int_clear.build();

         reg_int_set = reg_int_set_reg::type_id::create("reg_int_set");
         reg_int_set.configure(this);
         reg_int_set.build();

         interrupt_gen_reg_block_map = create_map("interrupt_gen_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = interrupt_gen_reg_block_map;

         interrupt_gen_reg_block_map.add_reg(reg_version, 'h0, "RW");
         interrupt_gen_reg_block_map.add_reg(reg_int_mask, 'h4, "RW");
         interrupt_gen_reg_block_map.add_reg(reg_int_status, 'h8, "RO");
         interrupt_gen_reg_block_map.add_reg(reg_int_clear, 'hc, "WO");
         interrupt_gen_reg_block_map.add_reg(reg_int_set, 'h10, "WO");

         lock_model();
      endfunction
   endclass


endpackage
