//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : local_reg_block
// File            : /home/daniel.lee/cdssen/senUintah/local/reg_gen/output/local_reg_block.v
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 12 08 2021 22:43::02
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : local_reg_block
// Address Range   : 0x14
//----------------------------------------------------------------------

module local_reg_block
#(
  parameter ADDR_WIDTH=5,
  parameter DATA_WIDTH=32
)
(

  // FIELD INPUT PORTS
  input wire   [15:0] version_reg_version_ip   ,
  input wire   [7:0]  num_opa_reg_capability_ip,
  input wire   [7:0]  num_toc_reg_capability_ip,
  input wire   [7:0]  num_adc_reg_capability_ip,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);



  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_version   ;
  wire [DATA_WIDTH-1:0] rmux_reg_capability;

  // FLIP-FLOP SIGNALS
  reg  [15:0] version_reg_version_local   ;
  reg  [7:0]  num_opa_reg_capability_local;
  reg  [7:0]  num_toc_reg_capability_local;
  reg  [7:0]  num_adc_reg_capability_local;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_VERSION_ADDR = 5'h00;
  localparam REG_CAPABILITY_ADDR = 5'h10;




  //------------------------------------------------------------
  // Register: reg_version_reg
  //   Local version register
  //   SW Access     : read-write
  //   Address Offset: 0x00
  //   HW Access     : read-write
  // 
  // Instance: reg_version
  //   Local version register
  //   Address Offset: 0x00
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:0  version (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: version                                
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   version number
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_version_reg_version_reg_version_local
    // Reset
    if ( !reset )
      version_reg_version_local <= 16'h0000;
    // HW:write-only
    else
      version_reg_version_local <= version_reg_version_ip;
  end


  //------------------------------------------------------------
  // Register: reg_capability_reg
  //   Capability Register
  //   SW Access     : read-write
  //   Address Offset: 0x10
  //   HW Access     : read-write
  // 
  // Instance: reg_capability
  //   Capability Register
  //   Address Offset: 0x10
  //   Reset Value   : 
  // 
  // Fields:
  //   31:24  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   23:16  num_opa (SW:read-only, HW:write-only)
  //   15:8  num_toc (SW:read-only, HW:write-only)
  //   7:0  num_adc (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 8                   , Offset: 24             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: num_opa                                
  //   Width: 8             , Offset: 16             
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   number of OPA blocks
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_capability_reg_num_opa_reg_capability_local
    // Reset
    if ( !reset )
      num_opa_reg_capability_local <= 8'h00;
    // HW:write-only
    else
      num_opa_reg_capability_local <= num_opa_reg_capability_ip;
  end

  //------------------------------------------------------------
  //   Field: num_toc                                
  //   Width: 8             , Offset: 8              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   number of TIA offset canceler blocks
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_capability_reg_num_toc_reg_capability_local
    // Reset
    if ( !reset )
      num_toc_reg_capability_local <= 8'h00;
    // HW:write-only
    else
      num_toc_reg_capability_local <= num_toc_reg_capability_ip;
  end

  //------------------------------------------------------------
  //   Field: num_adc                                
  //   Width: 8             , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   number of ADCs
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_capability_reg_num_adc_reg_capability_local
    // Reset
    if ( !reset )
      num_adc_reg_capability_local <= 8'h00;
    // HW:write-only
    else
      num_adc_reg_capability_local <= num_adc_reg_capability_ip;
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_version[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_version[15:0] = version_reg_version_local;

  assign rmux_reg_capability[31:24] = DEF_RDATA_VAL[31:24]; // Default read value for RESERVED field - reserved
  assign rmux_reg_capability[23:16] = num_opa_reg_capability_local;
  assign rmux_reg_capability[15:8] = num_toc_reg_capability_local;
  assign rmux_reg_capability[7:0] = num_adc_reg_capability_local;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_VERSION_ADDR:
        begin
          rdata = rmux_reg_version;
        end
        REG_CAPABILITY_ADDR:
        begin
          rdata = rmux_reg_capability;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

