//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : local_reg_block
// Unit            : local_reg_block_pkg_uvm
// File            : local_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 8/12/21 10:43 PM
//----------------------------------------------------------------------
// Title           : local_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// local_reg_block_pkg_uvm
//----------------------------------------------------------------------
package local_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: reg_capability_reg
   // 
   // Capability Register
   //--------------------------------------------------------------------

   class reg_capability_reg extends uvm_reg;
      `uvm_object_utils(reg_capability_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field num_opa; // number of OPA blocks
      uvm_reg_field num_toc; // number of TIA offset canceler blocks
      uvm_reg_field num_adc; // number of ADCs


      // Function: coverage
      // 
      covergroup cg_vals;
         num_opa	 : coverpoint num_opa.value[7:0];
         num_toc	 : coverpoint num_toc.value[7:0];
         num_adc	 : coverpoint num_adc.value[7:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_capability_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         num_opa = uvm_reg_field::type_id::create("num_opa");
         num_toc = uvm_reg_field::type_id::create("num_toc");
         num_adc = uvm_reg_field::type_id::create("num_adc");

         reserved.configure(this, 8, 24, "RW", 0, 8'h00, 1, 0, 1);
         num_opa.configure(this, 8, 16, "RO", 0, 8'h00, 1, 0, 1);
         num_toc.configure(this, 8, 8, "RO", 0, 8'h00, 1, 0, 1);
         num_adc.configure(this, 8, 0, "RO", 0, 8'h00, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_version_reg
   // 
   // Local version register
   //--------------------------------------------------------------------

   class reg_version_reg extends uvm_reg;
      `uvm_object_utils(reg_version_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field version; // version number


      // Function: coverage
      // 
      covergroup cg_vals;
         version	 : coverpoint version.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_version_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         version = uvm_reg_field::type_id::create("version");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         version.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: local_reg_block
   // 
   //--------------------------------------------------------------------

   class local_reg_block extends uvm_reg_block;
      `uvm_object_utils(local_reg_block)

      rand reg_version_reg reg_version; // Local version register
      rand reg_capability_reg reg_capability; // Capability Register

      uvm_reg_map local_reg_block_map; 


      // Function: new
      // 
      function new(string name = "local_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_version = reg_version_reg::type_id::create("reg_version");
         reg_version.configure(this);
         reg_version.build();

         reg_capability = reg_capability_reg::type_id::create("reg_capability");
         reg_capability.configure(this);
         reg_capability.build();

         local_reg_block_map = create_map("local_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = local_reg_block_map;

         local_reg_block_map.add_reg(reg_version, 'h0, "RW");
         local_reg_block_map.add_reg(reg_capability, 'h10, "RW");

         lock_model();
      endfunction
   endclass


endpackage
