//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : sequencer_reg_block
// Unit            : sequencer_reg_block_pkg_uvm
// File            : sequencer_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 8/9/21 1:43 PM
//----------------------------------------------------------------------
// Title           : sequencer_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// sequencer_reg_block_pkg_uvm
//----------------------------------------------------------------------
package sequencer_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: reg_seq_cfg_reg
   // 
   // Sequencer configuration
   //--------------------------------------------------------------------

   class reg_seq_cfg_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_cfg_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field parity_odd_not_even; // parity odd not even (1-odd parity, 0 - even parity)


      // Function: new
      // 
      function new(string name = "reg_seq_cfg_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         parity_odd_not_even = uvm_reg_field::type_id::create("parity_odd_not_even");

         reserved.configure(this, 31, 1, "RW", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         parity_odd_not_even.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_cmd_reg
   // 
   // Sequener commands
   //--------------------------------------------------------------------

   class reg_seq_cmd_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_cmd_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field clear_done; // write 1 to clear done status (self-clear)
      rand uvm_reg_field clear_err_addr; // write 1 to clear error address (reset error address to 0, self-clear)


      // Function: coverage
      // 
      covergroup cg_vals;
         clear_done	 : coverpoint clear_done.value[0];
         clear_err_addr	 : coverpoint clear_err_addr.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_cmd_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         clear_done = uvm_reg_field::type_id::create("clear_done");
         clear_err_addr = uvm_reg_field::type_id::create("clear_err_addr");

         reserved.configure(this, 30, 2, "RW", 0, 30'b000000000000000000000000000000, 1, 0, 0);
         clear_done.configure(this, 1, 1, "RW", 1, 1'b0, 1, 1, 0);
         clear_err_addr.configure(this, 1, 0, "RW", 1, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_adc1_0_reg
   // 
   // sequencer manual config ADC1 bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_adc1_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_adc1_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_adc1_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_adc1_1_reg
   // 
   // sequencer manual config ADC1 bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_adc1_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_adc1_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_adc1_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_adc1_2_reg
   // 
   // sequencer manual config ADC1 bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_adc1_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_adc1_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_adc1_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_adc2_0_reg
   // 
   // sequencer manual config ADC2 bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_adc2_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_adc2_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_adc2_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_adc2_1_reg
   // 
   // sequencer manual config ADC2 bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_adc2_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_adc2_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_adc2_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_adc2_2_reg
   // 
   // sequencer manual config ADC2 bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_adc2_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_adc2_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_adc2_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa0_0_reg
   // 
   // sequencer manual config OPA0 bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa0_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa0_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa0_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa0_1_reg
   // 
   // sequencer manual config OPA0 bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa0_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa0_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa0_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa0_2_reg
   // 
   // sequencer manual config OPA0 bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa0_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa0_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa0_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa1_0_reg
   // 
   // sequencer manual config OPA1 bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa1_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa1_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa1_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa1_1_reg
   // 
   // sequencer manual config OPA1 bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa1_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa1_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa1_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa1_2_reg
   // 
   // sequencer manual config OPA1 bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa1_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa1_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa1_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa2_0_reg
   // 
   // sequencer manual config OPA2 bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa2_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa2_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa2_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa2_1_reg
   // 
   // sequencer manual config OPA2 bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa2_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa2_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa2_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa2_2_reg
   // 
   // sequencer manual config OPA2 bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa2_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa2_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa2_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa3_0_reg
   // 
   // sequencer manual config OPA3 bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa3_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa3_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa3_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa3_1_reg
   // 
   // sequencer manual config OPA3 bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa3_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa3_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa3_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa3_2_reg
   // 
   // sequencer manual config OPA3 bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa3_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa3_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa3_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa4_0_reg
   // 
   // sequencer manual config OPA4 bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa4_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa4_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa4_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa4_1_reg
   // 
   // sequencer manual config OPA4 bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa4_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa4_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa4_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_opa4_2_reg
   // 
   // sequencer manual config OPA4 bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_opa4_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_opa4_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_opa4_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_tia_0_reg
   // 
   // sequencer manual config TIA bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_tia_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_tia_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_tia_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_tia_1_reg
   // 
   // sequencer manual config TIA bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_tia_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_tia_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_tia_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_tia_2_reg
   // 
   // sequencer manual config TIA bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_tia_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_tia_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_tia_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_tx_0_reg
   // 
   // sequencer manual config transmit bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_tx_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_tx_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_tx_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_tx_1_reg
   // 
   // sequencer manual config transmit bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_tx_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_tx_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_tx_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_tx_2_reg
   // 
   // sequencer manual config transmit bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_tx_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_tx_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_tx_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_wlm_0_reg
   // 
   // sequencer manual config WLM bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_wlm_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_wlm_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_wlm_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_wlm_1_reg
   // 
   // sequencer manual config WLM bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_wlm_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_wlm_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_wlm_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_cfg_wlm_2_reg
   // 
   // sequencer manual config WLM bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_cfg_wlm_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_cfg_wlm_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_man_cfg_wlm_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_ctrl_0_reg
   // 
   // sequencer manual CTRL bits[31:00]
   //--------------------------------------------------------------------

   class reg_seq_man_ctrl_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_ctrl_0_reg)

      rand uvm_reg_field seq_man_ctrl0; // sequencer manul control bits[31:00], self-clear


      // Function: coverage
      // 
      covergroup cg_vals;
         seq_man_ctrl0	 : coverpoint seq_man_ctrl0.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_man_ctrl_0_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         seq_man_ctrl0 = uvm_reg_field::type_id::create("seq_man_ctrl0");

         seq_man_ctrl0.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_ctrl_1_reg
   // 
   // sequencer manual CTRL bits[63:32]
   //--------------------------------------------------------------------

   class reg_seq_man_ctrl_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_ctrl_1_reg)

      rand uvm_reg_field seq_man_ctrl1; // sequencer manul control bits[63:32], self-clear


      // Function: coverage
      // 
      covergroup cg_vals;
         seq_man_ctrl1	 : coverpoint seq_man_ctrl1.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_man_ctrl_1_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         seq_man_ctrl1 = uvm_reg_field::type_id::create("seq_man_ctrl1");

         seq_man_ctrl1.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_man_ctrl_2_reg
   // 
   // sequencer manual CTRL bits[95:64]
   //--------------------------------------------------------------------

   class reg_seq_man_ctrl_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_man_ctrl_2_reg)

      rand uvm_reg_field seq_man_ctrl2; // sequencer manul control bits[95:64], self-clear


      // Function: coverage
      // 
      covergroup cg_vals;
         seq_man_ctrl2	 : coverpoint seq_man_ctrl2.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_man_ctrl_2_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         seq_man_ctrl2 = uvm_reg_field::type_id::create("seq_man_ctrl2");

         seq_man_ctrl2.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_addr_reg
   // 
   // Sequencer memory address
   //--------------------------------------------------------------------

   class reg_seq_mem_addr_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_addr_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field mem_addr; // memory address


      // Function: coverage
      // 
      covergroup cg_vals;
         mem_addr	 : coverpoint mem_addr.value[11:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_mem_addr_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         mem_addr = uvm_reg_field::type_id::create("mem_addr");

         reserved.configure(this, 20, 12, "RW", 0, 20'h00000, 1, 0, 0);
         mem_addr.configure(this, 12, 0, "RW", 0, 12'h000, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_rdata_0_reg
   // 
   // Sequencer Memory read data [31:00]
   //--------------------------------------------------------------------

   class reg_seq_mem_rdata_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_rdata_0_reg)

      uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_mem_rdata_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RO", 1, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_rdata_1_reg
   // 
   // Sequencer Memory read data [63:32]
   //--------------------------------------------------------------------

   class reg_seq_mem_rdata_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_rdata_1_reg)

      uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_mem_rdata_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RO", 1, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_rdata_2_reg
   // 
   // Sequencer Memory read data [95:64]
   //--------------------------------------------------------------------

   class reg_seq_mem_rdata_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_rdata_2_reg)

      uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_mem_rdata_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RO", 1, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_rdata_3_reg
   // 
   // Sequencer Memory read data [127:96]
   //--------------------------------------------------------------------

   class reg_seq_mem_rdata_3_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_rdata_3_reg)

      uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_mem_rdata_3_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RO", 1, 32'h00000000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_wdata_0_reg
   // 
   // Sequencer Memory write data [31:00]
   //--------------------------------------------------------------------

   class reg_seq_mem_wdata_0_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_wdata_0_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_mem_wdata_0_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_wdata_1_reg
   // 
   // Sequencer Memory write data [63:32]
   //--------------------------------------------------------------------

   class reg_seq_mem_wdata_1_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_wdata_1_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_mem_wdata_1_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_wdata_2_reg
   // 
   // Sequencer Memory write data [95:64]
   //--------------------------------------------------------------------

   class reg_seq_mem_wdata_2_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_wdata_2_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_mem_wdata_2_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_wdata_3_reg
   // 
   // Sequencer Memory write data [127:96]
   //--------------------------------------------------------------------

   class reg_seq_mem_wdata_3_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_wdata_3_reg)

      rand uvm_reg_field F;


      // Function: new
      // 
      function new(string name = "reg_seq_mem_wdata_3_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         F = uvm_reg_field::type_id::create("F");
         F.configure(this, 32, 0, "RW", 1, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mem_write_reg
   // 
   // Sequencer memory write strobe
   //--------------------------------------------------------------------

   class reg_seq_mem_write_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mem_write_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field mem_write; // write 1 to write memory wdata to instruction memory.


      // Function: coverage
      // 
      covergroup cg_vals;
         mem_write	 : coverpoint mem_write.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_mem_write_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         mem_write = uvm_reg_field::type_id::create("mem_write");

         reserved.configure(this, 31, 1, "RW", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         mem_write.configure(this, 1, 0, "RW", 1, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_mux_sel_reg
   // 
   // Sequencer mu select
   //--------------------------------------------------------------------

   class reg_seq_mux_sel_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_mux_sel_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field man_ctrl_sel; // 1 - place manual ctrl data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_opa4_sel; // 1 - place manual cfg opa4 data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_opa3_sel; // 1 - place manual cfg opa3 data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_opa2_sel; // 1 - place manual cfg opa2 data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_opa1_sel; // 1 - place manual cfg opa1 data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_opa0_sel; // 1 - place manual cfg opa0 data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_wlm_sel; // 1 - place manual cfg wlm data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_adc2_sel; // 1 - place manual cfg adc2 data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_adc1_sel; // 1 - place manual cfg adc1 data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_tia_sel; // 1 - place manual cfg tia data on sequencer outputs,  0 - sequencer to drive sequencer outputs
      rand uvm_reg_field man_cfg_tx_sel; // 1 - place manual cfg tx data on sequencer outputs,  0 - sequencer to drive sequencer outputs


      // Function: new
      // 
      function new(string name = "reg_seq_mux_sel_reg");
         super.new(name, 32, UVM_NO_COVERAGE);
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         man_ctrl_sel = uvm_reg_field::type_id::create("man_ctrl_sel");
         man_cfg_opa4_sel = uvm_reg_field::type_id::create("man_cfg_opa4_sel");
         man_cfg_opa3_sel = uvm_reg_field::type_id::create("man_cfg_opa3_sel");
         man_cfg_opa2_sel = uvm_reg_field::type_id::create("man_cfg_opa2_sel");
         man_cfg_opa1_sel = uvm_reg_field::type_id::create("man_cfg_opa1_sel");
         man_cfg_opa0_sel = uvm_reg_field::type_id::create("man_cfg_opa0_sel");
         man_cfg_wlm_sel = uvm_reg_field::type_id::create("man_cfg_wlm_sel");
         man_cfg_adc2_sel = uvm_reg_field::type_id::create("man_cfg_adc2_sel");
         man_cfg_adc1_sel = uvm_reg_field::type_id::create("man_cfg_adc1_sel");
         man_cfg_tia_sel = uvm_reg_field::type_id::create("man_cfg_tia_sel");
         man_cfg_tx_sel = uvm_reg_field::type_id::create("man_cfg_tx_sel");

         reserved.configure(this, 21, 11, "RW", 0, 21'b000000000000000000000, 1, 0, 0);
         man_ctrl_sel.configure(this, 1, 10, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_opa4_sel.configure(this, 1, 9, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_opa3_sel.configure(this, 1, 8, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_opa2_sel.configure(this, 1, 7, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_opa1_sel.configure(this, 1, 6, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_opa0_sel.configure(this, 1, 5, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_wlm_sel.configure(this, 1, 4, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_adc2_sel.configure(this, 1, 3, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_adc1_sel.configure(this, 1, 2, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_tia_sel.configure(this, 1, 1, "RW", 0, 1'b0, 1, 1, 0);
         man_cfg_tx_sel.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_start_reg
   // 
   // Sequencer playback start
   //--------------------------------------------------------------------

   class reg_seq_start_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_start_reg)

      uvm_reg_field reserved2; // reserved2
      rand uvm_reg_field start_addr; // playback start address
      uvm_reg_field reserved; // reserved
      rand uvm_reg_field start; // write 1 to playback start (self clear)


      // Function: coverage
      // 
      covergroup cg_vals;
         start	 : coverpoint start.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_start_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved2 = uvm_reg_field::type_id::create("reserved2");
         start_addr = uvm_reg_field::type_id::create("start_addr");
         reserved = uvm_reg_field::type_id::create("reserved");
         start = uvm_reg_field::type_id::create("start");

         reserved2.configure(this, 4, 28, "RW", 0, 4'h0, 1, 0, 0);
         start_addr.configure(this, 12, 16, "RW", 0, 12'h000, 1, 1, 0);
         reserved.configure(this, 15, 1, "RW", 0, 15'b000000000000000, 1, 0, 0);
         start.configure(this, 1, 0, "RW", 1, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_status_reg
   // 
   // Sequencer status
   //--------------------------------------------------------------------

   class reg_seq_status_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_status_reg)

      uvm_reg_field reserved2; // reserved2
      uvm_reg_field err_addr; // err_addr (can be cleared with clear_err_addr)
      uvm_reg_field reserved; // reserved
      uvm_reg_field done; // done (goes low when busy goes high, can be cleared with clear_done)
      uvm_reg_field busy; // busy


      // Function: coverage
      // 
      covergroup cg_vals;
         err_addr	 : coverpoint err_addr.value[11:0];
         done	 : coverpoint done.value[0];
         busy	 : coverpoint busy.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_status_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved2 = uvm_reg_field::type_id::create("reserved2");
         err_addr = uvm_reg_field::type_id::create("err_addr");
         reserved = uvm_reg_field::type_id::create("reserved");
         done = uvm_reg_field::type_id::create("done");
         busy = uvm_reg_field::type_id::create("busy");

         reserved2.configure(this, 4, 28, "RW", 0, 4'h0, 1, 0, 0);
         err_addr.configure(this, 12, 16, "RO", 1, 12'h000, 1, 0, 0);
         reserved.configure(this, 14, 2, "RW", 0, 14'b00000000000000, 1, 0, 0);
         done.configure(this, 1, 1, "RO", 1, 1'b0, 1, 0, 0);
         busy.configure(this, 1, 0, "RO", 1, 1'b0, 1, 0, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_terminate_reg
   // 
   // Sequencer terminate
   //--------------------------------------------------------------------

   class reg_seq_terminate_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_terminate_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field terminate; // write 1 to terminate sequencer (self clear)


      // Function: coverage
      // 
      covergroup cg_vals;
         terminate	 : coverpoint terminate.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_terminate_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         terminate = uvm_reg_field::type_id::create("terminate");

         reserved.configure(this, 31, 1, "RW", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         terminate.configure(this, 1, 0, "RW", 1, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_seq_version_reg
   // 
   // Sequencer version
   //--------------------------------------------------------------------

   class reg_seq_version_reg extends uvm_reg;
      `uvm_object_utils(reg_seq_version_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field version; // version number


      // Function: coverage
      // 
      covergroup cg_vals;
         version	 : coverpoint version.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_seq_version_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         version = uvm_reg_field::type_id::create("version");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         version.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: sequencer_reg_block
   // 
   //--------------------------------------------------------------------

   class sequencer_reg_block extends uvm_reg_block;
      `uvm_object_utils(sequencer_reg_block)

      rand reg_seq_version_reg reg_seq_version; // Sequencer version
      rand reg_seq_mem_addr_reg reg_seq_mem_addr; // Sequencer memory address
      rand reg_seq_mem_write_reg reg_seq_mem_write; // Sequencer memory write strobe
      rand reg_seq_cfg_reg reg_seq_cfg; // Sequencer configuration
      rand reg_seq_start_reg reg_seq_start; // Sequencer playback start
      rand reg_seq_mem_wdata_3_reg reg_seq_mem_wdata_3; // Sequencer Memory write data [127:96]
      rand reg_seq_mem_wdata_2_reg reg_seq_mem_wdata_2; // Sequencer Memory write data [95:64]
      rand reg_seq_mem_wdata_1_reg reg_seq_mem_wdata_1; // Sequencer Memory write data [63:32]
      rand reg_seq_mem_wdata_0_reg reg_seq_mem_wdata_0; // Sequencer Memory write data [31:00]
      rand reg_seq_mem_rdata_3_reg reg_seq_mem_rdata_3; // Sequencer Memory read data [127:96]
      rand reg_seq_mem_rdata_2_reg reg_seq_mem_rdata_2; // Sequencer Memory read data [95:64]
      rand reg_seq_mem_rdata_1_reg reg_seq_mem_rdata_1; // Sequencer Memory read data [63:32]
      rand reg_seq_mem_rdata_0_reg reg_seq_mem_rdata_0; // Sequencer Memory read data [31:00]
      rand reg_seq_cmd_reg reg_seq_cmd; // Sequener commands
      rand reg_seq_status_reg reg_seq_status; // Sequencer status
      rand reg_seq_terminate_reg reg_seq_terminate; // Sequencer terminate
      rand reg_seq_mux_sel_reg reg_seq_mux_sel; // Sequencer mu select
      rand reg_seq_man_cfg_tx_2_reg reg_seq_man_cfg_tx_2; // sequencer manual config transmit bits[95:64]
      rand reg_seq_man_cfg_tx_1_reg reg_seq_man_cfg_tx_1; // sequencer manual config transmit bits[63:32]
      rand reg_seq_man_cfg_tx_0_reg reg_seq_man_cfg_tx_0; // sequencer manual config transmit bits[31:00]
      rand reg_seq_man_cfg_tia_2_reg reg_seq_man_cfg_tia_2; // sequencer manual config TIA bits[95:64]
      rand reg_seq_man_cfg_tia_1_reg reg_seq_man_cfg_tia_1; // sequencer manual config TIA bits[63:32]
      rand reg_seq_man_cfg_tia_0_reg reg_seq_man_cfg_tia_0; // sequencer manual config TIA bits[31:00]
      rand reg_seq_man_cfg_adc1_2_reg reg_seq_man_cfg_adc1_2; // sequencer manual config ADC1 bits[95:64]
      rand reg_seq_man_cfg_adc1_1_reg reg_seq_man_cfg_adc1_1; // sequencer manual config ADC1 bits[63:32]
      rand reg_seq_man_cfg_adc1_0_reg reg_seq_man_cfg_adc1_0; // sequencer manual config ADC1 bits[31:00]
      rand reg_seq_man_cfg_adc2_2_reg reg_seq_man_cfg_adc2_2; // sequencer manual config ADC2 bits[95:64]
      rand reg_seq_man_cfg_adc2_1_reg reg_seq_man_cfg_adc2_1; // sequencer manual config ADC2 bits[63:32]
      rand reg_seq_man_cfg_adc2_0_reg reg_seq_man_cfg_adc2_0; // sequencer manual config ADC2 bits[31:00]
      rand reg_seq_man_cfg_wlm_2_reg reg_seq_man_cfg_wlm_2; // sequencer manual config WLM bits[95:64]
      rand reg_seq_man_cfg_wlm_1_reg reg_seq_man_cfg_wlm_1; // sequencer manual config WLM bits[63:32]
      rand reg_seq_man_cfg_wlm_0_reg reg_seq_man_cfg_wlm_0; // sequencer manual config WLM bits[31:00]
      rand reg_seq_man_cfg_opa0_2_reg reg_seq_man_cfg_opa0_2; // sequencer manual config OPA0 bits[95:64]
      rand reg_seq_man_cfg_opa0_1_reg reg_seq_man_cfg_opa0_1; // sequencer manual config OPA0 bits[63:32]
      rand reg_seq_man_cfg_opa0_0_reg reg_seq_man_cfg_opa0_0; // sequencer manual config OPA0 bits[31:00]
      rand reg_seq_man_cfg_opa1_2_reg reg_seq_man_cfg_opa1_2; // sequencer manual config OPA1 bits[95:64]
      rand reg_seq_man_cfg_opa1_1_reg reg_seq_man_cfg_opa1_1; // sequencer manual config OPA1 bits[63:32]
      rand reg_seq_man_cfg_opa1_0_reg reg_seq_man_cfg_opa1_0; // sequencer manual config OPA1 bits[31:00]
      rand reg_seq_man_cfg_opa2_2_reg reg_seq_man_cfg_opa2_2; // sequencer manual config OPA2 bits[95:64]
      rand reg_seq_man_cfg_opa2_1_reg reg_seq_man_cfg_opa2_1; // sequencer manual config OPA2 bits[63:32]
      rand reg_seq_man_cfg_opa2_0_reg reg_seq_man_cfg_opa2_0; // sequencer manual config OPA2 bits[31:00]
      rand reg_seq_man_cfg_opa3_2_reg reg_seq_man_cfg_opa3_2; // sequencer manual config OPA3 bits[95:64]
      rand reg_seq_man_cfg_opa3_1_reg reg_seq_man_cfg_opa3_1; // sequencer manual config OPA3 bits[63:32]
      rand reg_seq_man_cfg_opa3_0_reg reg_seq_man_cfg_opa3_0; // sequencer manual config OPA3 bits[31:00]
      rand reg_seq_man_cfg_opa4_2_reg reg_seq_man_cfg_opa4_2; // sequencer manual config OPA4 bits[95:64]
      rand reg_seq_man_cfg_opa4_1_reg reg_seq_man_cfg_opa4_1; // sequencer manual config OPA4 bits[63:32]
      rand reg_seq_man_cfg_opa4_0_reg reg_seq_man_cfg_opa4_0; // sequencer manual config OPA4 bits[31:00]
      rand reg_seq_man_ctrl_2_reg reg_seq_man_ctrl_2; // sequencer manual CTRL bits[95:64]
      rand reg_seq_man_ctrl_1_reg reg_seq_man_ctrl_1; // sequencer manual CTRL bits[63:32]
      rand reg_seq_man_ctrl_0_reg reg_seq_man_ctrl_0; // sequencer manual CTRL bits[31:00]

      uvm_reg_map sequencer_reg_block_map; 


      // Function: new
      // 
      function new(string name = "sequencer_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_seq_version = reg_seq_version_reg::type_id::create("reg_seq_version");
         reg_seq_version.configure(this);
         reg_seq_version.build();

         reg_seq_mem_addr = reg_seq_mem_addr_reg::type_id::create("reg_seq_mem_addr");
         reg_seq_mem_addr.configure(this);
         reg_seq_mem_addr.build();

         reg_seq_mem_write = reg_seq_mem_write_reg::type_id::create("reg_seq_mem_write");
         reg_seq_mem_write.configure(this);
         reg_seq_mem_write.build();

         reg_seq_cfg = reg_seq_cfg_reg::type_id::create("reg_seq_cfg");
         reg_seq_cfg.configure(this);
         reg_seq_cfg.build();

         reg_seq_start = reg_seq_start_reg::type_id::create("reg_seq_start");
         reg_seq_start.configure(this);
         reg_seq_start.build();

         reg_seq_mem_wdata_3 = reg_seq_mem_wdata_3_reg::type_id::create("reg_seq_mem_wdata_3");
         reg_seq_mem_wdata_3.configure(this);
         reg_seq_mem_wdata_3.build();

         reg_seq_mem_wdata_2 = reg_seq_mem_wdata_2_reg::type_id::create("reg_seq_mem_wdata_2");
         reg_seq_mem_wdata_2.configure(this);
         reg_seq_mem_wdata_2.build();

         reg_seq_mem_wdata_1 = reg_seq_mem_wdata_1_reg::type_id::create("reg_seq_mem_wdata_1");
         reg_seq_mem_wdata_1.configure(this);
         reg_seq_mem_wdata_1.build();

         reg_seq_mem_wdata_0 = reg_seq_mem_wdata_0_reg::type_id::create("reg_seq_mem_wdata_0");
         reg_seq_mem_wdata_0.configure(this);
         reg_seq_mem_wdata_0.build();

         reg_seq_mem_rdata_3 = reg_seq_mem_rdata_3_reg::type_id::create("reg_seq_mem_rdata_3");
         reg_seq_mem_rdata_3.configure(this);
         reg_seq_mem_rdata_3.build();

         reg_seq_mem_rdata_2 = reg_seq_mem_rdata_2_reg::type_id::create("reg_seq_mem_rdata_2");
         reg_seq_mem_rdata_2.configure(this);
         reg_seq_mem_rdata_2.build();

         reg_seq_mem_rdata_1 = reg_seq_mem_rdata_1_reg::type_id::create("reg_seq_mem_rdata_1");
         reg_seq_mem_rdata_1.configure(this);
         reg_seq_mem_rdata_1.build();

         reg_seq_mem_rdata_0 = reg_seq_mem_rdata_0_reg::type_id::create("reg_seq_mem_rdata_0");
         reg_seq_mem_rdata_0.configure(this);
         reg_seq_mem_rdata_0.build();

         reg_seq_cmd = reg_seq_cmd_reg::type_id::create("reg_seq_cmd");
         reg_seq_cmd.configure(this);
         reg_seq_cmd.build();

         reg_seq_status = reg_seq_status_reg::type_id::create("reg_seq_status");
         reg_seq_status.configure(this);
         reg_seq_status.build();

         reg_seq_terminate = reg_seq_terminate_reg::type_id::create("reg_seq_terminate");
         reg_seq_terminate.configure(this);
         reg_seq_terminate.build();

         reg_seq_mux_sel = reg_seq_mux_sel_reg::type_id::create("reg_seq_mux_sel");
         reg_seq_mux_sel.configure(this);
         reg_seq_mux_sel.build();

         reg_seq_man_cfg_tx_2 = reg_seq_man_cfg_tx_2_reg::type_id::create("reg_seq_man_cfg_tx_2");
         reg_seq_man_cfg_tx_2.configure(this);
         reg_seq_man_cfg_tx_2.build();

         reg_seq_man_cfg_tx_1 = reg_seq_man_cfg_tx_1_reg::type_id::create("reg_seq_man_cfg_tx_1");
         reg_seq_man_cfg_tx_1.configure(this);
         reg_seq_man_cfg_tx_1.build();

         reg_seq_man_cfg_tx_0 = reg_seq_man_cfg_tx_0_reg::type_id::create("reg_seq_man_cfg_tx_0");
         reg_seq_man_cfg_tx_0.configure(this);
         reg_seq_man_cfg_tx_0.build();

         reg_seq_man_cfg_tia_2 = reg_seq_man_cfg_tia_2_reg::type_id::create("reg_seq_man_cfg_tia_2");
         reg_seq_man_cfg_tia_2.configure(this);
         reg_seq_man_cfg_tia_2.build();

         reg_seq_man_cfg_tia_1 = reg_seq_man_cfg_tia_1_reg::type_id::create("reg_seq_man_cfg_tia_1");
         reg_seq_man_cfg_tia_1.configure(this);
         reg_seq_man_cfg_tia_1.build();

         reg_seq_man_cfg_tia_0 = reg_seq_man_cfg_tia_0_reg::type_id::create("reg_seq_man_cfg_tia_0");
         reg_seq_man_cfg_tia_0.configure(this);
         reg_seq_man_cfg_tia_0.build();

         reg_seq_man_cfg_adc1_2 = reg_seq_man_cfg_adc1_2_reg::type_id::create("reg_seq_man_cfg_adc1_2");
         reg_seq_man_cfg_adc1_2.configure(this);
         reg_seq_man_cfg_adc1_2.build();

         reg_seq_man_cfg_adc1_1 = reg_seq_man_cfg_adc1_1_reg::type_id::create("reg_seq_man_cfg_adc1_1");
         reg_seq_man_cfg_adc1_1.configure(this);
         reg_seq_man_cfg_adc1_1.build();

         reg_seq_man_cfg_adc1_0 = reg_seq_man_cfg_adc1_0_reg::type_id::create("reg_seq_man_cfg_adc1_0");
         reg_seq_man_cfg_adc1_0.configure(this);
         reg_seq_man_cfg_adc1_0.build();

         reg_seq_man_cfg_adc2_2 = reg_seq_man_cfg_adc2_2_reg::type_id::create("reg_seq_man_cfg_adc2_2");
         reg_seq_man_cfg_adc2_2.configure(this);
         reg_seq_man_cfg_adc2_2.build();

         reg_seq_man_cfg_adc2_1 = reg_seq_man_cfg_adc2_1_reg::type_id::create("reg_seq_man_cfg_adc2_1");
         reg_seq_man_cfg_adc2_1.configure(this);
         reg_seq_man_cfg_adc2_1.build();

         reg_seq_man_cfg_adc2_0 = reg_seq_man_cfg_adc2_0_reg::type_id::create("reg_seq_man_cfg_adc2_0");
         reg_seq_man_cfg_adc2_0.configure(this);
         reg_seq_man_cfg_adc2_0.build();

         reg_seq_man_cfg_wlm_2 = reg_seq_man_cfg_wlm_2_reg::type_id::create("reg_seq_man_cfg_wlm_2");
         reg_seq_man_cfg_wlm_2.configure(this);
         reg_seq_man_cfg_wlm_2.build();

         reg_seq_man_cfg_wlm_1 = reg_seq_man_cfg_wlm_1_reg::type_id::create("reg_seq_man_cfg_wlm_1");
         reg_seq_man_cfg_wlm_1.configure(this);
         reg_seq_man_cfg_wlm_1.build();

         reg_seq_man_cfg_wlm_0 = reg_seq_man_cfg_wlm_0_reg::type_id::create("reg_seq_man_cfg_wlm_0");
         reg_seq_man_cfg_wlm_0.configure(this);
         reg_seq_man_cfg_wlm_0.build();

         reg_seq_man_cfg_opa0_2 = reg_seq_man_cfg_opa0_2_reg::type_id::create("reg_seq_man_cfg_opa0_2");
         reg_seq_man_cfg_opa0_2.configure(this);
         reg_seq_man_cfg_opa0_2.build();

         reg_seq_man_cfg_opa0_1 = reg_seq_man_cfg_opa0_1_reg::type_id::create("reg_seq_man_cfg_opa0_1");
         reg_seq_man_cfg_opa0_1.configure(this);
         reg_seq_man_cfg_opa0_1.build();

         reg_seq_man_cfg_opa0_0 = reg_seq_man_cfg_opa0_0_reg::type_id::create("reg_seq_man_cfg_opa0_0");
         reg_seq_man_cfg_opa0_0.configure(this);
         reg_seq_man_cfg_opa0_0.build();

         reg_seq_man_cfg_opa1_2 = reg_seq_man_cfg_opa1_2_reg::type_id::create("reg_seq_man_cfg_opa1_2");
         reg_seq_man_cfg_opa1_2.configure(this);
         reg_seq_man_cfg_opa1_2.build();

         reg_seq_man_cfg_opa1_1 = reg_seq_man_cfg_opa1_1_reg::type_id::create("reg_seq_man_cfg_opa1_1");
         reg_seq_man_cfg_opa1_1.configure(this);
         reg_seq_man_cfg_opa1_1.build();

         reg_seq_man_cfg_opa1_0 = reg_seq_man_cfg_opa1_0_reg::type_id::create("reg_seq_man_cfg_opa1_0");
         reg_seq_man_cfg_opa1_0.configure(this);
         reg_seq_man_cfg_opa1_0.build();

         reg_seq_man_cfg_opa2_2 = reg_seq_man_cfg_opa2_2_reg::type_id::create("reg_seq_man_cfg_opa2_2");
         reg_seq_man_cfg_opa2_2.configure(this);
         reg_seq_man_cfg_opa2_2.build();

         reg_seq_man_cfg_opa2_1 = reg_seq_man_cfg_opa2_1_reg::type_id::create("reg_seq_man_cfg_opa2_1");
         reg_seq_man_cfg_opa2_1.configure(this);
         reg_seq_man_cfg_opa2_1.build();

         reg_seq_man_cfg_opa2_0 = reg_seq_man_cfg_opa2_0_reg::type_id::create("reg_seq_man_cfg_opa2_0");
         reg_seq_man_cfg_opa2_0.configure(this);
         reg_seq_man_cfg_opa2_0.build();

         reg_seq_man_cfg_opa3_2 = reg_seq_man_cfg_opa3_2_reg::type_id::create("reg_seq_man_cfg_opa3_2");
         reg_seq_man_cfg_opa3_2.configure(this);
         reg_seq_man_cfg_opa3_2.build();

         reg_seq_man_cfg_opa3_1 = reg_seq_man_cfg_opa3_1_reg::type_id::create("reg_seq_man_cfg_opa3_1");
         reg_seq_man_cfg_opa3_1.configure(this);
         reg_seq_man_cfg_opa3_1.build();

         reg_seq_man_cfg_opa3_0 = reg_seq_man_cfg_opa3_0_reg::type_id::create("reg_seq_man_cfg_opa3_0");
         reg_seq_man_cfg_opa3_0.configure(this);
         reg_seq_man_cfg_opa3_0.build();

         reg_seq_man_cfg_opa4_2 = reg_seq_man_cfg_opa4_2_reg::type_id::create("reg_seq_man_cfg_opa4_2");
         reg_seq_man_cfg_opa4_2.configure(this);
         reg_seq_man_cfg_opa4_2.build();

         reg_seq_man_cfg_opa4_1 = reg_seq_man_cfg_opa4_1_reg::type_id::create("reg_seq_man_cfg_opa4_1");
         reg_seq_man_cfg_opa4_1.configure(this);
         reg_seq_man_cfg_opa4_1.build();

         reg_seq_man_cfg_opa4_0 = reg_seq_man_cfg_opa4_0_reg::type_id::create("reg_seq_man_cfg_opa4_0");
         reg_seq_man_cfg_opa4_0.configure(this);
         reg_seq_man_cfg_opa4_0.build();

         reg_seq_man_ctrl_2 = reg_seq_man_ctrl_2_reg::type_id::create("reg_seq_man_ctrl_2");
         reg_seq_man_ctrl_2.configure(this);
         reg_seq_man_ctrl_2.build();

         reg_seq_man_ctrl_1 = reg_seq_man_ctrl_1_reg::type_id::create("reg_seq_man_ctrl_1");
         reg_seq_man_ctrl_1.configure(this);
         reg_seq_man_ctrl_1.build();

         reg_seq_man_ctrl_0 = reg_seq_man_ctrl_0_reg::type_id::create("reg_seq_man_ctrl_0");
         reg_seq_man_ctrl_0.configure(this);
         reg_seq_man_ctrl_0.build();

         sequencer_reg_block_map = create_map("sequencer_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = sequencer_reg_block_map;

         sequencer_reg_block_map.add_reg(reg_seq_version, 'h0, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_mem_addr, 'h10, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_mem_write, 'h14, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_cfg, 'h18, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_start, 'h1c, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_mem_wdata_3, 'h20, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_mem_wdata_2, 'h24, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_mem_wdata_1, 'h28, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_mem_wdata_0, 'h2c, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_mem_rdata_3, 'h30, "RO");
         sequencer_reg_block_map.add_reg(reg_seq_mem_rdata_2, 'h34, "RO");
         sequencer_reg_block_map.add_reg(reg_seq_mem_rdata_1, 'h38, "RO");
         sequencer_reg_block_map.add_reg(reg_seq_mem_rdata_0, 'h3c, "RO");
         sequencer_reg_block_map.add_reg(reg_seq_cmd, 'h40, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_status, 'h44, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_terminate, 'h48, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_mux_sel, 'h50, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_tx_2, 'h54, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_tx_1, 'h58, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_tx_0, 'h5c, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_tia_2, 'h64, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_tia_1, 'h68, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_tia_0, 'h6c, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_adc1_2, 'h74, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_adc1_1, 'h78, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_adc1_0, 'h7c, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_adc2_2, 'h84, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_adc2_1, 'h88, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_adc2_0, 'h8c, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_wlm_2, 'h94, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_wlm_1, 'h98, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_wlm_0, 'h9c, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa0_2, 'ha4, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa0_1, 'ha8, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa0_0, 'hac, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa1_2, 'hb4, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa1_1, 'hb8, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa1_0, 'hbc, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa2_2, 'hc4, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa2_1, 'hc8, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa2_0, 'hcc, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa3_2, 'hd4, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa3_1, 'hd8, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa3_0, 'hdc, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa4_2, 'he4, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa4_1, 'he8, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_cfg_opa4_0, 'hec, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_ctrl_2, 'hf4, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_ctrl_1, 'hf8, "RW");
         sequencer_reg_block_map.add_reg(reg_seq_man_ctrl_0, 'hfc, "RW");

         lock_model();
      endfunction
   endclass


endpackage
