//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : test_mux_reg_block
// File            : /home/daniel.lee/cdssen/senUintah/test_mux/reg_gen/output/test_mux_reg_block.v
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 12 08 2021 13:28::26
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : test_mux_reg_block
// Address Range   : 0x18
//----------------------------------------------------------------------

module test_mux_reg_block
#(
  parameter ADDR_WIDTH=5,
  parameter DATA_WIDTH=32
)
(

  // FIELD OUTPUT PORTS
  output reg   [7:0] sel_data_reg_mux_sel  ,
  output reg   [7:0] sel_module_reg_mux_sel,
  output reg         nibble_sel_reg_mux_cfg,

  // FIELD INPUT PORTS
  input wire   [15:0] version_reg_version_ip,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);

  // READ/WRITE ENABLE SIGNALS
  reg  wen_reg_mux_sel;
  reg  wen_reg_mux_cfg;

  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_version;
  wire [DATA_WIDTH-1:0] rmux_reg_mux_sel;
  wire [DATA_WIDTH-1:0] rmux_reg_mux_cfg;

  // FLIP-FLOP SIGNALS
  reg  [15:0] version_reg_version_local;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_VERSION_ADDR = 5'h00;
  localparam REG_MUX_SEL_ADDR = 5'h10;
  localparam REG_MUX_CFG_ADDR = 5'h14;

  //----------------------------------------------------------------------
  //                    WRITE ADDRESS DECODE
  //----------------------------------------------------------------------
  always @ ( * )
  begin : write_enable
    wen_reg_mux_sel = 1'b0;
    wen_reg_mux_cfg = 1'b0;
    waddrerr = 1'b0;
    wack = 1'b0;

    if (wstrobe)
    begin
      case (waddr)
        REG_MUX_SEL_ADDR:
        begin
          wen_reg_mux_sel = 1'b1;
        end
        REG_MUX_CFG_ADDR:
        begin
          wen_reg_mux_cfg = 1'b1;
        end
        default:
        begin
          waddrerr = 1'b1;
        end
      endcase
      wack = 1'b1;
    end
  end


  //------------------------------------------------------------
  // Register: reg_version_reg
  //   Arbiter version register
  //   SW Access     : read-write
  //   Address Offset: 0x00
  //   HW Access     : read-write
  // 
  // Instance: reg_version
  //   Arbiter version register
  //   Address Offset: 0x00
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:0  version (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: version                                
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   version number
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_version_reg_version_reg_version_local
    // Reset
    if ( !reset )
      version_reg_version_local <= 16'h0000;
    // HW:write-only
    else
      version_reg_version_local <= version_reg_version_ip;
  end


  //------------------------------------------------------------
  // Register: reg_mux_sel_reg
  //   test mux select register
  //   SW Access     : read-write
  //   Address Offset: 0x10
  //   HW Access     : read-write
  // 
  // Instance: reg_mux_sel
  //   test mux select register
  //   Address Offset: 0x10
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //   15:8  sel_data (SW:read-write, HW:read-only)
  //   7:0  sel_module (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 16                  , Offset: 16             
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: sel_data                               
  //   Width: 8              , Offset: 8             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   select data
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_mux_sel_reg_sel_data_reg_mux_sel
    // Reset
    if ( !reset )
      sel_data_reg_mux_sel <= 8'h00;
    // SW:read-write
    else if (wen_reg_mux_sel)
      sel_data_reg_mux_sel <= wdata[15:8];
  end

  //------------------------------------------------------------
  //   Field: sel_module                             
  //   Width: 8              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   select module
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_mux_sel_reg_sel_module_reg_mux_sel
    // Reset
    if ( !reset )
      sel_module_reg_mux_sel <= 8'h00;
    // SW:read-write
    else if (wen_reg_mux_sel)
      sel_module_reg_mux_sel <= wdata[7:0];
  end


  //------------------------------------------------------------
  // Register: reg_mux_cfg_reg
  //   test mux configuration regsiter
  //   SW Access     : read-write
  //   Address Offset: 0x14
  //   HW Access     : read-write
  // 
  // Instance: reg_mux_cfg
  //   test mux configuration regsiter
  //   Address Offset: 0x14
  //   Reset Value   : 
  // 
  // Fields:
  //   31:1  reserved (SW:read-write, HW:read-write) (RESERVED) 
  //     0  nibble_sel (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: reserved (reserved)                          
  //   Width: 31                  , Offset: 1              
  //   SW Access: read-write      , HW Access: read-write  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: nibble_sel                             
  //   Width: 1              , Offset: 0             
  //   SW Access: read-write , HW Access: read-only  
  //------------------------------------------------------------
  //   output nibble selection (1- upper nibble test data, 0 - lower nibble test data)
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_mux_cfg_reg_nibble_sel_reg_mux_cfg
    // Reset
    if ( !reset )
      nibble_sel_reg_mux_cfg <= 1'b0;
    // SW:read-write
    else if (wen_reg_mux_cfg)
      nibble_sel_reg_mux_cfg <= wdata[0];
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_version[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_version[15:0] = version_reg_version_local;

  assign rmux_reg_mux_sel[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - reserved
  assign rmux_reg_mux_sel[15:8] = sel_data_reg_mux_sel;
  assign rmux_reg_mux_sel[7:0] = sel_module_reg_mux_sel;

  assign rmux_reg_mux_cfg[31:1] = DEF_RDATA_VAL[31:1]; // Default read value for RESERVED field - reserved
  assign rmux_reg_mux_cfg[0] = nibble_sel_reg_mux_cfg;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_VERSION_ADDR:
        begin
          rdata = rmux_reg_version;
        end
        REG_MUX_SEL_ADDR:
        begin
          rdata = rmux_reg_mux_sel;
        end
        REG_MUX_CFG_ADDR:
        begin
          rdata = rmux_reg_mux_cfg;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

