//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : test_mux_reg_block
// Unit            : test_mux_reg_block_pkg_uvm
// File            : test_mux_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : daniel.lee
// Creation Date   : 8/12/21 1:28 PM
//----------------------------------------------------------------------
// Title           : test_mux_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// test_mux_reg_block_pkg_uvm
//----------------------------------------------------------------------
package test_mux_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: reg_mux_cfg_reg
   // 
   // test mux configuration regsiter
   //--------------------------------------------------------------------

   class reg_mux_cfg_reg extends uvm_reg;
      `uvm_object_utils(reg_mux_cfg_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field nibble_sel; // output nibble selection (1- upper nibble test data, 0 - lower nibble test data)


      // Function: coverage
      // 
      covergroup cg_vals;
         nibble_sel	 : coverpoint nibble_sel.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_mux_cfg_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         nibble_sel = uvm_reg_field::type_id::create("nibble_sel");

         reserved.configure(this, 31, 1, "RW", 0, 31'b0000000000000000000000000000000, 1, 0, 0);
         nibble_sel.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_mux_sel_reg
   // 
   // test mux select register
   //--------------------------------------------------------------------

   class reg_mux_sel_reg extends uvm_reg;
      `uvm_object_utils(reg_mux_sel_reg)

      uvm_reg_field reserved; // reserved
      rand uvm_reg_field sel_data; // select data
      rand uvm_reg_field sel_module; // select module


      // Function: coverage
      // 
      covergroup cg_vals;
         sel_data	 : coverpoint sel_data.value[7:0];
         sel_module	 : coverpoint sel_module.value[7:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_mux_sel_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         sel_data = uvm_reg_field::type_id::create("sel_data");
         sel_module = uvm_reg_field::type_id::create("sel_module");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         sel_data.configure(this, 8, 8, "RW", 0, 8'h00, 1, 1, 1);
         sel_module.configure(this, 8, 0, "RW", 0, 8'h00, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_version_reg
   // 
   // Arbiter version register
   //--------------------------------------------------------------------

   class reg_version_reg extends uvm_reg;
      `uvm_object_utils(reg_version_reg)

      uvm_reg_field reserved; // reserved
      uvm_reg_field version; // version number


      // Function: coverage
      // 
      covergroup cg_vals;
         version	 : coverpoint version.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_version_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         reserved = uvm_reg_field::type_id::create("reserved");
         version = uvm_reg_field::type_id::create("version");

         reserved.configure(this, 16, 16, "RW", 0, 16'h0000, 1, 0, 1);
         version.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: test_mux_reg_block
   // 
   //--------------------------------------------------------------------

   class test_mux_reg_block extends uvm_reg_block;
      `uvm_object_utils(test_mux_reg_block)

      rand reg_version_reg reg_version; // Arbiter version register
      rand reg_mux_sel_reg reg_mux_sel; // test mux select register
      rand reg_mux_cfg_reg reg_mux_cfg; // test mux configuration regsiter

      uvm_reg_map test_mux_reg_block_map; 


      // Function: new
      // 
      function new(string name = "test_mux_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_version = reg_version_reg::type_id::create("reg_version");
         reg_version.configure(this);
         reg_version.build();

         reg_mux_sel = reg_mux_sel_reg::type_id::create("reg_mux_sel");
         reg_mux_sel.configure(this);
         reg_mux_sel.build();

         reg_mux_cfg = reg_mux_cfg_reg::type_id::create("reg_mux_cfg");
         reg_mux_cfg.configure(this);
         reg_mux_cfg.build();

         test_mux_reg_block_map = create_map("test_mux_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = test_mux_reg_block_map;

         test_mux_reg_block_map.add_reg(reg_version, 'h0, "RW");
         test_mux_reg_block_map.add_reg(reg_mux_sel, 'h10, "RW");
         test_mux_reg_block_map.add_reg(reg_mux_cfg, 'h14, "RW");

         lock_model();
      endfunction
   endclass


endpackage
