//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//----------------------------------------------------------------------
// Project         : tia_offset_cancel_reg_block
// File            : /home/puneeth/cdssen/senUintah/tia_offset_cancel/reg_gen/output/tia_offset_cancel_reg_block.v
//----------------------------------------------------------------------
// Created by      : puneeth.reddy
// Creation Date   : 13 08 2021 16:28::59
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// Block           : tia_offset_cancel_reg_block
// Address Range   : 0xC
//----------------------------------------------------------------------

module tia_offset_cancel_reg_block
#(
  parameter ADDR_WIDTH=4,
  parameter DATA_WIDTH=32
)
(

  // FIELD OUTPUT PORTS
  output reg   [9:0] comp_settling_time_settling_time,
  output reg   [9:0] dac_settling_time_settling_time ,

  // FIELD INPUT PORTS
  input wire   [15:0] id_reg_block_revision_ip             ,
  input wire   [7:0]  dac_ambient_cancel_value_dac_debug_ip,
  input wire   [7:0]  dac_monitor_dac_debug_ip             ,

  // GENERIC BUS PORTS
  input  wire                  clock   , // Register Bus Clock
  input  wire                  reset   , // Register Bus Reset
  input  wire [ADDR_WIDTH-1:0] waddr   , // Write Address-Bus
  input  wire [ADDR_WIDTH-1:0] raddr   , // Read Address-Bus
  input  wire [DATA_WIDTH-1:0] wdata   , // Write Data-Bus
  output reg  [DATA_WIDTH-1:0] rdata   , // Read Data-Bus
  input  wire                  rstrobe , // Read-Strobe
  input  wire                  wstrobe , // Write-Strobe
  output reg                   raddrerr, // Read-Address-Error
  output reg                   waddrerr, // Write-Address-Error
  output reg                   wack    , // Write Acknowledge
  output reg                   rack      // Read Acknowledge
);

  // READ/WRITE ENABLE SIGNALS
  reg  wen_settling_time;

  // MUX INPUTS FOR EACH INSTANCE WITH READ ACCESS
  wire [DATA_WIDTH-1:0] rmux_reg_block_revision;
  wire [DATA_WIDTH-1:0] rmux_settling_time     ;
  wire [DATA_WIDTH-1:0] rmux_dac_debug         ;

  // FLIP-FLOP SIGNALS
  reg  [15:0] id_reg_block_revision_local             ;
  reg  [7:0]  dac_ambient_cancel_value_dac_debug_local;
  reg  [7:0]  dac_monitor_dac_debug_local             ;

  // DEFAULT VALUE FOR READ DATA BUS
  localparam DEF_RDATA_VAL = 32'h00000000;

  // ADDRESS PARAMETERS
  localparam REG_BLOCK_REVISION_ADDR = 4'h0;
  localparam SETTLING_TIME_ADDR = 4'h4;
  localparam DAC_DEBUG_ADDR = 4'h8;

  //----------------------------------------------------------------------
  //                    WRITE ADDRESS DECODE
  //----------------------------------------------------------------------
  always @ ( * )
  begin : write_enable
    wen_settling_time = 1'b0;
    waddrerr = 1'b0;
    wack = 1'b0;

    if (wstrobe)
    begin
      case (waddr)
        SETTLING_TIME_ADDR:
        begin
          wen_settling_time = 1'b1;
        end
        default:
        begin
          waddrerr = 1'b1;
        end
      endcase
      wack = 1'b1;
    end
  end


  //------------------------------------------------------------
  // Register: reg_block_revision_reg
  //   Defines the revision ID of the tia_offset_cancel reg block
  //   SW Access     : read-write
  //   Address Offset: 0x0
  //   HW Access     : read-write
  // 
  // Instance: reg_block_revision
  //   Defines the revision ID of the tia_offset_cancel reg block
  //   Address Offset: 0x0
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  Reserved_16_31 (SW:read-write, HW:read-only) (RESERVED) 
  //   15:0  id (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: Reserved_16_31 (reserved)                         
  //   Width: 16                        , Offset: 16            
  //   SW Access: read-write            , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: id                                     
  //   Width: 16            , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   Defines the revision ID of the tia_offset_cancel reg block
  //
  always @ (posedge clock or negedge reset)
  begin : reg_reg_block_revision_reg_id_reg_block_revision_local
    // Reset
    if ( !reset )
      id_reg_block_revision_local <= 16'h0000;
    // HW:write-only
    else
      id_reg_block_revision_local <= id_reg_block_revision_ip;
  end


  //------------------------------------------------------------
  // Register: settling_time_reg
  //   defines the settling times for dac and comparator in the tia offset cancellation analog block, specified in multiple of coreclk
  //   SW Access     : read-write
  //   Address Offset: 0x4
  //   HW Access     : read-write
  // 
  // Instance: settling_time
  //   defines the settling times for dac and comparator in the tia offset cancellation analog block, specified in multiple of coreclk
  //   Address Offset: 0x4
  //   Reset Value   : 
  // 
  // Fields:
  //   31:20  Reserved_24_31 (SW:read-write, HW:read-only) (RESERVED) 
  //   19:10  comp_settling_time (SW:read-write, HW:read-only)
  //   9:0  dac_settling_time (SW:read-write, HW:read-only)

  //------------------------------------------------------------
  //   Field: Reserved_24_31 (reserved)                         
  //   Width: 12                        , Offset: 20            
  //   SW Access: read-write            , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: comp_settling_time                         
  //   Width: 10                 , Offset: 10            
  //   SW Access: read-write     , HW Access: read-only  
  //------------------------------------------------------------
  //   defines the settling time for the comparator, specified in multiple of coreclk cycles
  //
  always @ (posedge clock or negedge reset)
  begin : reg_settling_time_reg_comp_settling_time_settling_time
    // Reset
    if ( !reset )
      comp_settling_time_settling_time <= 10'h0F1;
    // SW:read-write
    else if (wen_settling_time)
      comp_settling_time_settling_time <= wdata[19:10];
  end

  //------------------------------------------------------------
  //   Field: dac_settling_time                         
  //   Width: 10                , Offset: 0             
  //   SW Access: read-write    , HW Access: read-only  
  //------------------------------------------------------------
  //   defines the settling time for the dac in specified in multiple of coreclk cycles
  //
  always @ (posedge clock or negedge reset)
  begin : reg_settling_time_reg_dac_settling_time_settling_time
    // Reset
    if ( !reset )
      dac_settling_time_settling_time <= 10'h0F1;
    // SW:read-write
    else if (wen_settling_time)
      dac_settling_time_settling_time <= wdata[9:0];
  end


  //------------------------------------------------------------
  // Register: dac_debug_reg
  //   debug registers that can help in dac debug
  //   SW Access     : read-write
  //   Address Offset: 0x8
  //   HW Access     : read-write
  // 
  // Instance: dac_debug
  //   debug registers that can help in dac debug
  //   Address Offset: 0x8
  //   Reset Value   : 
  // 
  // Fields:
  //   31:16  Reserved_24_31 (SW:read-write, HW:read-only) (RESERVED) 
  //   15:8  dac_ambient_cancel_value (SW:read-only, HW:write-only)
  //   7:0  dac_monitor (SW:read-only, HW:write-only)

  //------------------------------------------------------------
  //   Field: Reserved_24_31 (reserved)                         
  //   Width: 16                        , Offset: 16            
  //   SW Access: read-write            , HW Access: read-only  
  //------------------------------------------------------------
  //   reserved
  //

  //------------------------------------------------------------
  //   Field: dac_ambient_cancel_value                          
  //   Width: 8                        , Offset: 8              
  //   SW Access: read-only            , HW Access: write-only  
  //------------------------------------------------------------
  //   the dac input value that was measured in the ambient/dark covnersion stage can be read here
  //
  always @ (posedge clock or negedge reset)
  begin : reg_dac_debug_reg_dac_ambient_cancel_value_dac_debug_local
    // Reset
    if ( !reset )
      dac_ambient_cancel_value_dac_debug_local <= 8'h00;
    // HW:write-only
    else
      dac_ambient_cancel_value_dac_debug_local <= dac_ambient_cancel_value_dac_debug_ip;
  end

  //------------------------------------------------------------
  //   Field: dac_monitor                            
  //   Width: 8             , Offset: 0              
  //   SW Access: read-only , HW Access: write-only  
  //------------------------------------------------------------
  //   the digital input value to the dac can be read here
  //
  always @ (posedge clock or negedge reset)
  begin : reg_dac_debug_reg_dac_monitor_dac_debug_local
    // Reset
    if ( !reset )
      dac_monitor_dac_debug_local <= 8'h00;
    // HW:write-only
    else
      dac_monitor_dac_debug_local <= dac_monitor_dac_debug_ip;
  end


  //----------------------------------------------------------------------
  //                    READ BUS MULTIPLEXER
  //----------------------------------------------------------------------
  assign rmux_reg_block_revision[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - Reserved_16_31
  assign rmux_reg_block_revision[15:0] = id_reg_block_revision_local;

  assign rmux_settling_time[31:20] = DEF_RDATA_VAL[31:20]; // Default read value for RESERVED field - Reserved_24_31
  assign rmux_settling_time[19:10] = comp_settling_time_settling_time;
  assign rmux_settling_time[9:0] = dac_settling_time_settling_time;

  assign rmux_dac_debug[31:16] = DEF_RDATA_VAL[31:16]; // Default read value for RESERVED field - Reserved_24_31
  assign rmux_dac_debug[15:8] = dac_ambient_cancel_value_dac_debug_local;
  assign rmux_dac_debug[7:0] = dac_monitor_dac_debug_local;

  // PUT REGISTER VALUE ON READ DATA BUS
  always @ ( * )
  begin : read_bus_mux
    raddrerr = 1'b0;
    rdata = DEF_RDATA_VAL;
    if (rstrobe )
    begin
      case (raddr)
        REG_BLOCK_REVISION_ADDR:
        begin
          rdata = rmux_reg_block_revision;
        end
        SETTLING_TIME_ADDR:
        begin
          rdata = rmux_settling_time;
        end
        DAC_DEBUG_ADDR:
        begin
          rdata = rmux_dac_debug;
        end
        default:
        begin
          raddrerr = 1'b1;
        end
      endcase
    end
    rack = rstrobe;
  end
endmodule

