//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V2021.2 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : tia_offset_cancel_reg_block
// Unit            : tia_offset_cancel_reg_block_pkg_uvm
// File            : tia_offset_cancel_reg_block_pkg_uvm.sv
//----------------------------------------------------------------------
// Created by      : puneeth.reddy
// Creation Date   : 8/13/21 4:28 PM
//----------------------------------------------------------------------
// Title           : tia_offset_cancel_reg_block
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// tia_offset_cancel_reg_block_pkg_uvm
//----------------------------------------------------------------------
package tia_offset_cancel_reg_block_pkg_uvm;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: dac_debug_reg
   // 
   // debug registers that can help in dac debug
   //--------------------------------------------------------------------

   class dac_debug_reg extends uvm_reg;
      `uvm_object_utils(dac_debug_reg)

      uvm_reg_field Reserved_24_31; // reserved
      uvm_reg_field dac_ambient_cancel_value; // the dac input value that was measured in the ambient/dark covnersion stage can be read here
      uvm_reg_field dac_monitor; // the digital input value to the dac can be read here


      // Function: coverage
      // 
      covergroup cg_vals;
         dac_ambient_cancel_value	 : coverpoint dac_ambient_cancel_value.value[7:0];
         dac_monitor	 : coverpoint dac_monitor.value[7:0];
      endgroup



      // Function: new
      // 
      function new(string name = "dac_debug_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         Reserved_24_31 = uvm_reg_field::type_id::create("Reserved_24_31");
         dac_ambient_cancel_value = uvm_reg_field::type_id::create("dac_ambient_cancel_value");
         dac_monitor = uvm_reg_field::type_id::create("dac_monitor");

         Reserved_24_31.configure(this, 16, 16, "RW", 1, 16'h0000, 1, 0, 1);
         dac_ambient_cancel_value.configure(this, 8, 8, "RO", 0, 8'h00, 1, 0, 1);
         dac_monitor.configure(this, 8, 0, "RO", 0, 8'h00, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: reg_block_revision_reg
   // 
   // Defines the revision ID of the tia_offset_cancel reg block
   //--------------------------------------------------------------------

   class reg_block_revision_reg extends uvm_reg;
      `uvm_object_utils(reg_block_revision_reg)

      uvm_reg_field Reserved_16_31; // reserved
      uvm_reg_field id; // Defines the revision ID of the tia_offset_cancel reg block


      // Function: coverage
      // 
      covergroup cg_vals;
         id	 : coverpoint id.value[15:0];
      endgroup



      // Function: new
      // 
      function new(string name = "reg_block_revision_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         Reserved_16_31 = uvm_reg_field::type_id::create("Reserved_16_31");
         id = uvm_reg_field::type_id::create("id");

         Reserved_16_31.configure(this, 16, 16, "RW", 1, 16'h0000, 1, 0, 1);
         id.configure(this, 16, 0, "RO", 0, 16'h0000, 1, 0, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: settling_time_reg
   // 
   // defines the settling times for dac and comparator in the tia offset cancellation analog block, specified in multiple of coreclk
   //--------------------------------------------------------------------

   class settling_time_reg extends uvm_reg;
      `uvm_object_utils(settling_time_reg)

      uvm_reg_field Reserved_24_31; // reserved
      rand uvm_reg_field comp_settling_time; // defines the settling time for the comparator, specified in multiple of coreclk cycles
      rand uvm_reg_field dac_settling_time; // defines the settling time for the dac in specified in multiple of coreclk cycles


      // Function: coverage
      // 
      covergroup cg_vals;
         comp_settling_time	 : coverpoint comp_settling_time.value[9:0];
         dac_settling_time	 : coverpoint dac_settling_time.value[9:0];
      endgroup



      // Function: new
      // 
      function new(string name = "settling_time_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         Reserved_24_31 = uvm_reg_field::type_id::create("Reserved_24_31");
         comp_settling_time = uvm_reg_field::type_id::create("comp_settling_time");
         dac_settling_time = uvm_reg_field::type_id::create("dac_settling_time");

         Reserved_24_31.configure(this, 12, 20, "RW", 1, 12'h000, 1, 0, 0);
         comp_settling_time.configure(this, 10, 10, "RW", 0, 10'b0011110001, 1, 1, 0);
         dac_settling_time.configure(this, 10, 0, "RW", 0, 10'b0011110001, 1, 1, 0);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: tia_offset_cancel_reg_block
   // 
   //--------------------------------------------------------------------

   class tia_offset_cancel_reg_block extends uvm_reg_block;
      `uvm_object_utils(tia_offset_cancel_reg_block)

      rand reg_block_revision_reg reg_block_revision; // Defines the revision ID of the tia_offset_cancel reg block
      rand settling_time_reg settling_time; // defines the settling times for dac and comparator in the tia offset cancellation analog block, specified in multiple of coreclk
      rand dac_debug_reg dac_debug; // debug registers that can help in dac debug

      uvm_reg_map tia_offset_cancel_reg_block_map; 


      // Function: new
      // 
      function new(string name = "tia_offset_cancel_reg_block");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         reg_block_revision = reg_block_revision_reg::type_id::create("reg_block_revision");
         reg_block_revision.configure(this);
         reg_block_revision.build();

         settling_time = settling_time_reg::type_id::create("settling_time");
         settling_time.configure(this);
         settling_time.build();

         dac_debug = dac_debug_reg::type_id::create("dac_debug");
         dac_debug.configure(this);
         dac_debug.build();

         tia_offset_cancel_reg_block_map = create_map("tia_offset_cancel_reg_block_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = tia_offset_cancel_reg_block_map;

         tia_offset_cancel_reg_block_map.add_reg(reg_block_revision, 'h0, "RW");
         tia_offset_cancel_reg_block_map.add_reg(settling_time, 'h4, "RW");
         tia_offset_cancel_reg_block_map.add_reg(dac_debug, 'h8, "RW");

         lock_model();
      endfunction
   endclass


endpackage
