#!/usr/bin/env python3
"""
CAD Verification Directory Structure Generator

This script generates standardized directory structures for CAD verification
environments at three hierarchical levels: unit, subsystem, and system.

Author: CAD Verification Team
Date: 2025
"""

import os
import sys
import argparse
import shutil
from pathlib import Path
from typing import List


class CADVerificationStructureGenerator:
    """
    A class to generate CAD verification directory structures.
    """
    
    def __init__(self):
        """Initialize the generator with directory structure definitions."""
        
        # Define common directories for all levels
        self.common_dirs = [
            'agents',
            'env',
            'tests',
            'sequences',
            'tb',
            'assertions',
            'ral',
            'docs',
            'scripts',
            'sim/regression',
            'sim/results',
            'sim/vcs',
            'sim/xcelium',
            'sim/questa'
        ]
        
        # Define level-specific directories
        self.unit_subsystem_dirs = self.common_dirs + ['interface']
        self.system_dirs = self.common_dirs  # System doesn't have interface
        
        # Define files to create
        self.files_to_create = [
            ('sim/regression/run_regression.py', self._get_regression_template()),
            ('sim/run_test.py', self._get_test_template()),
            ('sim/Makefile', self._get_makefile_template()),
            ('sim/vcs/Makefile', self._get_vcs_makefile_template()),
            ('sim/xcelium/Makefile', self._get_xcelium_makefile_template()),
            ('sim/questa/Makefile', self._get_questa_makefile_template()),
            ('filelist.f', self._get_filelist_template())
        ]
        
        # Track created items for reporting
        self.created_dirs = []
        self.created_files = []
        self.skipped_items = []
    
    def _get_regression_template(self) -> str:
        """Return template content for run_regression.py"""
        return '''#!/usr/bin/env python3
"""
Regression test runner for CAD verification.
"""

import os
import sys
import subprocess
from datetime import datetime


def run_regression():
    """Run regression test suite."""
    print(f"Starting regression run at {datetime.now()}")
    # TODO: Implement regression test logic
    pass


if __name__ == "__main__":
    run_regression()
'''
    
    def _get_test_template(self) -> str:
        """Return template content for run_test.py"""
        return '''#!/usr/bin/env python3
"""
Individual test runner for CAD verification.
"""

import os
import sys
import argparse


def run_test(test_name):
    """Run a specific test."""
    print(f"Running test: {test_name}")
    # TODO: Implement test execution logic
    pass


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run individual CAD verification test")
    parser.add_argument("test_name", help="Name of the test to run")
    args = parser.parse_args()
    
    run_test(args.test_name)
'''
    
    def _get_makefile_template(self) -> str:
        """Return template content for main sim/Makefile"""
        return '''# Main Verification Makefile - ExpFifo
# Generated by Verification Structure Generator
# This Makefile delegates to simulator-specific Makefiles

#===========================================
# SIMULATION VARIABLES
#===========================================

# Default simulator (can be overridden: make SIM=vcs)
SIM ?= vcs

# Default test
TEST ?= fifo_base_test

# Default verbosity
VERBOSITY ?= UVM_MEDIUM

# Default seed
SEED ?= 1

# Common variables to pass to sub-makefiles
MAKE_VARS = TEST=$(TEST) VERBOSITY=$(VERBOSITY) SEED=$(SEED) WAVES=$(WAVES) COV=$(COV)

#===========================================
# SIMULATOR PATHS
#===========================================

VCS_DIR = vcs
XCELIUM_DIR = xcelium
QUESTA_DIR = questa
REGRESSION_DIR = regression

#===========================================
# DEFAULT AND HELP TARGETS
#===========================================

.PHONY: all help clean clean_all

# Default target
all: help

# Help target
help:
	@echo "Verification Main Makefile - ExpFifo"
	@echo "==============================================="
	@echo "Available targets:"
	@echo "  help       - Show this help message"
	@echo ""
	@echo "SIMULATION TARGETS:"
	@echo "  vcs        - Compile and run with VCS"
	@echo "  xcelium    - Compile and run with Xcelium" 
	@echo "  questa     - Compile and run with Questa"
	@echo ""
	@echo "  compile    - Compile only (auto-detects simulator)"
	@echo "  simulate   - Run simulation (auto-detects simulator)"
	@echo "  run        - Compile and run (auto-detects simulator)"
	@echo "  debug      - Launch waveform viewer (auto-detects simulator)"
	@echo ""
	@echo "UTILITY TARGETS:"
	@echo "  clean      - Clean build artifacts for all simulators"
	@echo "  clean_all  - Clean all including results directories"
	@echo "  regression - Run regression tests"
	@echo "  regression_random  - Run regression tests with random seed"
	@echo "  regression_quick   - Run quick regression (subset of tests)"
	@echo "  regression_parallel - Run parallel regression (4 jobs)"
	@echo "  cov_report - Generate coverage report (auto-detects simulator)"
	@echo ""
	@echo "DEBUG TARGETS:"
	@echo "  vcs_debug     - Launch Verdi (VCS waveform viewer)"
	@echo "  xcelium_debug - Launch SimVision (Xcelium waveform viewer)"
	@echo "  questa_debug  - Launch QuestaSim viewer (Questa waveform viewer)"
	@echo ""
	@echo "SIMULATOR-SPECIFIC HELP:"
	@echo "  vcs_help      - Show VCS-specific help"
	@echo "  xcelium_help  - Show Xcelium-specific help"
	@echo "  questa_help   - Show Questa-specific help"
	@echo ""
	@echo "VARIABLES:"
	@echo "  SIM        - Simulator: vcs|xcelium|questa (default: $(SIM))"
	@echo "  TEST       - Test name (default: $(TEST))"
	@echo "  VERBOSITY  - UVM verbosity (default: $(VERBOSITY))"
	@echo "  SEED       - Random seed (default: $(SEED))"
	@echo "  WAVES      - Enable waveforms: 1|0 (default: 0)"
	@echo "  COV        - Enable coverage: 1|0 (default: 0)"
	@echo ""
	@echo "AVAILABLE TESTS:"
	@echo "  fifo_base_test         - Basic functionality test"
	@echo "  fifo_basic_test        - Basic read/write operations"
	@echo "  fifo_fill_test         - Fill and empty FIFO test"
	@echo "  fifo_simultaneous_test - Simultaneous read/write test"
	@echo "  fifo_random_test       - Random operations test"
	@echo "  fifo_wraparound_test   - Wraparound behavior test"
	@echo "  fifo_reset_test        - Reset functionality test"
	@echo "  fifo_enable_edge_test  - Enable signal edge cases test"
	@echo "  fifo_comprehensive_test - All tests combined"
	@echo ""
	@echo "EXAMPLES:"
	@echo "  make vcs TEST=fifo_random_test SEED=42"
	@echo "  make xcelium TEST=fifo_comprehensive_test WAVES=1"
	@echo "  make questa COV=1 VERBOSITY=UVM_HIGH"
	@echo "  make run SIM=vcs TEST=fifo_random_test"

#===========================================
# SIMULATOR-SPECIFIC TARGETS
#===========================================

.PHONY: vcs xcelium questa vcs_help xcelium_help questa_help

# VCS targets
vcs:
	@echo "Delegating to VCS Makefile..."
	@$(MAKE) -C $(VCS_DIR) run $(MAKE_VARS)

vcs_compile:
	@$(MAKE) -C $(VCS_DIR) compile $(MAKE_VARS)

vcs_sim:
	@$(MAKE) -C $(VCS_DIR) sim $(MAKE_VARS)

vcs_clean:
	@$(MAKE) -C $(VCS_DIR) clean

vcs_clean_all:
	@$(MAKE) -C $(VCS_DIR) clean_all

vcs_cov_report:
	@$(MAKE) -C $(VCS_DIR) cov_report

vcs_debug:
	@$(MAKE) -C $(VCS_DIR) debug

vcs_help:
	@$(MAKE) -C $(VCS_DIR) help

# Xcelium targets
xcelium:
	@echo "Delegating to Xcelium Makefile..."
	@$(MAKE) -C $(XCELIUM_DIR) run $(MAKE_VARS)

xcelium_compile:
	@$(MAKE) -C $(XCELIUM_DIR) compile $(MAKE_VARS)

xcelium_sim:
	@$(MAKE) -C $(XCELIUM_DIR) sim $(MAKE_VARS)

xcelium_clean:
	@$(MAKE) -C $(XCELIUM_DIR) clean

xcelium_clean_all:
	@$(MAKE) -C $(XCELIUM_DIR) clean_all

xcelium_cov_report:
	@$(MAKE) -C $(XCELIUM_DIR) cov_report

xcelium_debug:
	@$(MAKE) -C $(XCELIUM_DIR) debug

xcelium_help:
	@$(MAKE) -C $(XCELIUM_DIR) help

# Questa targets
questa:
	@echo "Delegating to Questa Makefile..."
	@$(MAKE) -C $(QUESTA_DIR) run $(MAKE_VARS)

questa_compile:
	@$(MAKE) -C $(QUESTA_DIR) compile $(MAKE_VARS)

questa_sim:
	@$(MAKE) -C $(QUESTA_DIR) sim $(MAKE_VARS)

questa_gui:
	@$(MAKE) -C $(QUESTA_DIR) gui $(MAKE_VARS)

questa_clean:
	@$(MAKE) -C $(QUESTA_DIR) clean

questa_clean_all:
	@$(MAKE) -C $(QUESTA_DIR) clean_all

questa_cov_report:
	@$(MAKE) -C $(QUESTA_DIR) cov_report

questa_debug:
	@$(MAKE) -C $(QUESTA_DIR) debug

questa_help:
	@$(MAKE) -C $(QUESTA_DIR) help

#===========================================
# GENERIC TARGETS (AUTO-DETECT SIMULATOR)
#===========================================

.PHONY: compile simulate run cov_report debug

# Generic compile target (uses SIM variable)
compile:
	@echo "Compiling with $(SIM)..."
	@$(MAKE) $(SIM)_compile $(MAKE_VARS)

# Generic simulate target (uses SIM variable)
simulate:
	@echo "Running simulation with $(SIM)..."
	@$(MAKE) $(SIM)_sim $(MAKE_VARS)

# Generic run target (compile + simulate)
run:
	@echo "Running complete flow with $(SIM)..."
	@$(MAKE) $(SIM) $(MAKE_VARS)

# Generic coverage report target
cov_report:
	@echo "Generating coverage report with $(SIM)..."
	@$(MAKE) $(SIM)_cov_report

# Generic debug target (launch waveform viewer)
debug:
	@echo "Launching debug viewer for $(SIM)..."
	@$(MAKE) $(SIM)_debug

#===========================================
# UTILITY TARGETS
#===========================================

.PHONY: clean clean_all regression regression_random regression_quick regression_parallel setup_dirs

# Clean all simulators
clean:
	@echo "Cleaning all simulator artifacts..."
	@-$(MAKE) vcs_clean 2>/dev/null || echo "VCS clean completed (or VCS not available)"
	@-$(MAKE) xcelium_clean 2>/dev/null || echo "Xcelium clean completed (or Xcelium not available)"
	@-$(MAKE) questa_clean 2>/dev/null || echo "Questa clean completed (or Questa not available)"
	@echo "Cleaning common artifacts..."
	@rm -rf results

# Clean all (including results directories)
clean_all:
	@echo "Cleaning all artifacts including results..."
	@-$(MAKE) vcs_clean_all 2>/dev/null || echo "VCS clean_all completed (or VCS not available)"
	@-$(MAKE) xcelium_clean_all 2>/dev/null || echo "Xcelium clean_all completed (or Xcelium not available)"  
	@-$(MAKE) questa_clean_all 2>/dev/null || echo "Questa clean_all completed (or Questa not available)"
	@rm -rf results

# Regression target
regression:
	@echo "Running regression tests..."
	@if [ -d "$(REGRESSION_DIR)" ]; then \
		if [ ! -f "$(REGRESSION_DIR)/run_regression.py" ]; then \
			echo "Error: Regression script not found. Please ensure run_regression.py exists."; \
			exit 1; \
		fi; \
		echo "Starting regression with simulator: $(SIM)"; \
		cd $(REGRESSION_DIR) && python3 run_regression.py --simulator $(SIM) $(MAKE_VARS); \
	else \
		echo "Warning: Regression directory not found. Skipping regression tests."; \
	fi

# Regression with random seed
regression_random:
	@echo "Running regression tests with random seed..."
	@if [ -d "$(REGRESSION_DIR)" ]; then \
		if [ ! -f "$(REGRESSION_DIR)/run_regression.py" ]; then \
			echo "Error: Regression script not found. Please ensure run_regression.py exists."; \
			exit 1; \
		fi; \
		RANDOM_SEED=$$RANDOM; \
		echo "Starting regression with simulator: $(SIM) and random seed: $$RANDOM_SEED"; \
		cd $(REGRESSION_DIR) && python3 run_regression.py --simulator $(SIM) SEED=$$RANDOM_SEED TEST=$(TEST) VERBOSITY=$(VERBOSITY) WAVES=$(WAVES) COV=$(COV); \
	else \
		echo "Warning: Regression directory not found. Skipping regression tests."; \
	fi

# Quick regression (subset of tests)
regression_quick:
	@echo "Running quick regression tests..."
	@if [ -d "$(REGRESSION_DIR)" ]; then \
		if [ ! -f "$(REGRESSION_DIR)/run_regression.py" ]; then \
			echo "Error: Regression script not found. Please ensure run_regression.py exists."; \
			exit 1; \
		fi; \
		echo "Starting quick regression with simulator: $(SIM)"; \
		cd $(REGRESSION_DIR) && python3 run_regression.py --simulator $(SIM) --quick $(MAKE_VARS); \
	else \
		echo "Warning: Regression directory not found. Skipping regression tests."; \
	fi

# Parallel regression
regression_parallel:
	@echo "Running parallel regression tests..."
	@if [ -d "$(REGRESSION_DIR)" ]; then \
		if [ ! -f "$(REGRESSION_DIR)/run_regression.py" ]; then \
			echo "Error: Regression script not found. Please ensure run_regression.py exists."; \
			exit 1; \
		fi; \
		echo "Starting parallel regression with simulator: $(SIM)"; \
		cd $(REGRESSION_DIR) && python3 run_regression.py --simulator $(SIM) --jobs 4 $(MAKE_VARS); \
	else \
		echo "Warning: Regression directory not found. Skipping regression tests."; \
	fi

# Setup directories for all simulators
setup_dirs:
	@echo "Setting up simulator directories..."
	@mkdir -p $(VCS_DIR) $(XCELIUM_DIR) $(QUESTA_DIR)
	@mkdir -p results/vcs results/xcelium results/questa

#===========================================
# VALIDATION TARGETS
#===========================================

.PHONY: validate_sim

# Validate simulator selection
validate_sim:
	@case "$(SIM)" in \
		vcs|xcelium|questa) \
			echo "Using simulator: $(SIM)" ;; \
		*) \
			echo "Error: Invalid simulator '$(SIM)'. Valid options: vcs, xcelium, questa" >&2; \
			exit 1 ;; \
	esac

# Add validation as a dependency for generic targets
compile: validate_sim
simulate: validate_sim
run: validate_sim
cov_report: validate_sim
debug: validate_sim
'''
    
    def _get_vcs_makefile_template(self) -> str:
        """Return template content for VCS Makefile"""
        return '''# VCS-Specific Makefile - ExpFifo
# Generated by Verification Structure Generator

#===========================================
# COMMON SIMULATION VARIABLES
#===========================================

# Default test
TEST ?= fifo_base_test

# Default verbosity
VERBOSITY ?= UVM_MEDIUM

# Default seed
SEED ?= 1

# File paths
FILELIST = ../filelist.f
EXECUTABLE = simv

# Results directory
RESULTS_DIR = ../results/vcs
LOG_FILE = $(RESULTS_DIR)/vcs_$(TEST)_$(SEED).log

# VCS-specific flags
VCS_FLAGS = -sverilog -ntb_opts uvm-1.2 -debug_access+all -kdb -lca -timescale=1ns/1ps -full64 -LDFLAGS -Wl,--no-as-needed +define+VCS
VCS_SIM_FLAGS = -licqueue -full64 -assert svaext +warn=noTFIDF

# Enable waveforms (0=off, 1=on)
WAVES ?= 0
ifeq ($(WAVES),1)
    VCS_FLAGS += -debug_access+all
    VCS_SIM_FLAGS += +USE_FSDB
endif

# Enable coverage (0=off, 1=on)  
COV ?= 0
ifeq ($(COV),1)
    VCS_FLAGS += -cm line+cond+fsm+branch+tgl
    VCS_SIM_FLAGS += -cm line+cond+fsm+branch+tgl
endif

#===========================================
# FILE AND DIRECTORY PATHS
#===========================================

COMPILE_LOG = $(RESULTS_DIR)/vcs_compile.log

#===========================================
# VCS TARGETS
#===========================================

.PHONY: all help compile sim run clean clean_all cov_report debug

# Default target
all: help

help:
	@echo "VCS Simulator Makefile - ExpFifo"
	@echo "================================"
	@echo "Available targets:"
	@echo "  compile    - Compile testbench"
	@echo "  sim        - Run simulation only"
	@echo "  run        - Compile and run (default flow)"
	@echo "  clean      - Clean VCS artifacts"
	@echo "  clean_all  - Clean all VCS files including results"
	@echo "  cov_report - Generate coverage report"
	@echo "  debug      - Launch Verdi for waveform debug"
	@echo "  help       - Show this help"
	@echo ""
	@echo "Variables:"
	@echo "  TEST       - Test name (default: $(TEST))"
	@echo "  VERBOSITY  - UVM verbosity (default: $(VERBOSITY))"
	@echo "  SEED       - Random seed (default: $(SEED))"
	@echo "  WAVES      - Enable waveforms: 1|0 (default: $(WAVES))"
	@echo "  COV        - Enable coverage: 1|0 (default: $(COV))"
	@echo ""
	@echo "Available tests:"
	@echo "  fifo_base_test, fifo_basic_test, fifo_fill_test,"
	@echo "  fifo_simultaneous_test, fifo_random_test, fifo_wraparound_test,"
	@echo "  fifo_reset_test, fifo_enable_edge_test, fifo_comprehensive_test"
	@echo ""
	@echo "Examples:"
	@echo "  make compile"
	@echo "  make run TEST=fifo_random_test SEED=42"
	@echo "  make run WAVES=1 COV=1"

#===========================================
# BUILD TARGETS
#===========================================

$(RESULTS_DIR):
	@mkdir -p $(RESULTS_DIR)

compile: $(RESULTS_DIR)
	@echo "=============================================="
	@echo "Compiling ExpFifo with VCS..."
	@echo "=============================================="
	@if command -v vcs >/dev/null 2>&1; then \\
		cd ../.. && vcs $(VCS_FLAGS) -f filelist.f -l sim/results/vcs/vcs_compile.log -o sim/vcs/simv; \\
		echo "Compilation completed. Check $(COMPILE_LOG) for details."; \\
	else \\
		echo "Error: VCS not found. Please ensure VCS is installed and in your PATH."; \\
		exit 1; \\
	fi

sim: $(EXECUTABLE)
	@echo "=============================================="
	@echo "Running VCS simulation..."
	@echo "Test: $(TEST), Seed: $(SEED)"
	@echo "=============================================="
	@./$(EXECUTABLE) $(VCS_SIM_FLAGS) +UVM_TESTNAME=$(TEST) +UVM_VERBOSITY=$(VERBOSITY) +ntb_random_seed=$(SEED) -l $(LOG_FILE)
	@echo "Simulation completed. Check $(LOG_FILE) for results."

run: compile sim

#===========================================
# UTILITY TARGETS
#===========================================

clean:
	@echo "Cleaning VCS artifacts..."
	@rm -rf *.log simv* csrc *.vpd *.fsdb *.key DVEfiles
	@rm -rf .vcs* vc_hdrs.h ucli.key
	@rm -rf novas.conf novas.rc verdi_config_file
	@rm -rf novas_dump.log
	@echo "VCS clean completed."

clean_all: clean
	@echo "Cleaning VCS results..."
	@rm -rf $(RESULTS_DIR)
	@echo "VCS clean_all completed."

cov_report:
	@if [ "$(COV)" = "1" ] && [ -d "simv.vdb" ]; then \\
		echo "Generating VCS coverage report..."; \\
		if command -v urg >/dev/null 2>&1; then \\
			urg -dir simv.vdb -report $(RESULTS_DIR)/coverage_report; \\
			echo "Coverage report available at: $(RESULTS_DIR)/coverage_report/dashboard.html"; \\
		else \\
			echo "Warning: URG (urg) not found. Cannot generate coverage report."; \\
		fi \\
	elif [ "$(COV)" != "1" ]; then \\
		echo "Coverage not enabled. Use COV=1 to enable coverage collection."; \\
	else \\
		echo "Coverage database not found. Run simulation with COV=1 first."; \\
	fi

#===========================================
# DEPENDENCIES
#===========================================

$(EXECUTABLE): ../../filelist.f
	@$(MAKE) compile

#===========================================
# DEBUG TARGETS
#===========================================

debug:
	@if command -v verdi >/dev/null 2>&1 && [ -f "novas.fsdb" ]; then \\
		echo "Launching Verdi..."; \\
		verdi -dbdir ./simv.daidir -ssf novas.fsdb & \\
	elif [ ! -f "novas.fsdb" ]; then \\
		echo "Error: Waveform file not found. Run simulation with WAVES=1 first."; \\
	else \\
		echo "Warning: Verdi not found. Please ensure Verdi is installed and in your PATH."; \\
	fi
'''

    def _get_xcelium_makefile_template(self) -> str:
        """Return template content for Xcelium Makefile"""
        return '''# Xcelium-Specific Makefile - ExpFifo
# Generated by Verification Structure Generator

#===========================================
# COMMON SIMULATION VARIABLES
#===========================================

# Default test
TEST ?= fifo_base_test

# Default verbosity
VERBOSITY ?= UVM_MEDIUM

# Default seed
SEED ?= 1

# File paths (relative to sim directory)
FILELIST = ../filelist.f
TB_TOP = fifo_tb_top

# Results directory
RESULTS_DIR = ../results/xcelium
LOG_FILE = $(RESULTS_DIR)/xcelium_$(TEST)_$(SEED).log

# Common simulation arguments
COMMON_ARGS = +UVM_TESTNAME=$(TEST) +UVM_VERBOSITY=$(VERBOSITY) +ntb_random_seed=$(SEED)

# Coverage options
COV_DIR = $(RESULTS_DIR)/coverage

# Enable waveforms (0=off, 1=on)
WAVES ?= 0

# Enable coverage (0=off, 1=on)  
COV ?= 0

# Waveform options
WAVE_ARGS = -input shm.tcl

#===========================================
# XCELIUM VARIABLES AND OPTIONS
#===========================================

XCELIUM = xrun
XCELIUM_COMP_OPTS = -sv -uvm -64bit -access +rwc -timescale 1ns/1ps +define+XCELIUM
XCELIUM_COMP_OPTS += -nowarn SPDUSD -nowarn SAWSTP -disable_sem2009
XCELIUM_SIM_OPTS = -R -64bit +UVM_NO_RELNOTES

# Add waveform and coverage flags conditionally
ifeq ($(WAVES),1)
    XCELIUM_COMP_OPTS += -input shm.tcl
    WAVE_DB = waves.shm
endif

ifeq ($(COV),1)
    XCELIUM_COMP_OPTS += -coverage all -covdut $(TB_TOP)
    XCELIUM_SIM_OPTS += -covdir $(COV_DIR)/xcelium_cov
endif

#===========================================
# XCELIUM TARGETS
#===========================================

.PHONY: all compile sim run clean clean_all cov_report help debug gui

# Default target
all: run

# Help target
help:
	@echo "Xcelium Simulation Makefile - ExpFifo"
	@echo "====================================="
	@echo "Available targets:"
	@echo "  help       - Show this help message"
	@echo "  all/run    - Compile and run simulation"
	@echo "  compile    - Compile only"
	@echo "  sim        - Run simulation (requires compilation first)"
	@echo "  clean      - Clean build artifacts"
	@echo "  clean_all  - Clean all including results directory"
	@echo "  cov_report - Generate coverage report"
	@echo "  debug      - Launch SimVision for waveform debug"
	@echo "  gui        - Launch SimVision (same as debug)"
	@echo ""
	@echo "VARIABLES:"
	@echo "  TEST       - Test name (default: $(TEST))"
	@echo "  VERBOSITY  - UVM verbosity (default: $(VERBOSITY))"
	@echo "  SEED       - Random seed (default: $(SEED))"
	@echo "  WAVES      - Enable waveforms: 1|0 (default: 0)"
	@echo "  COV        - Enable coverage: 1|0 (default: 0)"
	@echo ""
	@echo "Available tests:"
	@echo "  fifo_base_test, fifo_basic_test, fifo_fill_test,"
	@echo "  fifo_simultaneous_test, fifo_random_test, fifo_wraparound_test,"
	@echo "  fifo_reset_test, fifo_enable_edge_test, fifo_comprehensive_test"
	@echo ""
	@echo "EXAMPLES:"
	@echo "  make run TEST=fifo_random_test SEED=42"
	@echo "  make run TEST=fifo_comprehensive_test WAVES=1"
	@echo "  make run COV=1 VERBOSITY=UVM_HIGH"
	@echo "  make debug  # After running with WAVES=1"

# Complete flow: compile and run (Xcelium does both in one step)
run: $(RESULTS_DIR) $(if $(findstring 1,$(WAVES)),shm.tcl,)
	@echo "==============================================="
	@echo "Compiling and Running ExpFifo with Xcelium..."
	@echo "Test: $(TEST), Seed: $(SEED)"
	@echo "==============================================="
	@if command -v xrun >/dev/null 2>&1; then \\
		cd .. && xrun $(XCELIUM_COMP_OPTS) -f $(FILELIST) \\
			$(COMMON_ARGS) \\
			$(if $(findstring 1,$(WAVES)),-input xcelium/shm.tcl,) \\
			$(if $(findstring 1,$(COV)),-coverage all -covdut $(TB_TOP) -covdir xcelium/$(COV_DIR)/xcelium_cov,) \\
			-logfile xcelium/$(LOG_FILE) \\
			$(XCELIUM_SIM_OPTS); \\
		echo "Simulation completed. Check $(LOG_FILE) for results."; \\
	else \\
		echo "Error: Xcelium (xrun) not found. Please ensure Xcelium is installed and in your PATH."; \\
		exit 1; \\
	fi

# Compile target (same as run for Xcelium)
compile: $(RESULTS_DIR)
	@echo "==============================================="
	@echo "Compiling ExpFifo with Xcelium..."
	@echo "==============================================="
	@if command -v xrun >/dev/null 2>&1; then \\
		cd .. && xrun $(XCELIUM_COMP_OPTS) -f $(FILELIST) \\
			$(if $(findstring 1,$(COV)),-coverage all -covdut $(TB_TOP),) \\
			-logfile xcelium/$(RESULTS_DIR)/xcelium_compile.log; \\
		echo "Compilation completed. Check $(RESULTS_DIR)/xcelium_compile.log for details."; \\
	else \\
		echo "Error: Xcelium (xrun) not found. Please ensure Xcelium is installed and in your PATH."; \\
		exit 1; \\
	fi

# Simulation target (for consistency, but Xcelium typically does compile+sim together)
sim:
	@echo "==============================================="
	@echo "Running Xcelium simulation..." 
	@echo "Test: $(TEST), Seed: $(SEED)"
	@echo "==============================================="
	cd .. && $(XCELIUM) $(XCELIUM_SIM_OPTS) $(COMMON_ARGS) \\
		$(if $(findstring 1,$(WAVES)),$(WAVE_ARGS),) \\
		$(if $(findstring 1,$(COV)),-coverage all -covdut $(TB_TOP) -covdir xcelium/$(COV_DIR)/xcelium,) \\
		-logfile xcelium/$(LOG_FILE) | tee xcelium/$(LOG_FILE)

# Clean target
clean:
	@echo "Cleaning Xcelium build artifacts..."
	@rm -rf *.log xcelium.d *.key .simvision *.shm *.fsdb
	@rm -rf cov_work xcrg xcelium.history
	@rm -rf shm.tcl novas.conf novas.rc
	@echo "Xcelium clean completed."

# Clean all (including results directory)
clean_all: clean
	rm -rf $(RESULTS_DIR)

# Coverage report generation
cov_report:
	@if [ "$(COV)" = "1" ] && [ -d "$(COV_DIR)/xcelium_cov" ]; then \\
		echo "Generating Xcelium coverage report..."; \\
		if command -v imc >/dev/null 2>&1; then \\
			imc -load $(COV_DIR)/xcelium_cov -execcmd "report -html $(COV_DIR)/xcelium_coverage_report"; \\
			echo "Coverage report available at: $(COV_DIR)/xcelium_coverage_report/index.html"; \\
		else \\
			echo "Warning: IMC not found. Cannot generate coverage report."; \\
		fi \\
	elif [ "$(COV)" != "1" ]; then \\
		echo "Coverage not enabled. Use COV=1 to enable coverage collection."; \\
	else \\
		echo "Coverage database not found. Run simulation with COV=1 first."; \\
	fi

# Create shm.tcl file for waveform dumping
shm.tcl:
	@echo "Creating shm.tcl for waveform dumping..."
	@echo "database -open -shm waves -into waves.shm -default" > shm.tcl
	@echo "probe -create -database waves -all -memories -variables -packed 8192 -unpacked 8192" >> shm.tcl
	@echo "run" >> shm.tcl
	@echo "quit" >> shm.tcl

# Setup results directory
$(RESULTS_DIR):
	@mkdir -p $(RESULTS_DIR)

#===========================================
# DEBUG TARGETS
#===========================================

# Debug target - launch SimVision with waveforms
debug:
	@if command -v simvision >/dev/null 2>&1 && [ -f "waves.shm" ]; then \\
		echo "Launching SimVision..."; \\
		simvision waves.shm & \\
	elif [ ! -f "waves.shm" ]; then \\
		echo "Error: Waveform file not found. Run simulation with WAVES=1 first."; \\
	else \\
		echo "Warning: SimVision not found. Please ensure SimVision is installed and in your PATH."; \\
	fi

# GUI target - same as debug for Xcelium
gui: debug
'''

    def _get_questa_makefile_template(self) -> str:
        """Return template content for Questa Makefile"""
        return '''# Questa-Specific Makefile - ExpFifo
# Generated by Verification Structure Generator

#===========================================
# COMMON SIMULATION VARIABLES
#===========================================

# Default test
TEST ?= fifo_base_test

# Default verbosity
VERBOSITY ?= UVM_MEDIUM

# Default seed
SEED ?= 1

# File paths (relative to sim directory)
FILELIST = ../filelist.f
TB_TOP = fifo_tb_top

# Results directory
RESULTS_DIR = ../results/questa
LOG_FILE = $(RESULTS_DIR)/questa_$(TEST)_$(SEED).log

# Common simulation arguments
COMMON_ARGS = +UVM_TESTNAME=$(TEST) +UVM_VERBOSITY=$(VERBOSITY) +ntb_random_seed=$(SEED)

# Coverage options
COV_DIR = $(RESULTS_DIR)/coverage

# Enable waveforms (0=off, 1=on)
WAVES ?= 0

# Enable coverage (0=off, 1=on)
COV ?= 0

# Waveform options
WAVE_ARGS = +DUMP_VCD

#===========================================
# QUESTA VARIABLES AND OPTIONS
#===========================================

QUESTA_VLOG = vlog
QUESTA_VSIM = vsim

# UVM Home detection - tries environment variable first, then common paths
UVM_HOME ?= $(shell \\
	if [ -n "$$QUESTA_UVM_HOME" ]; then \\
		echo "$$QUESTA_UVM_HOME"; \\
	elif [ -n "$$QUESTASIM_HOME" ]; then \\
		echo "$$QUESTASIM_HOME/verilog_src/uvm-1.2"; \\
	elif [ -n "$$MTI_HOME" ]; then \\
		echo "$$MTI_HOME/verilog_src/uvm-1.2"; \\
	elif command -v vsim >/dev/null 2>&1; then \\
		vsim_path=$$(which vsim); \\
		vsim_dir=$$(dirname $$vsim_path); \\
		if [ -d "$$vsim_dir/../share/modeltech/verilog_src/uvm-1.2" ]; then \\
			echo "$$vsim_dir/../share/modeltech/verilog_src/uvm-1.2"; \\
		elif [ -d "$$vsim_dir/../verilog_src/uvm-1.2" ]; then \\
			echo "$$vsim_dir/../verilog_src/uvm-1.2"; \\
		else \\
			echo ""; \\
		fi \\
	else \\
		echo ""; \\
	fi)

QUESTA_COMP_OPTS = -sv -timescale=1ns/1ps -64 $(if $(UVM_HOME),+incdir+$(UVM_HOME)/src,) -L mtiUvm +define+QUESTA
QUESTA_SIM_OPTS = -64 -c -do "run -all; quit -f" +UVM_NO_RELNOTES -L mtiUvm

# Add waveform and coverage flags conditionally
ifeq ($(WAVES),1)
    QUESTA_SIM_OPTS += -wlf waves.wlf
    WAVE_DB = waves.wlf
endif

ifeq ($(COV),1)
    QUESTA_COMP_OPTS += +cover=bcesfx -coveropt 3
    QUESTA_SIM_OPTS += -coverage -coverstore $(COV_DIR)/questa_cov
endif

# Work library
WORK_LIB = work

#===========================================
# QUESTA TARGETS
#===========================================

.PHONY: all compile sim run clean clean_all cov_report help gui debug

# Default target
all: run

# Help target
help:
	@echo "Questa Simulation Makefile - ExpFifo"
	@echo "====================================="
	@echo "Available targets:"
	@echo "  help       - Show this help message"
	@echo "  all/run    - Compile and run simulation"
	@echo "  compile    - Compile only"
	@echo "  sim        - Run simulation (requires compilation first)"
	@echo "  gui        - Run interactive GUI simulation"
	@echo "  debug      - Launch QuestaSim with waveforms"
	@echo "  clean      - Clean build artifacts"
	@echo "  clean_all  - Clean all including results directory"
	@echo "  cov_report - Generate coverage report"
	@echo ""
	@echo "VARIABLES:"
	@echo "  TEST       - Test name (default: $(TEST))"
	@echo "  VERBOSITY  - UVM verbosity (default: $(VERBOSITY))"
	@echo "  SEED       - Random seed (default: $(SEED))"
	@echo "  WAVES      - Enable waveforms: 1|0 (default: 0)"
	@echo "  COV        - Enable coverage: 1|0 (default: 0)"
	@echo ""
	@echo "ENVIRONMENT VARIABLES (for UVM path detection):"
	@echo "  QUESTA_UVM_HOME - Direct path to UVM installation"
	@echo "  QUESTASIM_HOME  - QuestaSim installation directory"
	@echo "  MTI_HOME        - ModelSim/Questa installation directory"
	@echo ""
	@echo "Available tests:"
	@echo "  fifo_base_test, fifo_basic_test, fifo_fill_test,"
	@echo "  fifo_simultaneous_test, fifo_random_test, fifo_wraparound_test,"
	@echo "  fifo_reset_test, fifo_enable_edge_test, fifo_comprehensive_test"
	@echo ""
	@echo "EXAMPLES:"
	@echo "  make run TEST=fifo_random_test SEED=42"
	@echo "  make run TEST=fifo_comprehensive_test WAVES=1"
	@echo "  make run COV=1 VERBOSITY=UVM_HIGH"
	@echo "  make gui WAVES=1  # Interactive simulation"
	@echo "  make debug        # After running with WAVES=1"

# Complete flow: compile and run
run: $(RESULTS_DIR) compile sim

# Compile target  
compile: $(RESULTS_DIR) setup_lib
	@echo "==============================================="
	@echo "Compiling ExpFifo with Questa..."
	@echo "==============================================="
	@if command -v vlog >/dev/null 2>&1; then \\
		if [ -z "$(UVM_HOME)" ]; then \\
			echo "Error: UVM_HOME not detected. Please set QUESTA_UVM_HOME, QUESTASIM_HOME, or MTI_HOME environment variable."; \\
			echo "Or ensure UVM is in a standard location relative to your Questa installation."; \\
			exit 1; \\
		fi; \\
		echo "Using UVM from: $(UVM_HOME)"; \\
		vlog $(QUESTA_COMP_OPTS) \\
			$(UVM_HOME)/src/uvm_pkg.sv \\
			-work $(WORK_LIB) \\
			-l $(RESULTS_DIR)/questa_compile.log; \\
		cd ../.. && vlog $(QUESTA_COMP_OPTS) -f filelist.f \\
			-work sim/questa/$(WORK_LIB) \\
			-l sim/$(RESULTS_DIR)/questa_compile.log; \\
		echo "Compilation completed. Check $(RESULTS_DIR)/questa_compile.log for details."; \\
	else \\
		echo "Error: Questa (vlog) not found. Please ensure QuestaSim is installed and in your PATH."; \\
		exit 1; \\
	fi

# Simulation target
sim:
	@echo "==============================================="
	@echo "Running Questa simulation..."
	@echo "Test: $(TEST), Seed: $(SEED)" 
	@echo "==============================================="
	@if command -v vsim >/dev/null 2>&1; then \\
		vsim $(QUESTA_SIM_OPTS) -lib $(WORK_LIB) $(TB_TOP) $(COMMON_ARGS) \\
			$(if $(findstring 1,$(WAVES)),-wlf waves.wlf,) \\
			$(if $(findstring 1,$(COV)),-coverage -coverstore $(COV_DIR)/questa_cov,) \\
			-l $(LOG_FILE); \\
		echo "Simulation completed. Check $(LOG_FILE) for results."; \\
	else \\
		echo "Error: Questa (vsim) not found. Please ensure QuestaSim is installed and in your PATH."; \\
		exit 1; \\
	fi

# Interactive simulation target
gui: $(RESULTS_DIR) setup_lib
	@echo "==============================================="
	@echo "Running Questa GUI simulation..."
	@echo "Test: $(TEST), Seed: $(SEED)" 
	@echo "==============================================="
	@if command -v vsim >/dev/null 2>&1; then \\
		vsim -gui $(TB_TOP) $(COMMON_ARGS) \\
			$(if $(findstring 1,$(WAVES)),-wlf waves.wlf,) \\
			$(if $(findstring 1,$(COV)),-coverage -coverstore $(COV_DIR)/questa_cov,) \\
			-l $(LOG_FILE); \\
	else \\
		echo "Error: Questa (vsim) not found. Please ensure QuestaSim is installed and in your PATH."; \\
		exit 1; \\
	fi

# Clean target
clean:
	@echo "Cleaning Questa build artifacts..."
	@rm -rf *.log $(WORK_LIB) transcript *.wlf *.vstf
	@rm -rf modelsim.ini wlft* wlf*
	@rm -rf *.vcd *.fsdb novas.conf novas.rc
	@echo "Questa clean completed."

# Clean all (including results directory)
clean_all: clean
	rm -rf $(RESULTS_DIR)

# Coverage report generation
cov_report:
	@if [ "$(COV)" = "1" ] && [ -d "$(COV_DIR)/questa_cov" ]; then \\
		echo "Generating Questa coverage report..."; \\
		if command -v vcover >/dev/null 2>&1; then \\
			vcover report -html -htmldir $(COV_DIR)/questa_coverage_report $(COV_DIR)/questa_cov; \\
			echo "Coverage report available at: $(COV_DIR)/questa_coverage_report/index.html"; \\
		else \\
			echo "Warning: vcover not found. Cannot generate coverage report."; \\
		fi \\
	elif [ "$(COV)" != "1" ]; then \\
		echo "Coverage not enabled. Use COV=1 to enable coverage collection."; \\
	else \\
		echo "Coverage database not found. Run simulation with COV=1 first."; \\
	fi

# Setup work library
setup_lib:
	@if [ ! -d "$(WORK_LIB)" ]; then \\
		echo "Creating work library..."; \\
		if command -v vlib >/dev/null 2>&1; then \\
			vlib $(WORK_LIB); \\
			vmap work $(WORK_LIB); \\
		else \\
			echo "Error: Questa tools not found. Please ensure QuestaSim is installed and in your PATH."; \\
			exit 1; \\
		fi \\
	fi

# Setup results directory
$(RESULTS_DIR):
	@mkdir -p $(RESULTS_DIR)

#===========================================
# DEBUG TARGETS
#===========================================

# Debug target - launch QuestaSim with waveforms
debug:
	@if command -v vsim >/dev/null 2>&1 && [ -f "waves.wlf" ]; then \\
		echo "Launching QuestaSim with waveforms..."; \\
		vsim -view waves.wlf & \\
	elif [ ! -f "waves.wlf" ]; then \\
		echo "Error: Waveform file not found. Run simulation with WAVES=1 first."; \\
	else \\
		echo "Warning: QuestaSim not found. Please ensure QuestaSim is installed and in your PATH."; \\
	fi
'''

    def _get_filelist_template(self) -> str:
        """Return template content for filelist.f"""
        return '''# File list for RTL compilation
# Generated by CAD Verification Structure Generator

# Include directories
+incdir+./include
+incdir+../include

# Source files
# Add your RTL source files here
# Example:
# ./src/module_name.sv
# ./src/interface_name.sv

# Library files
# Add library files if needed
# -v /path/to/library.v

# Define macros if needed
# +define+MACRO_NAME=value
'''
    
    def create_directory_structure(self, base_path: Path, dirs: List[str]) -> None:
        """
        Create directory structure.
        
        Args:
            base_path: Base path where directories will be created
            dirs: List of directory paths to create
        """
        for dir_path in dirs:
            full_path = base_path / dir_path
            try:
                full_path.mkdir(parents=True, exist_ok=True)
                if str(full_path) not in self.created_dirs:
                    self.created_dirs.append(str(full_path))
                    print(f"  ✓ Created directory: {full_path}")
            except Exception as e:
                self.skipped_items.append(str(full_path))
                print(f"  ⚠ Skipped directory: {full_path} (Reason: {e})")
    
    def move_existing_files_to_sim(self, base_path: Path) -> None:
        """
        Move existing Makefile and run_test.py files to sim directory.
        
        Args:
            base_path: Base path where files might exist
        """
        files_to_move = ['Makefile', 'run_test.py']
        sim_path = base_path / 'sim'
        
        for filename in files_to_move:
            source_path = base_path / filename
            target_path = sim_path / filename
            
            if source_path.exists():
                try:
                    # Ensure sim directory exists
                    sim_path.mkdir(parents=True, exist_ok=True)
                    
                    # Move the file
                    shutil.move(str(source_path), str(target_path))
                    print(f"  ✓ Moved {filename} from {base_path} to {sim_path}")
                    
                except Exception as e:
                    self.skipped_items.append(str(source_path))
                    print(f"  ⚠ Failed to move {filename}: {e}")
    
    def create_files(self, base_path: Path) -> None:
        """
        Create files with template content.
        
        Args:
            base_path: Base path where files will be created
        """
        for file_path, content in self.files_to_create:
            full_path = base_path / file_path
            try:
                # Ensure parent directory exists
                full_path.parent.mkdir(parents=True, exist_ok=True)
                
                # Create file if it doesn't exist
                if not full_path.exists():
                    with open(full_path, 'w') as f:
                        f.write(content)
                    
                    # Make Python files executable
                    if file_path.endswith('.py'):
                        os.chmod(full_path, 0o755)
                    
                    self.created_files.append(str(full_path))
                    print(f"  ✓ Created file: {full_path}")
                else:
                    self.skipped_items.append(str(full_path))
                    print(f"  ⚠ File already exists: {full_path}")
            except Exception as e:
                self.skipped_items.append(str(full_path))
                print(f"  ⚠ Failed to create file: {full_path} (Reason: {e})")
    
    def _create_structure_for_level(self, level_name: str, base_dir_name: str, 
                                   names: List[str], dirs: List[str], 
                                   item_type: str) -> None:
        """
        Generic method to create verification structure for any level.
        
        Args:
            level_name: Display name for the level (e.g., "UNIT LEVEL")
            base_dir_name: Base directory name (e.g., "UnitVerif")
            names: List of names to create structures for
            dirs: Directory list to use
            item_type: Type of item being created (e.g., "unit module")
        """
        if not names:
            return
        
        print("\n" + "="*60)
        print(f"Creating {level_name} verification structures")
        print("="*60)
        
        # Create verification folder structure
        verification_base = Path("verification")
        base_dir = verification_base / base_dir_name
        
        for name in names:
            print(f"\n→ Creating structure for {item_type}: '{name}'")
            item_path = base_dir / name
            
            # Create directories
            self.create_directory_structure(item_path, dirs)
            
            # Move existing files to sim folder
            self.move_existing_files_to_sim(item_path)
            
            # Create files
            self.create_files(item_path)
        
        # Create parallel RTL directory structure
        self._create_rtl_structure_for_level(level_name, base_dir_name, names, item_type)
    
    def _create_rtl_structure_for_level(self, level_name: str, base_dir_name: str,
                                       names: List[str], item_type: str) -> None:
        """
        Create RTL directory structure parallel to verification structure.
        
        Args:
            level_name: Display name for the level (e.g., "UNIT LEVEL")
            base_dir_name: Base directory name (e.g., "UnitVerif")
            names: List of names to create structures for
            item_type: Type of item being created (e.g., "unit module")
        """
        print("\n" + "="*60)
        print(f"Creating {level_name} RTL structures")
        print("="*60)
        
        # Create RTL folder structure parallel to verification
        rtl_base = Path("rtl")
        
        # Map verification directory names to RTL directory names
        rtl_dir_mapping = {
            "UnitVerif": "UnitRtl",
            "SubSystemVerif": "SubSystemRtl", 
            "SysVerif": "SysVerifRtl"
        }
        
        rtl_dir_name = rtl_dir_mapping.get(base_dir_name, base_dir_name)
        base_dir = rtl_base / rtl_dir_name
        
        for name in names:
            print(f"\n→ Creating RTL structure for {item_type}: '{name}'")
            item_path = base_dir / name
            
            # Create basic RTL directories (simpler than verification structure)
            rtl_dirs = ['src', 'include', 'tb', 'docs']
            self.create_directory_structure(item_path, rtl_dirs)
            
            # Create filelist.f file
            filelist_path = item_path / 'filelist.f'
            try:
                if not filelist_path.exists():
                    with open(filelist_path, 'w') as f:
                        f.write(self._get_filelist_template())
                    self.created_files.append(str(filelist_path))
                    print(f"  ✓ Created file: {filelist_path}")
                else:
                    self.skipped_items.append(str(filelist_path))
                    print(f"  ⚠ File already exists: {filelist_path}")
            except Exception as e:
                self.skipped_items.append(str(filelist_path))
                print(f"  ⚠ Failed to create file: {filelist_path} (Reason: {e})")
    
    def create_unit_structure(self, module_names: List[str]) -> None:
        """Create unit level verification structure."""
        self._create_structure_for_level(
            "UNIT LEVEL", "UnitVerif", module_names, 
            self.unit_subsystem_dirs, "unit module"
        )
    
    def create_subsystem_structure(self, subsystem_names: List[str]) -> None:
        """Create subsystem level verification structure."""
        self._create_structure_for_level(
            "SUBSYSTEM LEVEL", "SubSystemVerif", subsystem_names,
            self.unit_subsystem_dirs, "subsystem"
        )
    
    def create_system_structure(self, system_name: str) -> None:
        """Create system level verification structure."""
        if system_name:
            self._create_structure_for_level(
                "SYSTEM LEVEL", "SysVerif", [system_name],
                self.system_dirs, "system"
            )
    
    def print_summary(self) -> None:
        """Print summary of created items."""
        print("\n" + "="*60)
        print("SUMMARY")
        print("="*60)
        
        print(f"\n📁 Directories created: {len(self.created_dirs)}")
        print(f"📄 Files created: {len(self.created_files)}")
        print(f"⚠  Items skipped: {len(self.skipped_items)}")
        
        total_items = len(self.created_dirs) + len(self.created_files)
        if total_items > 0:
            print(f"\n✅ Successfully created {total_items} items!")
        else:
            print("\n⚠ No new items were created (all may already exist).")


def parse_arguments() -> argparse.Namespace:
    """
    Parse command-line arguments.
    
    Returns:
        Parsed arguments namespace
    """
    parser = argparse.ArgumentParser(
        description="CAD Verification Directory Structure Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Create unit modules only (creates verification/UnitVerif/*)
  %(prog)s --unit_module_name uart spi i2c
  
  # Create subsystems only (creates verification/SubSystemVerif/*)
  %(prog)s --subsystem_name audio video
  
  # Create system only (creates verification/SysVerif/*)
  %(prog)s --system_name soc
  
  # Create all levels at once
  %(prog)s --unit_module_name uart spi --subsystem_name audio --system_name soc
        """
    )
    
    parser.add_argument(
        '--unit_module_name',
        nargs='+',
        metavar='MODULE',
        help='Unit module name(s) to create structure for'
    )
    
    parser.add_argument(
        '--subsystem_name',
        nargs='+',
        metavar='SUBSYSTEM',
        help='Subsystem name(s) to create structure for'
    )
    
    parser.add_argument(
        '--system_name',
        metavar='SYSTEM',
        help='System name to create structure for (single system only)'
    )
    
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Enable verbose output'
    )
    
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be created without actually creating anything'
    )
    
    return parser.parse_args()


def validate_arguments(args: argparse.Namespace) -> bool:
    """
    Validate command-line arguments.
    
    Args:
        args: Parsed arguments
    
    Returns:
        True if arguments are valid, False otherwise
    """
    # Check if at least one level is specified
    if not any([args.unit_module_name, args.subsystem_name, args.system_name]):
        print("Error: At least one of --unit_module_name, --subsystem_name, or --system_name must be specified.")
        return False
    
    # Validate names (basic check for valid directory names)
    all_names = []
    if args.unit_module_name:
        all_names.extend(args.unit_module_name)
    if args.subsystem_name:
        all_names.extend(args.subsystem_name)
    if args.system_name:
        all_names.append(args.system_name)
    
    invalid_chars = ['/', '\\', ':', '*', '?', '"', '<', '>', '|']
    for name in all_names:
        if any(char in name for char in invalid_chars):
            print(f"Error: Invalid character in name '{name}'. Names cannot contain: {', '.join(invalid_chars)}")
            return False
    
    return True


def main():
    """Main entry point for the script."""
    print("\n" + "="*60)
    print("CAD VERIFICATION DIRECTORY STRUCTURE GENERATOR")
    print("="*60)
    
    # Parse arguments
    args = parse_arguments()
    
    # Validate arguments
    if not validate_arguments(args):
        sys.exit(1)
    
    # Handle dry-run mode
    if args.dry_run:
        print("\n⚠ DRY-RUN MODE: No files or directories will be created.")
        print("\nWould create the following structures:")
        
        if args.unit_module_name:
            print(f"\n• Unit modules: {', '.join(args.unit_module_name)}")
        if args.subsystem_name:
            print(f"• Subsystems: {', '.join(args.subsystem_name)}")
        if args.system_name:
            print(f"• System: {args.system_name}")
        
        print("\nRun without --dry-run to actually create the structures.")
        sys.exit(0)
    
    # Create generator instance
    generator = CADVerificationStructureGenerator()
    
    try:
        # Create structures based on arguments
        if args.unit_module_name:
            generator.create_unit_structure(args.unit_module_name)
        
        if args.subsystem_name:
            generator.create_subsystem_structure(args.subsystem_name)
        
        if args.system_name:
            generator.create_system_structure(args.system_name)
        
        # Print summary
        generator.print_summary()
        
    except KeyboardInterrupt:
        print("\n\n⚠ Operation cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)
    
    print("\n" + "="*60)
    print("Operation completed successfully!")
    print("="*60 + "\n")


if __name__ == "__main__":
    main()
