# File list for RTL compilation
# Generated by CAD Verification Structure Generator

# Include directories
+incdir+./include
+incdir+../include

# Source files
# Add your RTL source files here
# Example:
# ./src/module_name.sv
# ./src/interface_name.sv

# Library files
# Add library files if needed
# -v /path/to/library.v

# Define macros if needed
# +define+MACRO_NAME=value
