# Filelist for rp_top
# Generated: 2026-04-04T18:30:20.232319

./src/adc_clk_ctrl_reg_block.v
./src/adc_clk_ctrl_reg_block_pkg_uvm.sv
./src/apb_bridge.v
./src/rp_adc_chop_gen.sv
./src/rp_adc_clk_ctrl_top.sv
./src/adc_postproc_reg_block.v
./src/adc_postproc_reg_block_pkg_uvm.sv
./src/rp_adc_postproc_averager.sv
./src/rp_adc_postproc_decimator.sv
./src/rp_adc_postproc_outputs.sv
./src/rp_adc_postproc_top.sv
./src/analog_config_reg_block.v
./src/analog_config_reg_block_pkg_uvm.sv
./src/rp_analog_config_top.sv
./src/arbiter_reg_block.v
./src/arbiter_reg_block_pkg_uvm.sv
./src/rp_arbiter.sv
./src/rp_arbiter_top.sv
./src/rp_clk_div_pos.v
./src/rp_clk_div_pos_no_sync.sv
./src/rp_ram_dual.v
./src/rp_sat_counter.sv
./src/rp_synch_pulse.v
./src/rp_synch_rst.v
./src/rp_synch_sim.v
./src/fifo_reg_block.v
./src/fifo_reg_block_pkg_uvm.sv
./src/rp_fifo_core.sv
./src/rp_fifo_mem_wrapper.sv
./src/rp_fifo_top.sv
./src/rp_host_bus_interconnect.sv
./src/host_if.sv
./src/interrupt_gen_reg_block.v
./src/interrupt_gen_reg_block_pkg_uvm.sv
./src/rp_interrupt_gen_top.sv
./src/local_reg_block.v
./src/local_reg_block_pkg_uvm.sv
./src/rp_local_top.sv
./src/rp_opa_wfm_gen_dp.sv
./src/rp_opa_wfm_gen_top.sv
./src/sequencer_reg_block.v
./src/sequencer_reg_block_pkg_uvm.sv
./src/rp_ram_single.sv
./src/rp_sequencer.sv
./src/rp_sequencer_mem_wrapper.sv
./src/rp_sequencer_mux.sv
./src/rp_sequencer_pkg.sv
./src/rp_sequencer_top.sv
./src/rp_spi_slave.sv
./src/test_mux_reg_block.v
./src/test_mux_reg_block_pkg_uvm.sv
./src/rp_test_mux.sv
./src/rp_test_mux_top.sv
./src/tia_offset_cancel_reg_block.v
./src/tia_offset_cancel_reg_block_pkg_uvm.sv
./src/rp_tia_offset_cancel_top.sv
./src/rp_top_top.sv
./src/rp_top_top_pkg.sv
