
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point ld ld -type PI PI
add mapped point key[127] key[127] -type PI PI
add mapped point key[126] key[126] -type PI PI
add mapped point key[125] key[125] -type PI PI
add mapped point key[124] key[124] -type PI PI
add mapped point key[123] key[123] -type PI PI
add mapped point key[122] key[122] -type PI PI
add mapped point key[121] key[121] -type PI PI
add mapped point key[120] key[120] -type PI PI
add mapped point key[119] key[119] -type PI PI
add mapped point key[118] key[118] -type PI PI
add mapped point key[117] key[117] -type PI PI
add mapped point key[116] key[116] -type PI PI
add mapped point key[115] key[115] -type PI PI
add mapped point key[114] key[114] -type PI PI
add mapped point key[113] key[113] -type PI PI
add mapped point key[112] key[112] -type PI PI
add mapped point key[111] key[111] -type PI PI
add mapped point key[110] key[110] -type PI PI
add mapped point key[109] key[109] -type PI PI
add mapped point key[108] key[108] -type PI PI
add mapped point key[107] key[107] -type PI PI
add mapped point key[106] key[106] -type PI PI
add mapped point key[105] key[105] -type PI PI
add mapped point key[104] key[104] -type PI PI
add mapped point key[103] key[103] -type PI PI
add mapped point key[102] key[102] -type PI PI
add mapped point key[101] key[101] -type PI PI
add mapped point key[100] key[100] -type PI PI
add mapped point key[99] key[99] -type PI PI
add mapped point key[98] key[98] -type PI PI
add mapped point key[97] key[97] -type PI PI
add mapped point key[96] key[96] -type PI PI
add mapped point key[95] key[95] -type PI PI
add mapped point key[94] key[94] -type PI PI
add mapped point key[93] key[93] -type PI PI
add mapped point key[92] key[92] -type PI PI
add mapped point key[91] key[91] -type PI PI
add mapped point key[90] key[90] -type PI PI
add mapped point key[89] key[89] -type PI PI
add mapped point key[88] key[88] -type PI PI
add mapped point key[87] key[87] -type PI PI
add mapped point key[86] key[86] -type PI PI
add mapped point key[85] key[85] -type PI PI
add mapped point key[84] key[84] -type PI PI
add mapped point key[83] key[83] -type PI PI
add mapped point key[82] key[82] -type PI PI
add mapped point key[81] key[81] -type PI PI
add mapped point key[80] key[80] -type PI PI
add mapped point key[79] key[79] -type PI PI
add mapped point key[78] key[78] -type PI PI
add mapped point key[77] key[77] -type PI PI
add mapped point key[76] key[76] -type PI PI
add mapped point key[75] key[75] -type PI PI
add mapped point key[74] key[74] -type PI PI
add mapped point key[73] key[73] -type PI PI
add mapped point key[72] key[72] -type PI PI
add mapped point key[71] key[71] -type PI PI
add mapped point key[70] key[70] -type PI PI
add mapped point key[69] key[69] -type PI PI
add mapped point key[68] key[68] -type PI PI
add mapped point key[67] key[67] -type PI PI
add mapped point key[66] key[66] -type PI PI
add mapped point key[65] key[65] -type PI PI
add mapped point key[64] key[64] -type PI PI
add mapped point key[63] key[63] -type PI PI
add mapped point key[62] key[62] -type PI PI
add mapped point key[61] key[61] -type PI PI
add mapped point key[60] key[60] -type PI PI
add mapped point key[59] key[59] -type PI PI
add mapped point key[58] key[58] -type PI PI
add mapped point key[57] key[57] -type PI PI
add mapped point key[56] key[56] -type PI PI
add mapped point key[55] key[55] -type PI PI
add mapped point key[54] key[54] -type PI PI
add mapped point key[53] key[53] -type PI PI
add mapped point key[52] key[52] -type PI PI
add mapped point key[51] key[51] -type PI PI
add mapped point key[50] key[50] -type PI PI
add mapped point key[49] key[49] -type PI PI
add mapped point key[48] key[48] -type PI PI
add mapped point key[47] key[47] -type PI PI
add mapped point key[46] key[46] -type PI PI
add mapped point key[45] key[45] -type PI PI
add mapped point key[44] key[44] -type PI PI
add mapped point key[43] key[43] -type PI PI
add mapped point key[42] key[42] -type PI PI
add mapped point key[41] key[41] -type PI PI
add mapped point key[40] key[40] -type PI PI
add mapped point key[39] key[39] -type PI PI
add mapped point key[38] key[38] -type PI PI
add mapped point key[37] key[37] -type PI PI
add mapped point key[36] key[36] -type PI PI
add mapped point key[35] key[35] -type PI PI
add mapped point key[34] key[34] -type PI PI
add mapped point key[33] key[33] -type PI PI
add mapped point key[32] key[32] -type PI PI
add mapped point key[31] key[31] -type PI PI
add mapped point key[30] key[30] -type PI PI
add mapped point key[29] key[29] -type PI PI
add mapped point key[28] key[28] -type PI PI
add mapped point key[27] key[27] -type PI PI
add mapped point key[26] key[26] -type PI PI
add mapped point key[25] key[25] -type PI PI
add mapped point key[24] key[24] -type PI PI
add mapped point key[23] key[23] -type PI PI
add mapped point key[22] key[22] -type PI PI
add mapped point key[21] key[21] -type PI PI
add mapped point key[20] key[20] -type PI PI
add mapped point key[19] key[19] -type PI PI
add mapped point key[18] key[18] -type PI PI
add mapped point key[17] key[17] -type PI PI
add mapped point key[16] key[16] -type PI PI
add mapped point key[15] key[15] -type PI PI
add mapped point key[14] key[14] -type PI PI
add mapped point key[13] key[13] -type PI PI
add mapped point key[12] key[12] -type PI PI
add mapped point key[11] key[11] -type PI PI
add mapped point key[10] key[10] -type PI PI
add mapped point key[9] key[9] -type PI PI
add mapped point key[8] key[8] -type PI PI
add mapped point key[7] key[7] -type PI PI
add mapped point key[6] key[6] -type PI PI
add mapped point key[5] key[5] -type PI PI
add mapped point key[4] key[4] -type PI PI
add mapped point key[3] key[3] -type PI PI
add mapped point key[2] key[2] -type PI PI
add mapped point key[1] key[1] -type PI PI
add mapped point key[0] key[0] -type PI PI
add mapped point text_in[127] text_in[127] -type PI PI
add mapped point text_in[126] text_in[126] -type PI PI
add mapped point text_in[125] text_in[125] -type PI PI
add mapped point text_in[124] text_in[124] -type PI PI
add mapped point text_in[123] text_in[123] -type PI PI
add mapped point text_in[122] text_in[122] -type PI PI
add mapped point text_in[121] text_in[121] -type PI PI
add mapped point text_in[120] text_in[120] -type PI PI
add mapped point text_in[119] text_in[119] -type PI PI
add mapped point text_in[118] text_in[118] -type PI PI
add mapped point text_in[117] text_in[117] -type PI PI
add mapped point text_in[116] text_in[116] -type PI PI
add mapped point text_in[115] text_in[115] -type PI PI
add mapped point text_in[114] text_in[114] -type PI PI
add mapped point text_in[113] text_in[113] -type PI PI
add mapped point text_in[112] text_in[112] -type PI PI
add mapped point text_in[111] text_in[111] -type PI PI
add mapped point text_in[110] text_in[110] -type PI PI
add mapped point text_in[109] text_in[109] -type PI PI
add mapped point text_in[108] text_in[108] -type PI PI
add mapped point text_in[107] text_in[107] -type PI PI
add mapped point text_in[106] text_in[106] -type PI PI
add mapped point text_in[105] text_in[105] -type PI PI
add mapped point text_in[104] text_in[104] -type PI PI
add mapped point text_in[103] text_in[103] -type PI PI
add mapped point text_in[102] text_in[102] -type PI PI
add mapped point text_in[101] text_in[101] -type PI PI
add mapped point text_in[100] text_in[100] -type PI PI
add mapped point text_in[99] text_in[99] -type PI PI
add mapped point text_in[98] text_in[98] -type PI PI
add mapped point text_in[97] text_in[97] -type PI PI
add mapped point text_in[96] text_in[96] -type PI PI
add mapped point text_in[95] text_in[95] -type PI PI
add mapped point text_in[94] text_in[94] -type PI PI
add mapped point text_in[93] text_in[93] -type PI PI
add mapped point text_in[92] text_in[92] -type PI PI
add mapped point text_in[91] text_in[91] -type PI PI
add mapped point text_in[90] text_in[90] -type PI PI
add mapped point text_in[89] text_in[89] -type PI PI
add mapped point text_in[88] text_in[88] -type PI PI
add mapped point text_in[87] text_in[87] -type PI PI
add mapped point text_in[86] text_in[86] -type PI PI
add mapped point text_in[85] text_in[85] -type PI PI
add mapped point text_in[84] text_in[84] -type PI PI
add mapped point text_in[83] text_in[83] -type PI PI
add mapped point text_in[82] text_in[82] -type PI PI
add mapped point text_in[81] text_in[81] -type PI PI
add mapped point text_in[80] text_in[80] -type PI PI
add mapped point text_in[79] text_in[79] -type PI PI
add mapped point text_in[78] text_in[78] -type PI PI
add mapped point text_in[77] text_in[77] -type PI PI
add mapped point text_in[76] text_in[76] -type PI PI
add mapped point text_in[75] text_in[75] -type PI PI
add mapped point text_in[74] text_in[74] -type PI PI
add mapped point text_in[73] text_in[73] -type PI PI
add mapped point text_in[72] text_in[72] -type PI PI
add mapped point text_in[71] text_in[71] -type PI PI
add mapped point text_in[70] text_in[70] -type PI PI
add mapped point text_in[69] text_in[69] -type PI PI
add mapped point text_in[68] text_in[68] -type PI PI
add mapped point text_in[67] text_in[67] -type PI PI
add mapped point text_in[66] text_in[66] -type PI PI
add mapped point text_in[65] text_in[65] -type PI PI
add mapped point text_in[64] text_in[64] -type PI PI
add mapped point text_in[63] text_in[63] -type PI PI
add mapped point text_in[62] text_in[62] -type PI PI
add mapped point text_in[61] text_in[61] -type PI PI
add mapped point text_in[60] text_in[60] -type PI PI
add mapped point text_in[59] text_in[59] -type PI PI
add mapped point text_in[58] text_in[58] -type PI PI
add mapped point text_in[57] text_in[57] -type PI PI
add mapped point text_in[56] text_in[56] -type PI PI
add mapped point text_in[55] text_in[55] -type PI PI
add mapped point text_in[54] text_in[54] -type PI PI
add mapped point text_in[53] text_in[53] -type PI PI
add mapped point text_in[52] text_in[52] -type PI PI
add mapped point text_in[51] text_in[51] -type PI PI
add mapped point text_in[50] text_in[50] -type PI PI
add mapped point text_in[49] text_in[49] -type PI PI
add mapped point text_in[48] text_in[48] -type PI PI
add mapped point text_in[47] text_in[47] -type PI PI
add mapped point text_in[46] text_in[46] -type PI PI
add mapped point text_in[45] text_in[45] -type PI PI
add mapped point text_in[44] text_in[44] -type PI PI
add mapped point text_in[43] text_in[43] -type PI PI
add mapped point text_in[42] text_in[42] -type PI PI
add mapped point text_in[41] text_in[41] -type PI PI
add mapped point text_in[40] text_in[40] -type PI PI
add mapped point text_in[39] text_in[39] -type PI PI
add mapped point text_in[38] text_in[38] -type PI PI
add mapped point text_in[37] text_in[37] -type PI PI
add mapped point text_in[36] text_in[36] -type PI PI
add mapped point text_in[35] text_in[35] -type PI PI
add mapped point text_in[34] text_in[34] -type PI PI
add mapped point text_in[33] text_in[33] -type PI PI
add mapped point text_in[32] text_in[32] -type PI PI
add mapped point text_in[31] text_in[31] -type PI PI
add mapped point text_in[30] text_in[30] -type PI PI
add mapped point text_in[29] text_in[29] -type PI PI
add mapped point text_in[28] text_in[28] -type PI PI
add mapped point text_in[27] text_in[27] -type PI PI
add mapped point text_in[26] text_in[26] -type PI PI
add mapped point text_in[25] text_in[25] -type PI PI
add mapped point text_in[24] text_in[24] -type PI PI
add mapped point text_in[23] text_in[23] -type PI PI
add mapped point text_in[22] text_in[22] -type PI PI
add mapped point text_in[21] text_in[21] -type PI PI
add mapped point text_in[20] text_in[20] -type PI PI
add mapped point text_in[19] text_in[19] -type PI PI
add mapped point text_in[18] text_in[18] -type PI PI
add mapped point text_in[17] text_in[17] -type PI PI
add mapped point text_in[16] text_in[16] -type PI PI
add mapped point text_in[15] text_in[15] -type PI PI
add mapped point text_in[14] text_in[14] -type PI PI
add mapped point text_in[13] text_in[13] -type PI PI
add mapped point text_in[12] text_in[12] -type PI PI
add mapped point text_in[11] text_in[11] -type PI PI
add mapped point text_in[10] text_in[10] -type PI PI
add mapped point text_in[9] text_in[9] -type PI PI
add mapped point text_in[8] text_in[8] -type PI PI
add mapped point text_in[7] text_in[7] -type PI PI
add mapped point text_in[6] text_in[6] -type PI PI
add mapped point text_in[5] text_in[5] -type PI PI
add mapped point text_in[4] text_in[4] -type PI PI
add mapped point text_in[3] text_in[3] -type PI PI
add mapped point text_in[2] text_in[2] -type PI PI
add mapped point text_in[1] text_in[1] -type PI PI
add mapped point text_in[0] text_in[0] -type PI PI

//output ports
add mapped point done done -type PO PO
add mapped point text_out[127] text_out[127] -type PO PO
add mapped point text_out[126] text_out[126] -type PO PO
add mapped point text_out[125] text_out[125] -type PO PO
add mapped point text_out[124] text_out[124] -type PO PO
add mapped point text_out[123] text_out[123] -type PO PO
add mapped point text_out[122] text_out[122] -type PO PO
add mapped point text_out[121] text_out[121] -type PO PO
add mapped point text_out[120] text_out[120] -type PO PO
add mapped point text_out[119] text_out[119] -type PO PO
add mapped point text_out[118] text_out[118] -type PO PO
add mapped point text_out[117] text_out[117] -type PO PO
add mapped point text_out[116] text_out[116] -type PO PO
add mapped point text_out[115] text_out[115] -type PO PO
add mapped point text_out[114] text_out[114] -type PO PO
add mapped point text_out[113] text_out[113] -type PO PO
add mapped point text_out[112] text_out[112] -type PO PO
add mapped point text_out[111] text_out[111] -type PO PO
add mapped point text_out[110] text_out[110] -type PO PO
add mapped point text_out[109] text_out[109] -type PO PO
add mapped point text_out[108] text_out[108] -type PO PO
add mapped point text_out[107] text_out[107] -type PO PO
add mapped point text_out[106] text_out[106] -type PO PO
add mapped point text_out[105] text_out[105] -type PO PO
add mapped point text_out[104] text_out[104] -type PO PO
add mapped point text_out[103] text_out[103] -type PO PO
add mapped point text_out[102] text_out[102] -type PO PO
add mapped point text_out[101] text_out[101] -type PO PO
add mapped point text_out[100] text_out[100] -type PO PO
add mapped point text_out[99] text_out[99] -type PO PO
add mapped point text_out[98] text_out[98] -type PO PO
add mapped point text_out[97] text_out[97] -type PO PO
add mapped point text_out[96] text_out[96] -type PO PO
add mapped point text_out[95] text_out[95] -type PO PO
add mapped point text_out[94] text_out[94] -type PO PO
add mapped point text_out[93] text_out[93] -type PO PO
add mapped point text_out[92] text_out[92] -type PO PO
add mapped point text_out[91] text_out[91] -type PO PO
add mapped point text_out[90] text_out[90] -type PO PO
add mapped point text_out[89] text_out[89] -type PO PO
add mapped point text_out[88] text_out[88] -type PO PO
add mapped point text_out[87] text_out[87] -type PO PO
add mapped point text_out[86] text_out[86] -type PO PO
add mapped point text_out[85] text_out[85] -type PO PO
add mapped point text_out[84] text_out[84] -type PO PO
add mapped point text_out[83] text_out[83] -type PO PO
add mapped point text_out[82] text_out[82] -type PO PO
add mapped point text_out[81] text_out[81] -type PO PO
add mapped point text_out[80] text_out[80] -type PO PO
add mapped point text_out[79] text_out[79] -type PO PO
add mapped point text_out[78] text_out[78] -type PO PO
add mapped point text_out[77] text_out[77] -type PO PO
add mapped point text_out[76] text_out[76] -type PO PO
add mapped point text_out[75] text_out[75] -type PO PO
add mapped point text_out[74] text_out[74] -type PO PO
add mapped point text_out[73] text_out[73] -type PO PO
add mapped point text_out[72] text_out[72] -type PO PO
add mapped point text_out[71] text_out[71] -type PO PO
add mapped point text_out[70] text_out[70] -type PO PO
add mapped point text_out[69] text_out[69] -type PO PO
add mapped point text_out[68] text_out[68] -type PO PO
add mapped point text_out[67] text_out[67] -type PO PO
add mapped point text_out[66] text_out[66] -type PO PO
add mapped point text_out[65] text_out[65] -type PO PO
add mapped point text_out[64] text_out[64] -type PO PO
add mapped point text_out[63] text_out[63] -type PO PO
add mapped point text_out[62] text_out[62] -type PO PO
add mapped point text_out[61] text_out[61] -type PO PO
add mapped point text_out[60] text_out[60] -type PO PO
add mapped point text_out[59] text_out[59] -type PO PO
add mapped point text_out[58] text_out[58] -type PO PO
add mapped point text_out[57] text_out[57] -type PO PO
add mapped point text_out[56] text_out[56] -type PO PO
add mapped point text_out[55] text_out[55] -type PO PO
add mapped point text_out[54] text_out[54] -type PO PO
add mapped point text_out[53] text_out[53] -type PO PO
add mapped point text_out[52] text_out[52] -type PO PO
add mapped point text_out[51] text_out[51] -type PO PO
add mapped point text_out[50] text_out[50] -type PO PO
add mapped point text_out[49] text_out[49] -type PO PO
add mapped point text_out[48] text_out[48] -type PO PO
add mapped point text_out[47] text_out[47] -type PO PO
add mapped point text_out[46] text_out[46] -type PO PO
add mapped point text_out[45] text_out[45] -type PO PO
add mapped point text_out[44] text_out[44] -type PO PO
add mapped point text_out[43] text_out[43] -type PO PO
add mapped point text_out[42] text_out[42] -type PO PO
add mapped point text_out[41] text_out[41] -type PO PO
add mapped point text_out[40] text_out[40] -type PO PO
add mapped point text_out[39] text_out[39] -type PO PO
add mapped point text_out[38] text_out[38] -type PO PO
add mapped point text_out[37] text_out[37] -type PO PO
add mapped point text_out[36] text_out[36] -type PO PO
add mapped point text_out[35] text_out[35] -type PO PO
add mapped point text_out[34] text_out[34] -type PO PO
add mapped point text_out[33] text_out[33] -type PO PO
add mapped point text_out[32] text_out[32] -type PO PO
add mapped point text_out[31] text_out[31] -type PO PO
add mapped point text_out[30] text_out[30] -type PO PO
add mapped point text_out[29] text_out[29] -type PO PO
add mapped point text_out[28] text_out[28] -type PO PO
add mapped point text_out[27] text_out[27] -type PO PO
add mapped point text_out[26] text_out[26] -type PO PO
add mapped point text_out[25] text_out[25] -type PO PO
add mapped point text_out[24] text_out[24] -type PO PO
add mapped point text_out[23] text_out[23] -type PO PO
add mapped point text_out[22] text_out[22] -type PO PO
add mapped point text_out[21] text_out[21] -type PO PO
add mapped point text_out[20] text_out[20] -type PO PO
add mapped point text_out[19] text_out[19] -type PO PO
add mapped point text_out[18] text_out[18] -type PO PO
add mapped point text_out[17] text_out[17] -type PO PO
add mapped point text_out[16] text_out[16] -type PO PO
add mapped point text_out[15] text_out[15] -type PO PO
add mapped point text_out[14] text_out[14] -type PO PO
add mapped point text_out[13] text_out[13] -type PO PO
add mapped point text_out[12] text_out[12] -type PO PO
add mapped point text_out[11] text_out[11] -type PO PO
add mapped point text_out[10] text_out[10] -type PO PO
add mapped point text_out[9] text_out[9] -type PO PO
add mapped point text_out[8] text_out[8] -type PO PO
add mapped point text_out[7] text_out[7] -type PO PO
add mapped point text_out[6] text_out[6] -type PO PO
add mapped point text_out[5] text_out[5] -type PO PO
add mapped point text_out[4] text_out[4] -type PO PO
add mapped point text_out[3] text_out[3] -type PO PO
add mapped point text_out[2] text_out[2] -type PO PO
add mapped point text_out[1] text_out[1] -type PO PO
add mapped point text_out[0] text_out[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point u0/r0/out[24]/q u0/r0_out_reg[24]/Q -type DFF DFF
add mapped point u0/r0/out[25]/q u0/r0_out_reg[25]/Q -type DFF DFF
add mapped point u0/r0/out[26]/q u0/r0_out_reg[26]/Q -type DFF DFF
add mapped point u0/r0/out[27]/q u0/r0_out_reg[27]/Q -type DFF DFF
add mapped point u0/r0/out[28]/q u0/r0_out_reg[28]/Q -type DFF DFF
add mapped point u0/r0/out[29]/q u0/r0_out_reg[29]/Q -type DFF DFF
add mapped point u0/r0/out[30]/q u0/r0_out_reg[30]/Q -type DFF DFF
add mapped point u0/r0/out[31]/q u0/r0_out_reg[31]/Q -type DFF DFF
add mapped point u0/r0/rcnt[0]/q u0/r0_rcnt_reg[0]/Q -type DFF DFF
add mapped point u0/r0/rcnt[1]/q u0/r0_rcnt_reg[1]/Q -type DFF DFF
add mapped point u0/r0/rcnt[2]/q u0/r0_rcnt_reg[2]/Q -type DFF DFF
add mapped point u0/r0/rcnt[3]/q u0/r0_rcnt_reg[3]/Q -type DFF DFF
add mapped point u0/w[0][0]/q u0/w_reg[0][0]/Q -type DFF DFF
add mapped point u0/w[0][1]/q u0/w_reg[0][1]/Q -type DFF DFF
add mapped point u0/w[0][2]/q u0/w_reg[0][2]/Q -type DFF DFF
add mapped point u0/w[0][3]/q u0/w_reg[0][3]/Q -type DFF DFF
add mapped point u0/w[0][4]/q u0/w_reg[0][4]/Q -type DFF DFF
add mapped point u0/w[0][5]/q u0/w_reg[0][5]/Q -type DFF DFF
add mapped point u0/w[0][6]/q u0/w_reg[0][6]/Q -type DFF DFF
add mapped point u0/w[0][7]/q u0/w_reg[0][7]/Q -type DFF DFF
add mapped point u0/w[0][8]/q u0/w_reg[0][8]/Q -type DFF DFF
add mapped point u0/w[0][9]/q u0/w_reg[0][9]/Q -type DFF DFF
add mapped point u0/w[0][10]/q u0/w_reg[0][10]/Q -type DFF DFF
add mapped point u0/w[0][11]/q u0/w_reg[0][11]/Q -type DFF DFF
add mapped point u0/w[0][12]/q u0/w_reg[0][12]/Q -type DFF DFF
add mapped point u0/w[0][13]/q u0/w_reg[0][13]/Q -type DFF DFF
add mapped point u0/w[0][14]/q u0/w_reg[0][14]/Q -type DFF DFF
add mapped point u0/w[0][15]/q u0/w_reg[0][15]/Q -type DFF DFF
add mapped point u0/w[0][16]/q u0/w_reg[0][16]/Q -type DFF DFF
add mapped point u0/w[0][17]/q u0/w_reg[0][17]/Q -type DFF DFF
add mapped point u0/w[0][18]/q u0/w_reg[0][18]/Q -type DFF DFF
add mapped point u0/w[0][19]/q u0/w_reg[0][19]/Q -type DFF DFF
add mapped point u0/w[0][20]/q u0/w_reg[0][20]/Q -type DFF DFF
add mapped point u0/w[0][21]/q u0/w_reg[0][21]/Q -type DFF DFF
add mapped point u0/w[0][22]/q u0/w_reg[0][22]/Q -type DFF DFF
add mapped point u0/w[0][23]/q u0/w_reg[0][23]/Q -type DFF DFF
add mapped point u0/w[0][24]/q u0/w_reg[0][24]/Q -type DFF DFF
add mapped point u0/w[0][25]/q u0/w_reg[0][25]/Q -type DFF DFF
add mapped point u0/w[0][26]/q u0/w_reg[0][26]/Q -type DFF DFF
add mapped point u0/w[0][27]/q u0/w_reg[0][27]/Q -type DFF DFF
add mapped point u0/w[0][28]/q u0/w_reg[0][28]/Q -type DFF DFF
add mapped point u0/w[0][29]/q u0/w_reg[0][29]/Q -type DFF DFF
add mapped point u0/w[0][30]/q u0/w_reg[0][30]/Q -type DFF DFF
add mapped point u0/w[0][31]/q u0/w_reg[0][31]/Q -type DFF DFF
add mapped point u0/w[1][0]/q u0/w_reg[1][0]/Q -type DFF DFF
add mapped point u0/w[1][1]/q u0/w_reg[1][1]/Q -type DFF DFF
add mapped point u0/w[1][2]/q u0/w_reg[1][2]/Q -type DFF DFF
add mapped point u0/w[1][3]/q u0/w_reg[1][3]/Q -type DFF DFF
add mapped point u0/w[1][4]/q u0/w_reg[1][4]/Q -type DFF DFF
add mapped point u0/w[1][5]/q u0/w_reg[1][5]/Q -type DFF DFF
add mapped point u0/w[1][6]/q u0/w_reg[1][6]/Q -type DFF DFF
add mapped point u0/w[1][7]/q u0/w_reg[1][7]/Q -type DFF DFF
add mapped point u0/w[1][8]/q u0/w_reg[1][8]/Q -type DFF DFF
add mapped point u0/w[1][9]/q u0/w_reg[1][9]/Q -type DFF DFF
add mapped point u0/w[1][10]/q u0/w_reg[1][10]/Q -type DFF DFF
add mapped point u0/w[1][11]/q u0/w_reg[1][11]/Q -type DFF DFF
add mapped point u0/w[1][12]/q u0/w_reg[1][12]/Q -type DFF DFF
add mapped point u0/w[1][13]/q u0/w_reg[1][13]/Q -type DFF DFF
add mapped point u0/w[1][14]/q u0/w_reg[1][14]/Q -type DFF DFF
add mapped point u0/w[1][15]/q u0/w_reg[1][15]/Q -type DFF DFF
add mapped point u0/w[1][16]/q u0/w_reg[1][16]/Q -type DFF DFF
add mapped point u0/w[1][17]/q u0/w_reg[1][17]/Q -type DFF DFF
add mapped point u0/w[1][18]/q u0/w_reg[1][18]/Q -type DFF DFF
add mapped point u0/w[1][19]/q u0/w_reg[1][19]/Q -type DFF DFF
add mapped point u0/w[1][20]/q u0/w_reg[1][20]/Q -type DFF DFF
add mapped point u0/w[1][21]/q u0/w_reg[1][21]/Q -type DFF DFF
add mapped point u0/w[1][22]/q u0/w_reg[1][22]/Q -type DFF DFF
add mapped point u0/w[1][23]/q u0/w_reg[1][23]/Q -type DFF DFF
add mapped point u0/w[1][24]/q u0/w_reg[1][24]/Q -type DFF DFF
add mapped point u0/w[1][25]/q u0/w_reg[1][25]/Q -type DFF DFF
add mapped point u0/w[1][26]/q u0/w_reg[1][26]/Q -type DFF DFF
add mapped point u0/w[1][27]/q u0/w_reg[1][27]/Q -type DFF DFF
add mapped point u0/w[1][28]/q u0/w_reg[1][28]/Q -type DFF DFF
add mapped point u0/w[1][29]/q u0/w_reg[1][29]/Q -type DFF DFF
add mapped point u0/w[1][30]/q u0/w_reg[1][30]/Q -type DFF DFF
add mapped point u0/w[1][31]/q u0/w_reg[1][31]/Q -type DFF DFF
add mapped point u0/w[2][0]/q u0/w_reg[2][0]/Q -type DFF DFF
add mapped point u0/w[2][1]/q u0/w_reg[2][1]/Q -type DFF DFF
add mapped point u0/w[2][2]/q u0/w_reg[2][2]/Q -type DFF DFF
add mapped point u0/w[2][3]/q u0/w_reg[2][3]/Q -type DFF DFF
add mapped point u0/w[2][4]/q u0/w_reg[2][4]/Q -type DFF DFF
add mapped point u0/w[2][5]/q u0/w_reg[2][5]/Q -type DFF DFF
add mapped point u0/w[2][6]/q u0/w_reg[2][6]/Q -type DFF DFF
add mapped point u0/w[2][7]/q u0/w_reg[2][7]/Q -type DFF DFF
add mapped point u0/w[2][8]/q u0/w_reg[2][8]/Q -type DFF DFF
add mapped point u0/w[2][9]/q u0/w_reg[2][9]/Q -type DFF DFF
add mapped point u0/w[2][10]/q u0/w_reg[2][10]/Q -type DFF DFF
add mapped point u0/w[2][11]/q u0/w_reg[2][11]/Q -type DFF DFF
add mapped point u0/w[2][12]/q u0/w_reg[2][12]/Q -type DFF DFF
add mapped point u0/w[2][13]/q u0/w_reg[2][13]/Q -type DFF DFF
add mapped point u0/w[2][14]/q u0/w_reg[2][14]/Q -type DFF DFF
add mapped point u0/w[2][15]/q u0/w_reg[2][15]/Q -type DFF DFF
add mapped point u0/w[2][16]/q u0/w_reg[2][16]/Q -type DFF DFF
add mapped point u0/w[2][17]/q u0/w_reg[2][17]/Q -type DFF DFF
add mapped point u0/w[2][18]/q u0/w_reg[2][18]/Q -type DFF DFF
add mapped point u0/w[2][19]/q u0/w_reg[2][19]/Q -type DFF DFF
add mapped point u0/w[2][20]/q u0/w_reg[2][20]/Q -type DFF DFF
add mapped point u0/w[2][21]/q u0/w_reg[2][21]/Q -type DFF DFF
add mapped point u0/w[2][22]/q u0/w_reg[2][22]/Q -type DFF DFF
add mapped point u0/w[2][23]/q u0/w_reg[2][23]/Q -type DFF DFF
add mapped point u0/w[2][24]/q u0/w_reg[2][24]/Q -type DFF DFF
add mapped point u0/w[2][25]/q u0/w_reg[2][25]/Q -type DFF DFF
add mapped point u0/w[2][26]/q u0/w_reg[2][26]/Q -type DFF DFF
add mapped point u0/w[2][27]/q u0/w_reg[2][27]/Q -type DFF DFF
add mapped point u0/w[2][28]/q u0/w_reg[2][28]/Q -type DFF DFF
add mapped point u0/w[2][29]/q u0/w_reg[2][29]/Q -type DFF DFF
add mapped point u0/w[2][30]/q u0/w_reg[2][30]/Q -type DFF DFF
add mapped point u0/w[2][31]/q u0/w_reg[2][31]/Q -type DFF DFF
add mapped point u0/w[3][0]/q u0/w_reg[3][0]/Q -type DFF DFF
add mapped point u0/w[3][1]/q u0/w_reg[3][1]/Q -type DFF DFF
add mapped point u0/w[3][2]/q u0/w_reg[3][2]/Q -type DFF DFF
add mapped point u0/w[3][3]/q u0/w_reg[3][3]/Q -type DFF DFF
add mapped point u0/w[3][4]/q u0/w_reg[3][4]/Q -type DFF DFF
add mapped point u0/w[3][5]/q u0/w_reg[3][5]/Q -type DFF DFF
add mapped point u0/w[3][6]/q u0/w_reg[3][6]/Q -type DFF DFF
add mapped point u0/w[3][7]/q u0/w_reg[3][7]/Q -type DFF DFF
add mapped point u0/w[3][8]/q u0/w_reg[3][8]/Q -type DFF DFF
add mapped point u0/w[3][9]/q u0/w_reg[3][9]/Q -type DFF DFF
add mapped point u0/w[3][10]/q u0/w_reg[3][10]/Q -type DFF DFF
add mapped point u0/w[3][11]/q u0/w_reg[3][11]/Q -type DFF DFF
add mapped point u0/w[3][12]/q u0/w_reg[3][12]/Q -type DFF DFF
add mapped point u0/w[3][13]/q u0/w_reg[3][13]/Q -type DFF DFF
add mapped point u0/w[3][14]/q u0/w_reg[3][14]/Q -type DFF DFF
add mapped point u0/w[3][15]/q u0/w_reg[3][15]/Q -type DFF DFF
add mapped point u0/w[3][16]/q u0/w_reg[3][16]/Q -type DFF DFF
add mapped point u0/w[3][17]/q u0/w_reg[3][17]/Q -type DFF DFF
add mapped point u0/w[3][18]/q u0/w_reg[3][18]/Q -type DFF DFF
add mapped point u0/w[3][19]/q u0/w_reg[3][19]/Q -type DFF DFF
add mapped point u0/w[3][20]/q u0/w_reg[3][20]/Q -type DFF DFF
add mapped point u0/w[3][21]/q u0/w_reg[3][21]/Q -type DFF DFF
add mapped point u0/w[3][22]/q u0/w_reg[3][22]/Q -type DFF DFF
add mapped point u0/w[3][23]/q u0/w_reg[3][23]/Q -type DFF DFF
add mapped point u0/w[3][24]/q u0/w_reg[3][24]/Q -type DFF DFF
add mapped point u0/w[3][25]/q u0/w_reg[3][25]/Q -type DFF DFF
add mapped point u0/w[3][26]/q u0/w_reg[3][26]/Q -type DFF DFF
add mapped point u0/w[3][27]/q u0/w_reg[3][27]/Q -type DFF DFF
add mapped point u0/w[3][28]/q u0/w_reg[3][28]/Q -type DFF DFF
add mapped point u0/w[3][29]/q u0/w_reg[3][29]/Q -type DFF DFF
add mapped point u0/w[3][30]/q u0/w_reg[3][30]/Q -type DFF DFF
add mapped point u0/w[3][31]/q u0/w_reg[3][31]/Q -type DFF DFF
add mapped point done/q done_reg/Q -type DFF DFF
add mapped point ld_r/q ld_r_reg/Q -type DFF DFF
add mapped point sa00[0]/q sa00_reg[0]/Q -type DFF DFF
add mapped point sa00[1]/q sa00_reg[1]/Q -type DFF DFF
add mapped point sa00[2]/q sa00_reg[2]/Q -type DFF DFF
add mapped point sa00[3]/q sa00_reg[3]/Q -type DFF DFF
add mapped point sa00[4]/q sa00_reg[4]/Q -type DFF DFF
add mapped point sa00[5]/q sa00_reg[5]/Q -type DFF DFF
add mapped point sa00[6]/q sa00_reg[6]/Q -type DFF DFF
add mapped point sa00[7]/q sa00_reg[7]/Q -type DFF DFF
add mapped point sa01[0]/q sa01_reg[0]/Q -type DFF DFF
add mapped point sa01[1]/q sa01_reg[1]/Q -type DFF DFF
add mapped point sa01[2]/q sa01_reg[2]/Q -type DFF DFF
add mapped point sa01[3]/q sa01_reg[3]/Q -type DFF DFF
add mapped point sa01[4]/q sa01_reg[4]/Q -type DFF DFF
add mapped point sa01[5]/q sa01_reg[5]/Q -type DFF DFF
add mapped point sa01[6]/q sa01_reg[6]/Q -type DFF DFF
add mapped point sa01[7]/q sa01_reg[7]/Q -type DFF DFF
add mapped point sa02[0]/q sa02_reg[0]/Q -type DFF DFF
add mapped point sa02[1]/q sa02_reg[1]/Q -type DFF DFF
add mapped point sa02[2]/q sa02_reg[2]/Q -type DFF DFF
add mapped point sa02[3]/q sa02_reg[3]/Q -type DFF DFF
add mapped point sa02[4]/q sa02_reg[4]/Q -type DFF DFF
add mapped point sa02[5]/q sa02_reg[5]/Q -type DFF DFF
add mapped point sa02[6]/q sa02_reg[6]/Q -type DFF DFF
add mapped point sa02[7]/q sa02_reg[7]/Q -type DFF DFF
add mapped point sa03[0]/q sa03_reg[0]/Q -type DFF DFF
add mapped point sa03[1]/q sa03_reg[1]/Q -type DFF DFF
add mapped point sa03[2]/q sa03_reg[2]/Q -type DFF DFF
add mapped point sa03[3]/q sa03_reg[3]/Q -type DFF DFF
add mapped point sa03[4]/q sa03_reg[4]/Q -type DFF DFF
add mapped point sa03[5]/q sa03_reg[5]/Q -type DFF DFF
add mapped point sa03[6]/q sa03_reg[6]/Q -type DFF DFF
add mapped point sa03[7]/q sa03_reg[7]/Q -type DFF DFF
add mapped point sa10[0]/q sa10_reg[0]/Q -type DFF DFF
add mapped point sa10[1]/q sa10_reg[1]/Q -type DFF DFF
add mapped point sa10[2]/q sa10_reg[2]/Q -type DFF DFF
add mapped point sa10[3]/q sa10_reg[3]/Q -type DFF DFF
add mapped point sa10[4]/q sa10_reg[4]/Q -type DFF DFF
add mapped point sa10[5]/q sa10_reg[5]/Q -type DFF DFF
add mapped point sa10[6]/q sa10_reg[6]/Q -type DFF DFF
add mapped point sa10[7]/q sa10_reg[7]/Q -type DFF DFF
add mapped point sa11[0]/q sa11_reg[0]/Q -type DFF DFF
add mapped point sa11[1]/q sa11_reg[1]/Q -type DFF DFF
add mapped point sa11[2]/q sa11_reg[2]/Q -type DFF DFF
add mapped point sa11[3]/q sa11_reg[3]/Q -type DFF DFF
add mapped point sa11[4]/q sa11_reg[4]/Q -type DFF DFF
add mapped point sa11[5]/q sa11_reg[5]/Q -type DFF DFF
add mapped point sa11[6]/q sa11_reg[6]/Q -type DFF DFF
add mapped point sa11[7]/q sa11_reg[7]/Q -type DFF DFF
add mapped point sa12[0]/q sa12_reg[0]/Q -type DFF DFF
add mapped point sa12[1]/q sa12_reg[1]/Q -type DFF DFF
add mapped point sa12[2]/q sa12_reg[2]/Q -type DFF DFF
add mapped point sa12[3]/q sa12_reg[3]/Q -type DFF DFF
add mapped point sa12[4]/q sa12_reg[4]/Q -type DFF DFF
add mapped point sa12[5]/q sa12_reg[5]/Q -type DFF DFF
add mapped point sa12[6]/q sa12_reg[6]/Q -type DFF DFF
add mapped point sa12[7]/q sa12_reg[7]/Q -type DFF DFF
add mapped point sa13[0]/q sa13_reg[0]/Q -type DFF DFF
add mapped point sa13[1]/q sa13_reg[1]/Q -type DFF DFF
add mapped point sa13[2]/q sa13_reg[2]/Q -type DFF DFF
add mapped point sa13[3]/q sa13_reg[3]/Q -type DFF DFF
add mapped point sa13[4]/q sa13_reg[4]/Q -type DFF DFF
add mapped point sa13[5]/q sa13_reg[5]/Q -type DFF DFF
add mapped point sa13[6]/q sa13_reg[6]/Q -type DFF DFF
add mapped point sa13[7]/q sa13_reg[7]/Q -type DFF DFF
add mapped point sa20[0]/q sa20_reg[0]/Q -type DFF DFF
add mapped point sa20[1]/q sa20_reg[1]/Q -type DFF DFF
add mapped point sa20[2]/q sa20_reg[2]/Q -type DFF DFF
add mapped point sa20[3]/q sa20_reg[3]/Q -type DFF DFF
add mapped point sa20[4]/q sa20_reg[4]/Q -type DFF DFF
add mapped point sa20[5]/q sa20_reg[5]/Q -type DFF DFF
add mapped point sa20[6]/q sa20_reg[6]/Q -type DFF DFF
add mapped point sa20[7]/q sa20_reg[7]/Q -type DFF DFF
add mapped point sa21[0]/q sa21_reg[0]/Q -type DFF DFF
add mapped point sa21[1]/q sa21_reg[1]/Q -type DFF DFF
add mapped point sa21[2]/q sa21_reg[2]/Q -type DFF DFF
add mapped point sa21[3]/q sa21_reg[3]/Q -type DFF DFF
add mapped point sa21[4]/q sa21_reg[4]/Q -type DFF DFF
add mapped point sa21[5]/q sa21_reg[5]/Q -type DFF DFF
add mapped point sa21[6]/q sa21_reg[6]/Q -type DFF DFF
add mapped point sa21[7]/q sa21_reg[7]/Q -type DFF DFF
add mapped point sa22[0]/q sa22_reg[0]/Q -type DFF DFF
add mapped point sa22[1]/q sa22_reg[1]/Q -type DFF DFF
add mapped point sa22[2]/q sa22_reg[2]/Q -type DFF DFF
add mapped point sa22[3]/q sa22_reg[3]/Q -type DFF DFF
add mapped point sa22[4]/q sa22_reg[4]/Q -type DFF DFF
add mapped point sa22[5]/q sa22_reg[5]/Q -type DFF DFF
add mapped point sa22[6]/q sa22_reg[6]/Q -type DFF DFF
add mapped point sa22[7]/q sa22_reg[7]/Q -type DFF DFF
add mapped point sa23[0]/q sa23_reg[0]/Q -type DFF DFF
add mapped point sa23[1]/q sa23_reg[1]/Q -type DFF DFF
add mapped point sa23[2]/q sa23_reg[2]/Q -type DFF DFF
add mapped point sa23[3]/q sa23_reg[3]/Q -type DFF DFF
add mapped point sa23[4]/q sa23_reg[4]/Q -type DFF DFF
add mapped point sa23[5]/q sa23_reg[5]/Q -type DFF DFF
add mapped point sa23[6]/q sa23_reg[6]/Q -type DFF DFF
add mapped point sa23[7]/q sa23_reg[7]/Q -type DFF DFF
add mapped point sa30[0]/q sa30_reg[0]/Q -type DFF DFF
add mapped point sa30[1]/q sa30_reg[1]/Q -type DFF DFF
add mapped point sa30[2]/q sa30_reg[2]/Q -type DFF DFF
add mapped point sa30[3]/q sa30_reg[3]/Q -type DFF DFF
add mapped point sa30[4]/q sa30_reg[4]/Q -type DFF DFF
add mapped point sa30[5]/q sa30_reg[5]/Q -type DFF DFF
add mapped point sa30[6]/q sa30_reg[6]/Q -type DFF DFF
add mapped point sa30[7]/q sa30_reg[7]/Q -type DFF DFF
add mapped point sa31[0]/q sa31_reg[0]/Q -type DFF DFF
add mapped point sa31[1]/q sa31_reg[1]/Q -type DFF DFF
add mapped point sa31[2]/q sa31_reg[2]/Q -type DFF DFF
add mapped point sa31[3]/q sa31_reg[3]/Q -type DFF DFF
add mapped point sa31[4]/q sa31_reg[4]/Q -type DFF DFF
add mapped point sa31[5]/q sa31_reg[5]/Q -type DFF DFF
add mapped point sa31[6]/q sa31_reg[6]/Q -type DFF DFF
add mapped point sa31[7]/q sa31_reg[7]/Q -type DFF DFF
add mapped point sa32[0]/q sa32_reg[0]/Q -type DFF DFF
add mapped point sa32[1]/q sa32_reg[1]/Q -type DFF DFF
add mapped point sa32[2]/q sa32_reg[2]/Q -type DFF DFF
add mapped point sa32[3]/q sa32_reg[3]/Q -type DFF DFF
add mapped point sa32[4]/q sa32_reg[4]/Q -type DFF DFF
add mapped point sa32[5]/q sa32_reg[5]/Q -type DFF DFF
add mapped point sa32[6]/q sa32_reg[6]/Q -type DFF DFF
add mapped point sa32[7]/q sa32_reg[7]/Q -type DFF DFF
add mapped point sa33[0]/q sa33_reg[0]/Q -type DFF DFF
add mapped point sa33[1]/q sa33_reg[1]/Q -type DFF DFF
add mapped point sa33[2]/q sa33_reg[2]/Q -type DFF DFF
add mapped point sa33[3]/q sa33_reg[3]/Q -type DFF DFF
add mapped point sa33[4]/q sa33_reg[4]/Q -type DFF DFF
add mapped point sa33[5]/q sa33_reg[5]/Q -type DFF DFF
add mapped point sa33[6]/q sa33_reg[6]/Q -type DFF DFF
add mapped point sa33[7]/q sa33_reg[7]/Q -type DFF DFF
add mapped point text_in_r[0]/q text_in_r_reg[0]/Q -type DFF DFF
add mapped point text_in_r[1]/q text_in_r_reg[1]/Q -type DFF DFF
add mapped point text_in_r[2]/q text_in_r_reg[2]/Q -type DFF DFF
add mapped point text_in_r[3]/q text_in_r_reg[3]/Q -type DFF DFF
add mapped point text_in_r[4]/q text_in_r_reg[4]/Q -type DFF DFF
add mapped point text_in_r[5]/q text_in_r_reg[5]/Q -type DFF DFF
add mapped point text_in_r[6]/q text_in_r_reg[6]/Q -type DFF DFF
add mapped point text_in_r[7]/q text_in_r_reg[7]/Q -type DFF DFF
add mapped point text_in_r[8]/q text_in_r_reg[8]/Q -type DFF DFF
add mapped point text_in_r[9]/q text_in_r_reg[9]/Q -type DFF DFF
add mapped point text_in_r[10]/q text_in_r_reg[10]/Q -type DFF DFF
add mapped point text_in_r[11]/q text_in_r_reg[11]/Q -type DFF DFF
add mapped point text_in_r[12]/q text_in_r_reg[12]/Q -type DFF DFF
add mapped point text_in_r[13]/q text_in_r_reg[13]/Q -type DFF DFF
add mapped point text_in_r[14]/q text_in_r_reg[14]/Q -type DFF DFF
add mapped point text_in_r[15]/q text_in_r_reg[15]/Q -type DFF DFF
add mapped point text_in_r[16]/q text_in_r_reg[16]/Q -type DFF DFF
add mapped point text_in_r[17]/q text_in_r_reg[17]/Q -type DFF DFF
add mapped point text_in_r[18]/q text_in_r_reg[18]/Q -type DFF DFF
add mapped point text_in_r[19]/q text_in_r_reg[19]/Q -type DFF DFF
add mapped point text_in_r[20]/q text_in_r_reg[20]/Q -type DFF DFF
add mapped point text_in_r[21]/q text_in_r_reg[21]/Q -type DFF DFF
add mapped point text_in_r[22]/q text_in_r_reg[22]/Q -type DFF DFF
add mapped point text_in_r[23]/q text_in_r_reg[23]/Q -type DFF DFF
add mapped point text_in_r[24]/q text_in_r_reg[24]/Q -type DFF DFF
add mapped point text_in_r[25]/q text_in_r_reg[25]/Q -type DFF DFF
add mapped point text_in_r[26]/q text_in_r_reg[26]/Q -type DFF DFF
add mapped point text_in_r[27]/q text_in_r_reg[27]/Q -type DFF DFF
add mapped point text_in_r[28]/q text_in_r_reg[28]/Q -type DFF DFF
add mapped point text_in_r[29]/q text_in_r_reg[29]/Q -type DFF DFF
add mapped point text_in_r[30]/q text_in_r_reg[30]/Q -type DFF DFF
add mapped point text_in_r[31]/q text_in_r_reg[31]/Q -type DFF DFF
add mapped point text_in_r[32]/q text_in_r_reg[32]/Q -type DFF DFF
add mapped point text_in_r[33]/q text_in_r_reg[33]/Q -type DFF DFF
add mapped point text_in_r[34]/q text_in_r_reg[34]/Q -type DFF DFF
add mapped point text_in_r[35]/q text_in_r_reg[35]/Q -type DFF DFF
add mapped point text_in_r[36]/q text_in_r_reg[36]/Q -type DFF DFF
add mapped point text_in_r[37]/q text_in_r_reg[37]/Q -type DFF DFF
add mapped point text_in_r[38]/q text_in_r_reg[38]/Q -type DFF DFF
add mapped point text_in_r[39]/q text_in_r_reg[39]/Q -type DFF DFF
add mapped point text_in_r[40]/q text_in_r_reg[40]/Q -type DFF DFF
add mapped point text_in_r[41]/q text_in_r_reg[41]/Q -type DFF DFF
add mapped point text_in_r[42]/q text_in_r_reg[42]/Q -type DFF DFF
add mapped point text_in_r[43]/q text_in_r_reg[43]/Q -type DFF DFF
add mapped point text_in_r[44]/q text_in_r_reg[44]/Q -type DFF DFF
add mapped point text_in_r[45]/q text_in_r_reg[45]/Q -type DFF DFF
add mapped point text_in_r[46]/q text_in_r_reg[46]/Q -type DFF DFF
add mapped point text_in_r[47]/q text_in_r_reg[47]/Q -type DFF DFF
add mapped point text_in_r[48]/q text_in_r_reg[48]/Q -type DFF DFF
add mapped point text_in_r[49]/q text_in_r_reg[49]/Q -type DFF DFF
add mapped point text_in_r[50]/q text_in_r_reg[50]/Q -type DFF DFF
add mapped point text_in_r[51]/q text_in_r_reg[51]/Q -type DFF DFF
add mapped point text_in_r[52]/q text_in_r_reg[52]/Q -type DFF DFF
add mapped point text_in_r[53]/q text_in_r_reg[53]/Q -type DFF DFF
add mapped point text_in_r[54]/q text_in_r_reg[54]/Q -type DFF DFF
add mapped point text_in_r[55]/q text_in_r_reg[55]/Q -type DFF DFF
add mapped point text_in_r[56]/q text_in_r_reg[56]/Q -type DFF DFF
add mapped point text_in_r[57]/q text_in_r_reg[57]/Q -type DFF DFF
add mapped point text_in_r[58]/q text_in_r_reg[58]/Q -type DFF DFF
add mapped point text_in_r[59]/q text_in_r_reg[59]/Q -type DFF DFF
add mapped point text_in_r[60]/q text_in_r_reg[60]/Q -type DFF DFF
add mapped point text_in_r[61]/q text_in_r_reg[61]/Q -type DFF DFF
add mapped point text_in_r[62]/q text_in_r_reg[62]/Q -type DFF DFF
add mapped point text_in_r[63]/q text_in_r_reg[63]/Q -type DFF DFF
add mapped point text_in_r[64]/q text_in_r_reg[64]/Q -type DFF DFF
add mapped point text_in_r[65]/q text_in_r_reg[65]/Q -type DFF DFF
add mapped point text_in_r[66]/q text_in_r_reg[66]/Q -type DFF DFF
add mapped point text_in_r[67]/q text_in_r_reg[67]/Q -type DFF DFF
add mapped point text_in_r[68]/q text_in_r_reg[68]/Q -type DFF DFF
add mapped point text_in_r[69]/q text_in_r_reg[69]/Q -type DFF DFF
add mapped point text_in_r[70]/q text_in_r_reg[70]/Q -type DFF DFF
add mapped point text_in_r[71]/q text_in_r_reg[71]/Q -type DFF DFF
add mapped point text_in_r[72]/q text_in_r_reg[72]/Q -type DFF DFF
add mapped point text_in_r[73]/q text_in_r_reg[73]/Q -type DFF DFF
add mapped point text_in_r[74]/q text_in_r_reg[74]/Q -type DFF DFF
add mapped point text_in_r[75]/q text_in_r_reg[75]/Q -type DFF DFF
add mapped point text_in_r[76]/q text_in_r_reg[76]/Q -type DFF DFF
add mapped point text_in_r[77]/q text_in_r_reg[77]/Q -type DFF DFF
add mapped point text_in_r[78]/q text_in_r_reg[78]/Q -type DFF DFF
add mapped point text_in_r[79]/q text_in_r_reg[79]/Q -type DFF DFF
add mapped point text_in_r[80]/q text_in_r_reg[80]/Q -type DFF DFF
add mapped point text_in_r[81]/q text_in_r_reg[81]/Q -type DFF DFF
add mapped point text_in_r[82]/q text_in_r_reg[82]/Q -type DFF DFF
add mapped point text_in_r[83]/q text_in_r_reg[83]/Q -type DFF DFF
add mapped point text_in_r[84]/q text_in_r_reg[84]/Q -type DFF DFF
add mapped point text_in_r[85]/q text_in_r_reg[85]/Q -type DFF DFF
add mapped point text_in_r[86]/q text_in_r_reg[86]/Q -type DFF DFF
add mapped point text_in_r[87]/q text_in_r_reg[87]/Q -type DFF DFF
add mapped point text_in_r[88]/q text_in_r_reg[88]/Q -type DFF DFF
add mapped point text_in_r[89]/q text_in_r_reg[89]/Q -type DFF DFF
add mapped point text_in_r[90]/q text_in_r_reg[90]/Q -type DFF DFF
add mapped point text_in_r[91]/q text_in_r_reg[91]/Q -type DFF DFF
add mapped point text_in_r[92]/q text_in_r_reg[92]/Q -type DFF DFF
add mapped point text_in_r[93]/q text_in_r_reg[93]/Q -type DFF DFF
add mapped point text_in_r[94]/q text_in_r_reg[94]/Q -type DFF DFF
add mapped point text_in_r[95]/q text_in_r_reg[95]/Q -type DFF DFF
add mapped point text_in_r[96]/q text_in_r_reg[96]/Q -type DFF DFF
add mapped point text_in_r[97]/q text_in_r_reg[97]/Q -type DFF DFF
add mapped point text_in_r[98]/q text_in_r_reg[98]/Q -type DFF DFF
add mapped point text_in_r[99]/q text_in_r_reg[99]/Q -type DFF DFF
add mapped point text_in_r[100]/q text_in_r_reg[100]/Q -type DFF DFF
add mapped point text_in_r[101]/q text_in_r_reg[101]/Q -type DFF DFF
add mapped point text_in_r[102]/q text_in_r_reg[102]/Q -type DFF DFF
add mapped point text_in_r[103]/q text_in_r_reg[103]/Q -type DFF DFF
add mapped point text_in_r[104]/q text_in_r_reg[104]/Q -type DFF DFF
add mapped point text_in_r[105]/q text_in_r_reg[105]/Q -type DFF DFF
add mapped point text_in_r[106]/q text_in_r_reg[106]/Q -type DFF DFF
add mapped point text_in_r[107]/q text_in_r_reg[107]/Q -type DFF DFF
add mapped point text_in_r[108]/q text_in_r_reg[108]/Q -type DFF DFF
add mapped point text_in_r[109]/q text_in_r_reg[109]/Q -type DFF DFF
add mapped point text_in_r[110]/q text_in_r_reg[110]/Q -type DFF DFF
add mapped point text_in_r[111]/q text_in_r_reg[111]/Q -type DFF DFF
add mapped point text_in_r[112]/q text_in_r_reg[112]/Q -type DFF DFF
add mapped point text_in_r[113]/q text_in_r_reg[113]/Q -type DFF DFF
add mapped point text_in_r[114]/q text_in_r_reg[114]/Q -type DFF DFF
add mapped point text_in_r[115]/q text_in_r_reg[115]/Q -type DFF DFF
add mapped point text_in_r[116]/q text_in_r_reg[116]/Q -type DFF DFF
add mapped point text_in_r[117]/q text_in_r_reg[117]/Q -type DFF DFF
add mapped point text_in_r[118]/q text_in_r_reg[118]/Q -type DFF DFF
add mapped point text_in_r[119]/q text_in_r_reg[119]/Q -type DFF DFF
add mapped point text_in_r[120]/q text_in_r_reg[120]/Q -type DFF DFF
add mapped point text_in_r[121]/q text_in_r_reg[121]/Q -type DFF DFF
add mapped point text_in_r[122]/q text_in_r_reg[122]/Q -type DFF DFF
add mapped point text_in_r[123]/q text_in_r_reg[123]/Q -type DFF DFF
add mapped point text_in_r[124]/q text_in_r_reg[124]/Q -type DFF DFF
add mapped point text_in_r[125]/q text_in_r_reg[125]/Q -type DFF DFF
add mapped point text_in_r[126]/q text_in_r_reg[126]/Q -type DFF DFF
add mapped point text_in_r[127]/q text_in_r_reg[127]/Q -type DFF DFF
add mapped point text_out[0]/q text_out_reg[0]/Q -type DFF DFF
add mapped point text_out[1]/q text_out_reg[1]/Q -type DFF DFF
add mapped point text_out[2]/q text_out_reg[2]/Q -type DFF DFF
add mapped point text_out[3]/q text_out_reg[3]/Q -type DFF DFF
add mapped point text_out[4]/q text_out_reg[4]/Q -type DFF DFF
add mapped point text_out[5]/q text_out_reg[5]/Q -type DFF DFF
add mapped point text_out[6]/q text_out_reg[6]/Q -type DFF DFF
add mapped point text_out[7]/q text_out_reg[7]/Q -type DFF DFF
add mapped point text_out[8]/q text_out_reg[8]/Q -type DFF DFF
add mapped point text_out[9]/q text_out_reg[9]/Q -type DFF DFF
add mapped point text_out[10]/q text_out_reg[10]/Q -type DFF DFF
add mapped point text_out[11]/q text_out_reg[11]/Q -type DFF DFF
add mapped point text_out[12]/q text_out_reg[12]/Q -type DFF DFF
add mapped point text_out[13]/q text_out_reg[13]/Q -type DFF DFF
add mapped point text_out[14]/q text_out_reg[14]/Q -type DFF DFF
add mapped point text_out[15]/q text_out_reg[15]/Q -type DFF DFF
add mapped point text_out[16]/q text_out_reg[16]/Q -type DFF DFF
add mapped point text_out[17]/q text_out_reg[17]/Q -type DFF DFF
add mapped point text_out[18]/q text_out_reg[18]/Q -type DFF DFF
add mapped point text_out[19]/q text_out_reg[19]/Q -type DFF DFF
add mapped point text_out[20]/q text_out_reg[20]/Q -type DFF DFF
add mapped point text_out[21]/q text_out_reg[21]/Q -type DFF DFF
add mapped point text_out[22]/q text_out_reg[22]/Q -type DFF DFF
add mapped point text_out[23]/q text_out_reg[23]/Q -type DFF DFF
add mapped point text_out[24]/q text_out_reg[24]/Q -type DFF DFF
add mapped point text_out[25]/q text_out_reg[25]/Q -type DFF DFF
add mapped point text_out[26]/q text_out_reg[26]/Q -type DFF DFF
add mapped point text_out[27]/q text_out_reg[27]/Q -type DFF DFF
add mapped point text_out[28]/q text_out_reg[28]/Q -type DFF DFF
add mapped point text_out[29]/q text_out_reg[29]/Q -type DFF DFF
add mapped point text_out[30]/q text_out_reg[30]/Q -type DFF DFF
add mapped point text_out[31]/q text_out_reg[31]/Q -type DFF DFF
add mapped point text_out[32]/q text_out_reg[32]/Q -type DFF DFF
add mapped point text_out[33]/q text_out_reg[33]/Q -type DFF DFF
add mapped point text_out[34]/q text_out_reg[34]/Q -type DFF DFF
add mapped point text_out[35]/q text_out_reg[35]/Q -type DFF DFF
add mapped point text_out[36]/q text_out_reg[36]/Q -type DFF DFF
add mapped point text_out[37]/q text_out_reg[37]/Q -type DFF DFF
add mapped point text_out[38]/q text_out_reg[38]/Q -type DFF DFF
add mapped point text_out[39]/q text_out_reg[39]/Q -type DFF DFF
add mapped point text_out[40]/q text_out_reg[40]/Q -type DFF DFF
add mapped point text_out[41]/q text_out_reg[41]/Q -type DFF DFF
add mapped point text_out[42]/q text_out_reg[42]/Q -type DFF DFF
add mapped point text_out[43]/q text_out_reg[43]/Q -type DFF DFF
add mapped point text_out[44]/q text_out_reg[44]/Q -type DFF DFF
add mapped point text_out[45]/q text_out_reg[45]/Q -type DFF DFF
add mapped point text_out[46]/q text_out_reg[46]/Q -type DFF DFF
add mapped point text_out[47]/q text_out_reg[47]/Q -type DFF DFF
add mapped point text_out[48]/q text_out_reg[48]/Q -type DFF DFF
add mapped point text_out[49]/q text_out_reg[49]/Q -type DFF DFF
add mapped point text_out[50]/q text_out_reg[50]/Q -type DFF DFF
add mapped point text_out[51]/q text_out_reg[51]/Q -type DFF DFF
add mapped point text_out[52]/q text_out_reg[52]/Q -type DFF DFF
add mapped point text_out[53]/q text_out_reg[53]/Q -type DFF DFF
add mapped point text_out[54]/q text_out_reg[54]/Q -type DFF DFF
add mapped point text_out[55]/q text_out_reg[55]/Q -type DFF DFF
add mapped point text_out[56]/q text_out_reg[56]/Q -type DFF DFF
add mapped point text_out[57]/q text_out_reg[57]/Q -type DFF DFF
add mapped point text_out[58]/q text_out_reg[58]/Q -type DFF DFF
add mapped point text_out[59]/q text_out_reg[59]/Q -type DFF DFF
add mapped point text_out[60]/q text_out_reg[60]/Q -type DFF DFF
add mapped point text_out[61]/q text_out_reg[61]/Q -type DFF DFF
add mapped point text_out[62]/q text_out_reg[62]/Q -type DFF DFF
add mapped point text_out[63]/q text_out_reg[63]/Q -type DFF DFF
add mapped point text_out[64]/q text_out_reg[64]/Q -type DFF DFF
add mapped point text_out[65]/q text_out_reg[65]/Q -type DFF DFF
add mapped point text_out[66]/q text_out_reg[66]/Q -type DFF DFF
add mapped point text_out[67]/q text_out_reg[67]/Q -type DFF DFF
add mapped point text_out[68]/q text_out_reg[68]/Q -type DFF DFF
add mapped point text_out[69]/q text_out_reg[69]/Q -type DFF DFF
add mapped point text_out[70]/q text_out_reg[70]/Q -type DFF DFF
add mapped point text_out[71]/q text_out_reg[71]/Q -type DFF DFF
add mapped point text_out[72]/q text_out_reg[72]/Q -type DFF DFF
add mapped point text_out[73]/q text_out_reg[73]/Q -type DFF DFF
add mapped point text_out[74]/q text_out_reg[74]/Q -type DFF DFF
add mapped point text_out[75]/q text_out_reg[75]/Q -type DFF DFF
add mapped point text_out[76]/q text_out_reg[76]/Q -type DFF DFF
add mapped point text_out[77]/q text_out_reg[77]/Q -type DFF DFF
add mapped point text_out[78]/q text_out_reg[78]/Q -type DFF DFF
add mapped point text_out[79]/q text_out_reg[79]/Q -type DFF DFF
add mapped point text_out[80]/q text_out_reg[80]/Q -type DFF DFF
add mapped point text_out[81]/q text_out_reg[81]/Q -type DFF DFF
add mapped point text_out[82]/q text_out_reg[82]/Q -type DFF DFF
add mapped point text_out[83]/q text_out_reg[83]/Q -type DFF DFF
add mapped point text_out[84]/q text_out_reg[84]/Q -type DFF DFF
add mapped point text_out[85]/q text_out_reg[85]/Q -type DFF DFF
add mapped point text_out[86]/q text_out_reg[86]/Q -type DFF DFF
add mapped point text_out[87]/q text_out_reg[87]/Q -type DFF DFF
add mapped point text_out[88]/q text_out_reg[88]/Q -type DFF DFF
add mapped point text_out[89]/q text_out_reg[89]/Q -type DFF DFF
add mapped point text_out[90]/q text_out_reg[90]/Q -type DFF DFF
add mapped point text_out[91]/q text_out_reg[91]/Q -type DFF DFF
add mapped point text_out[92]/q text_out_reg[92]/Q -type DFF DFF
add mapped point text_out[93]/q text_out_reg[93]/Q -type DFF DFF
add mapped point text_out[94]/q text_out_reg[94]/Q -type DFF DFF
add mapped point text_out[95]/q text_out_reg[95]/Q -type DFF DFF
add mapped point text_out[96]/q text_out_reg[96]/Q -type DFF DFF
add mapped point text_out[97]/q text_out_reg[97]/Q -type DFF DFF
add mapped point text_out[98]/q text_out_reg[98]/Q -type DFF DFF
add mapped point text_out[99]/q text_out_reg[99]/Q -type DFF DFF
add mapped point text_out[100]/q text_out_reg[100]/Q -type DFF DFF
add mapped point text_out[101]/q text_out_reg[101]/Q -type DFF DFF
add mapped point text_out[102]/q text_out_reg[102]/Q -type DFF DFF
add mapped point text_out[103]/q text_out_reg[103]/Q -type DFF DFF
add mapped point text_out[104]/q text_out_reg[104]/Q -type DFF DFF
add mapped point text_out[105]/q text_out_reg[105]/Q -type DFF DFF
add mapped point text_out[106]/q text_out_reg[106]/Q -type DFF DFF
add mapped point text_out[107]/q text_out_reg[107]/Q -type DFF DFF
add mapped point text_out[108]/q text_out_reg[108]/Q -type DFF DFF
add mapped point text_out[109]/q text_out_reg[109]/Q -type DFF DFF
add mapped point text_out[110]/q text_out_reg[110]/Q -type DFF DFF
add mapped point text_out[111]/q text_out_reg[111]/Q -type DFF DFF
add mapped point text_out[112]/q text_out_reg[112]/Q -type DFF DFF
add mapped point text_out[113]/q text_out_reg[113]/Q -type DFF DFF
add mapped point text_out[114]/q text_out_reg[114]/Q -type DFF DFF
add mapped point text_out[115]/q text_out_reg[115]/Q -type DFF DFF
add mapped point text_out[116]/q text_out_reg[116]/Q -type DFF DFF
add mapped point text_out[117]/q text_out_reg[117]/Q -type DFF DFF
add mapped point text_out[118]/q text_out_reg[118]/Q -type DFF DFF
add mapped point text_out[119]/q text_out_reg[119]/Q -type DFF DFF
add mapped point text_out[120]/q text_out_reg[120]/Q -type DFF DFF
add mapped point text_out[121]/q text_out_reg[121]/Q -type DFF DFF
add mapped point text_out[122]/q text_out_reg[122]/Q -type DFF DFF
add mapped point text_out[123]/q text_out_reg[123]/Q -type DFF DFF
add mapped point text_out[124]/q text_out_reg[124]/Q -type DFF DFF
add mapped point text_out[125]/q text_out_reg[125]/Q -type DFF DFF
add mapped point text_out[126]/q text_out_reg[126]/Q -type DFF DFF
add mapped point text_out[127]/q text_out_reg[127]/Q -type DFF DFF
add mapped point dcnt[2]/q dcnt_reg[2]/Q -type DFF DFF
add mapped point dcnt[3]/q dcnt_reg[3]/Q -type DFF DFF
add mapped point dcnt[1]/q dcnt_reg[1]/Q -type DFF DFF
add mapped point dcnt[0]/q dcnt_reg[0]/Q -type DFF DFF



//Black Boxes
add mapped point u0/u0 u0/u0 -type BBOX BBOX
add mapped point u0/u1 u0/u1 -type BBOX BBOX
add mapped point u0/u2 u0/u2 -type BBOX BBOX
add mapped point u0/u3 u0/u3 -type BBOX BBOX
add mapped point us00 us00 -type BBOX BBOX
add mapped point us01 us01 -type BBOX BBOX
add mapped point us02 us02 -type BBOX BBOX
add mapped point us03 us03 -type BBOX BBOX
add mapped point us10 us10 -type BBOX BBOX
add mapped point us11 us11 -type BBOX BBOX
add mapped point us12 us12 -type BBOX BBOX
add mapped point us13 us13 -type BBOX BBOX
add mapped point us20 us20 -type BBOX BBOX
add mapped point us21 us21 -type BBOX BBOX
add mapped point us22 us22 -type BBOX BBOX
add mapped point us23 us23 -type BBOX BBOX
add mapped point us30 us30 -type BBOX BBOX
add mapped point us31 us31 -type BBOX BBOX
add mapped point us32 us32 -type BBOX BBOX
add mapped point us33 us33 -type BBOX BBOX



//Empty Modules as Blackboxes
